export const ENGINEERING_INTELLIGENCE_CONTRACT_VERSION = "1.0" as const;
export type IntelligenceAuthority="source-authoritative"|"backend-derived"|"frontend-derived"|"hardcoded"|"mocked";
export type IntelligenceAssertionKind="fact"|"inference"|"finding";
export type SourceExtractionStatus="available"|"partial"|"unavailable"|"failed"|"cancelled"|"timed-out"|"capability-limited"|"not-observed";
export type TemporalContext={requestedAt?:string;capturedAt?:string;assembledAt:string;effectiveAt?:string;validFrom?:string;validTo?:string;freshness:"current"|"stale"|"unknown"|"not-applicable"};
export type EngineeringProvenance={source?:"teamcenter"|"windchill"|"sap"|"configit";provider:string;nativeId?:string;nativeRevision?:string;sourceExecutionId?:string;artifactReference?:string;checksum?:string;observedAt:string;authority:IntelligenceAuthority};
export type IntelligenceProperty={type:string;text?:string;number?:number;boolean?:boolean;timestamp?:string;items?:string[];reference?:string};
export type IntelligenceEntity={id:string;kind:string;displayName:string;identityQuality:"native"|"deterministic-derived"|"provisional";assertion:IntelligenceAssertionKind;properties:Record<string,IntelligenceProperty>;provenance:EngineeringProvenance;temporal:TemporalContext};
export type IntelligenceRelationship={id:string;kind:string;family:string;sourceEntityId:string;targetEntityId:string;assertion:IntelligenceAssertionKind;confidence?:string;evidenceIds:string[];properties:Record<string,IntelligenceProperty>;provenance:EngineeringProvenance;temporal:TemporalContext};
export type EngineeringIntelligenceInvestigationV1={contractVersion:typeof ENGINEERING_INTELLIGENCE_CONTRACT_VERSION;investigationId:string;subject:{id:string;displayName:string;preferredProductId?:string;candidateIds:string[];confidence:string;reasons:string[];provenance:EngineeringProvenance;temporal:TemporalContext};entities:IntelligenceEntity[];relationships:IntelligenceRelationship[];evidence:Array<{id:string;kind:string;summary:string;source:string;provenance:EngineeringProvenance;temporal:TemporalContext}>;findings:Array<{id:string;kind:string;title:string;summary:string;subjectEntityIds:string[];evidenceIds:string[];provenance:EngineeringProvenance;temporal:TemporalContext}>;sources:Array<{entityId:string;source:string;status:SourceExtractionStatus;provenance:EngineeringProvenance}>;identityClusters:Array<{id:string;preferredEntityId?:string;entityIds:string[];confidence:string;reasons:string[];evidenceIds:string[]}>;temporal:TemporalContext;summary:{entityCount:number;relationshipCount:number;evidenceCount:number;findingCount:number;availableSourceCount:number;partialSourceCount:number;status:string}};
export function isEngineeringIntelligenceInvestigationV1(value:unknown):value is EngineeringIntelligenceInvestigationV1{if(!value||typeof value!=="object")return false;const v=value as Record<string,unknown>;return v.contractVersion===ENGINEERING_INTELLIGENCE_CONTRACT_VERSION&&typeof v.investigationId==="string"&&!!v.subject&&Array.isArray(v.entities)&&Array.isArray(v.relationships)&&Array.isArray(v.evidence)&&Array.isArray(v.findings)&&Array.isArray(v.sources)&&Array.isArray(v.identityClusters);}
