import { NextRequest, NextResponse } from "next/server";
import type { EngineeringIntelligenceInvestigationV1, IntelligenceEntity, IntelligenceProperty, IntelligenceRelationship } from "@/features/lattice-next/contracts/intelligence-v1";
import type { LatticeHandoff } from "@/features/lattice-next/contracts/handoff";

const API=(process.env.ORCHESTRATION_API_URL??process.env.NEXT_PUBLIC_API_URL??"http://localhost:5212").replace(/\/$/,"");
const safe=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"unknown";
const now=()=>new Date().toISOString();
const prop=(value:unknown):IntelligenceProperty=>typeof value==="number"?{type:"number",number:value}:typeof value==="boolean"?{type:"boolean",boolean:value}:Array.isArray(value)?{type:"items",items:value.map(String).slice(0,100)}:{type:"text",text:value==null?"":String(value)};
const properties=(input:Record<string,unknown>)=>Object.fromEntries(Object.entries(input).filter(([,v])=>v!==null&&v!==undefined&&typeof v!=="object").slice(0,60).map(([k,v])=>[k,prop(v)]));
const temporal=(capturedAt=now())=>({capturedAt,assembledAt:now(),freshness:"current" as const});
const provenance=(nativeId:string,provider:string,authority:"source-authoritative"|"backend-derived"="source-authoritative")=>({source:"sap" as const,provider,nativeId,observedAt:now(),authority});
const entity=(id:string,kind:string,name:string,nativeId:string,input:Record<string,unknown>,provider:string):IntelligenceEntity=>({id,kind,displayName:name,identityQuality:"native",assertion:"fact",properties:properties(input),provenance:provenance(nativeId,provider),temporal:temporal()});
const relation=(id:string,kind:string,family:string,sourceEntityId:string,targetEntityId:string,provider:string):IntelligenceRelationship=>({id,kind,family,sourceEntityId,targetEntityId,assertion:"fact",evidenceIds:[],properties:{},provenance:provenance(id,provider,"backend-derived"),temporal:temporal()});
const record=(value:unknown):value is Record<string,unknown>=>Boolean(value)&&typeof value==="object"&&!Array.isArray(value);
const pick=(o:Record<string,unknown>,...keys:string[])=>{for(const k of keys){const v=o[k];if(typeof v==="string"&&v.trim())return v.trim();if(typeof v==="number")return String(v)}return undefined};
async function get(path:string,signal:AbortSignal){try{const response=await fetch(`${API}${path}`,{cache:"no-store",signal});const value=await response.json().catch(()=>null);return response.ok?{ok:true as const,value}:{ok:false as const,message:value?.message??value?.error??`${path} returned ${response.status}`}}catch(error){return{ok:false as const,message:error instanceof Error?error.message:`${path} failed`}}}
async function post(path:string,body:unknown,signal:AbortSignal){try{const response=await fetch(`${API}${path}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body),cache:"no-store",signal});const value=await response.json().catch(()=>null);return response.ok?{ok:true as const,value}:{ok:false as const,message:value?.message??`${path} returned ${response.status}`}}catch(error){return{ok:false as const,message:error instanceof Error?error.message:`${path} failed`}}}
function walkStructure(node:Record<string,unknown>,parent:string|undefined,entities:IntelligenceEntity[],relationships:IntelligenceRelationship[],seen:Set<string>,provider:string){const native=pick(node,"id","itemId","materialId","material","number")??crypto.randomUUID();const id=`sap:structure:${safe(native)}:${entities.length}`;if(!seen.has(id)){seen.add(id);entities.push(entity(id,parent?"part-occurrence":"material",pick(node,"name","description","materialDescription")??native,native,node,provider));if(parent)relationships.push(relation(`sap:contains:${safe(parent)}:${safe(id)}`,"contains","structure",parent,id,provider));}const children=Array.isArray(node.children)?node.children:[];for(const child of children)if(record(child))walkStructure(child,id,entities,relationships,seen,provider);return id;}
function classify(key:string,item:Record<string,unknown>){const k=key.toLowerCase();if(k.includes("production")||k.includes("order"))return{kind:"production-order",family:"operation"};if(k.includes("account"))return{kind:"accounting-document",family:"cost-and-inventory"};if(k.includes("storage"))return{kind:"storage-location",family:"cost-and-inventory"};if(k.includes("plant"))return{kind:"plant",family:"cost-and-inventory"};if(k.includes("movement")||k.includes("history"))return{kind:"document",family:"operation"};if(k.includes("valuation")||k.includes("stock")||k.includes("inventory")||k.includes("cost"))return{kind:"accounting-document",family:"cost-and-inventory"};return null}
function mapReport(value:unknown,subjectId:string,entities:IntelligenceEntity[],relationships:IntelligenceRelationship[],provider:string,path="report",depth=0){if(depth>6||!record(value))return;for(const [key,raw] of Object.entries(value)){const items=Array.isArray(raw)?raw:record(raw)?[raw]:[];const type=classify(key,record(raw)?raw:{});if(type&&items.length){for(const candidate of items.slice(0,250)){if(!record(candidate))continue;const native=pick(candidate,"materialDocument","documentNumber","orderNumber","productionOrder","plant","plantId","storageLocation","id","reference")??`${path}.${key}.${entities.length}`;const id=`sap:${type.kind}:${safe(native)}:${entities.length}`;entities.push(entity(id,type.kind,pick(candidate,"description","name","text","materialDescription")??`${key.replace(/([A-Z])/g," $1")} ${native}`,native,candidate,provider));relationships.push(relation(`sap:rel:${safe(subjectId)}:${safe(id)}`,type.family==="operation"?"operational-context":"business-impact",type.family,subjectId,id,provider));mapReport(candidate,id,entities,relationships,provider,`${path}.${key}`,depth+1)}}else if(record(raw))mapReport(raw,subjectId,entities,relationships,provider,`${path}.${key}`,depth+1)}}
export async function POST(request:NextRequest){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),120000);try{const body=await request.json() as {handoff?:LatticeHandoff};const handoff=body.handoff;const source=handoff?.sources?.find(item=>item.source==="sap");if(!handoff||!source)return NextResponse.json({message:"A selected SAP material is required."},{status:400});const materialId=source.nativeId??source.root.id;const attrs=(source.root.attributes??{}) as Record<string,unknown>;const plant=pick(attrs,"plant","Plant","WERKS")??"1001";const assembled=now();const subjectId=`sap:material:${safe(materialId)}`;const entities:IntelligenceEntity[]=[];const relationships:IntelligenceRelationship[]=[];const seen=new Set<string>();const rootId=walkStructure(source.root as unknown as Record<string,unknown>,undefined,entities,relationships,seen,"sap-bom-extractor");if(rootId!==subjectId){entities.unshift(entity(subjectId,"material",handoff.subjectLabel,materialId,{materialId,plant},"sap-engineering-discovery"));relationships.unshift(relation(`sap:represents:${safe(materialId)}`,"represented-by","structure",subjectId,rootId,"sap-lattice-intelligence"));}
const existingBusiness=source.jobId?get(`/api/pipeline/sap-impact/${encodeURIComponent(source.jobId)}`,controller.signal):Promise.resolve({ok:false as const,message:"No SAP pipeline job ID was supplied."});const existingOperational=source.jobId?get(`/api/pipeline/sap-operational-impact/${encodeURIComponent(source.jobId)}`,controller.signal):Promise.resolve({ok:false as const,message:"No SAP pipeline job ID was supplied."});const [capabilities,impact,business,operational]=await Promise.all([post("/api/sap-capabilities/probe",{materialId,plant},controller.signal),post("/api/sap-impact-validation/run",{materialId,plant},controller.signal),existingBusiness,existingOperational]);if(business.ok)mapReport((business.value as Record<string,unknown>).sapImpact,subjectId,entities,relationships,"sap-existing-business-impact","businessImpact");if(operational.ok)mapReport((operational.value as Record<string,unknown>).sapOperationalImpact,subjectId,entities,relationships,"sap-existing-operational-impact","operationalImpact");if(capabilities.ok)mapReport((capabilities.value as Record<string,unknown>).report,subjectId,entities,relationships,"sap-capability-probe");if(impact.ok)mapReport((impact.value as Record<string,unknown>).report,subjectId,entities,relationships,"sap-impact-execution", "impact");
const unique=new Map(entities.map(item=>[item.id,item]));const canonical=[...unique.values()];const warnings=[capabilities,impact].filter(x=>!x.ok).map(x=>x.ok?"":x.message);const evidence=[{id:`sap:evidence:bom:${safe(materialId)}`,kind:"source-extraction",summary:"SAP BOM structure supplied by the existing SAP/JCo extraction path.",source:"sap",provenance:provenance(materialId,"sap-bom-extractor"),temporal:temporal()}];if(capabilities.ok)evidence.push({id:`sap:evidence:capability:${safe(materialId)}`,kind:"capability-report",summary:"Connected SAP capability probe completed.",source:"sap",provenance:provenance(materialId,"sap-capability-probe"),temporal:temporal()});if(business.ok)evidence.push({id:`sap:evidence:business:${safe(materialId)}`,kind:"business-impact",summary:"Existing SAP business-impact result from the BOM extraction pipeline was reused.",source:"sap",provenance:provenance(materialId,"sap-existing-business-impact"),temporal:temporal()});if(operational.ok)evidence.push({id:`sap:evidence:operational:${safe(materialId)}`,kind:"operational-impact",summary:"Existing SAP operational-impact result from the BOM extraction pipeline was reused.",source:"sap",provenance:provenance(materialId,"sap-existing-operational-impact"),temporal:temporal()});if(impact.ok)evidence.push({id:`sap:evidence:impact:${safe(materialId)}`,kind:"execution-validation",summary:"SAP operational and business-impact validation completed.",source:"sap",provenance:provenance(materialId,"sap-impact-execution"),temporal:temporal()});const findings=warnings.length?[{id:`sap:finding:partial:${safe(materialId)}`,kind:"incomplete-extraction",title:"SAP intelligence is partially available",summary:warnings.join(" | "),subjectEntityIds:[subjectId],evidenceIds:[],provenance:provenance(materialId,"sap-lattice-intelligence","backend-derived"),temporal:temporal()}]:[];
const result:EngineeringIntelligenceInvestigationV1={contractVersion:"1.0",investigationId:`sap-${safe(handoff.handoffId)}`,subject:{id:subjectId,displayName:handoff.subjectLabel,preferredProductId:materialId,candidateIds:[materialId],confidence:"verified",reasons:["Selected SAP material","Existing SAP BOM, capability and operational-impact infrastructure reused"],provenance:provenance(materialId,"sap-engineering-discovery"),temporal:temporal()},entities:canonical,relationships:relationships.filter(r=>unique.has(r.sourceEntityId)||r.sourceEntityId===subjectId).filter(r=>unique.has(r.targetEntityId)||r.targetEntityId===subjectId),evidence,findings,sources:[{entityId:subjectId,source:"sap",status:warnings.length?"partial":"available",provenance:provenance(materialId,"sap-lattice-intelligence")}],identityClusters:[],temporal:{requestedAt:handoff.createdAt,capturedAt:source.capturedAt,assembledAt:assembled,freshness:"current"},summary:{entityCount:canonical.length,relationshipCount:relationships.length,evidenceCount:evidence.length,findingCount:findings.length,availableSourceCount:1,partialSourceCount:warnings.length?1:0,status:warnings.length?"partial-success":"success"}};return NextResponse.json(result)}catch(error){return NextResponse.json({message:error instanceof Error?error.message:"SAP intelligence failed."},{status:500})}finally{clearTimeout(timer)}}
