import { NextResponse } from "next/server";
import type { LatticeHandoff } from "@/features/lattice-next/contracts/handoff";
import type { EngineeringIntelligenceInvestigationV1,IntelligenceAuthority,IntelligenceEntity,IntelligenceProperty,IntelligenceRelationship } from "@/features/lattice-next/contracts/intelligence-v1";
const API=(process.env.ORCHESTRATION_API_URL||process.env.NEXT_PUBLIC_API_URL||"http://localhost:5212").replace(/\/$/,"");
type R=Record<string,unknown>;type Outcome={ok:boolean;value?:R;message?:string};
const rec=(v:unknown):v is R=>Boolean(v)&&typeof v==="object"&&!Array.isArray(v);const arr=(v:unknown):R[]=>Array.isArray(v)?v.filter(rec):[];const str=(v:unknown)=>typeof v==="string"?v.trim():v===null||v===undefined?"":String(v);const safe=(v:string)=>v.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"unknown";const now=()=>new Date().toISOString();
const read=(value:unknown,key:string):unknown=>{if(!rec(value))return undefined;const actual=Object.keys(value).find(candidate=>candidate.toLowerCase()===key.toLowerCase());return actual?value[actual]:undefined};
const recordAt=(value:unknown,key:string):R=>{const found=read(value,key);return rec(found)?found:{}};
const arrayAt=(value:unknown,key:string):R[]=>arr(read(value,key));
const get=async(path:string,signal:AbortSignal):Promise<Outcome>=>{try{const response=await fetch(`${API}${path}`,{cache:"no-store",signal});const value=await response.json().catch(()=>null);return response.ok&&rec(value)?{ok:true,value}:{ok:false,message:rec(value)?str(value.message)||str(value.error)||`${path} returned ${response.status}`:`${path} returned ${response.status}`}}catch(error){return{ok:false,message:error instanceof Error?error.message:`${path} failed`}}};
const post=async(path:string,body:unknown,signal:AbortSignal):Promise<Outcome>=>{try{const response=await fetch(`${API}${path}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body),cache:"no-store",signal});const value=await response.json().catch(()=>null);return response.ok&&rec(value)?{ok:true,value}:{ok:false,message:rec(value)?str(value.message)||str(value.error)||`${path} returned ${response.status}`:`${path} returned ${response.status}`}}catch(error){return{ok:false,message:error instanceof Error?error.message:`${path} failed`}}};
const prop=(value:unknown):IntelligenceProperty=>typeof value==="number"?{type:"number",number:value}:typeof value==="boolean"?{type:"boolean",boolean:value}:{type:"text",text:str(value)};
async function ensureJob(source:LatticeHandoff["sources"][number],materialId:string,plant:string,signal:AbortSignal){if(source.jobId)return source.jobId;const started=await post("/api/pipeline/start",{kind:"sap",materialId,materialQuery:source.label,plant,includeSapBusinessImpact:true},signal);if(!started.ok)throw new Error(started.message||"SAP pipeline could not start.");const id=str(started.value?.jobId);if(!id)throw new Error("SAP pipeline did not return a job ID.");for(let i=0;i<150;i++){await new Promise(resolve=>setTimeout(resolve,2000));const operational=await get(`/api/pipeline/sap-operational-impact/${encodeURIComponent(id)}`,signal);if(operational.ok)return id;const status=await get(`/api/pipeline/status/${encodeURIComponent(id)}`,signal);if(status.ok&&status.value?.terminal===true){if(str(status.value.status).startsWith("failed"))throw new Error(str(status.value.error)||"SAP extraction failed.");throw new Error("SAP completed without operational intelligence.")}}throw new Error("SAP pipeline did not complete within the investigation window.")}
export async function POST(request:Request){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),330000);try{const body=await request.json() as {handoff?:LatticeHandoff};const handoff=body.handoff;if(!handoff)throw new Error("SAP investigation handoff is required.");const source=handoff.sources.find(item=>item.source==="sap");if(!source)throw new Error("No SAP source is present in the investigation.");const materialId=source.nativeId||str(source.root.attributes?.["Item ID"])||source.root.id;const plant=str(source.root.attributes?.Plant)||"1001";const jobId=await ensureJob(source,materialId,plant,controller.signal);const [bom,business,operational]=await Promise.all([get(`/api/pipeline/bom/${encodeURIComponent(jobId)}`,controller.signal),get(`/api/pipeline/sap-impact/${encodeURIComponent(jobId)}`,controller.signal),get(`/api/pipeline/sap-operational-impact/${encodeURIComponent(jobId)}`,controller.signal)]);
const operationalEnvelope=recordAt(operational.value,"sapOperationalImpact");
const op=Object.keys(operationalEnvelope).length?operationalEnvelope:{};
const history=recordAt(op,"history");const historyMaterial=recordAt(history,"material");
const fallback=Object.keys(recordAt(op,"fallback")).length?recordAt(op,"fallback"):recordAt(history,"fallback");
const dataSource=str(read(op,"dataSource"))||str(read(history,"dataSource"))||"live";const isFallback=dataSource.toLowerCase()==="fallback-snapshot"||read(fallback,"active")===true;const captured=str(read(fallback,"snapshotCapturedAt"))||str(read(history,"extractedAt"))||source.capturedAt||now();const assembled=now();
const entities:IntelligenceEntity[]=[];const relationships:IntelligenceRelationship[]=[];const evidence:EngineeringIntelligenceInvestigationV1["evidence"]=[];const findings:EngineeringIntelligenceInvestigationV1["findings"]=[];const subjectId=`sap:material:${safe(materialId)}`;
const provenance=(nativeId:string,provider:string,authority:IntelligenceAuthority="source-authoritative")=>({source:"sap" as const,provider,nativeId,sourceExecutionId:jobId,observedAt:captured,authority});const temporal={capturedAt:captured,assembledAt:assembled,freshness:isFallback?"stale" as const:"current" as const};
const add=(kind:string,id:string,name:string,value:unknown,extra:R={},nativeId=id)=>{if(entities.some(entity=>entity.id===id))return id;const properties:Record<string,IntelligenceProperty>={...Object.fromEntries(Object.entries(extra).filter(([,v])=>v!==undefined&&v!==null&&v!=="").map(([k,v])=>[k,prop(v)])),recordKind:prop(kind),dataSource:prop(dataSource),fallbackActive:prop(isFallback),snapshotCapturedAt:prop(captured)};if(value!==undefined&&value!==null&&value!=="")properties.value=prop(value);entities.push({id,kind,displayName:name,identityQuality:"native",assertion:"fact",properties,provenance:provenance(nativeId,"sap-operational-intelligence"),temporal});return id};
const link=(kind:string,family:string,from:string,to:string)=>{const id=`sap:rel:${safe(kind)}:${safe(from)}:${safe(to)}`;if(from!==to&&!relationships.some(item=>item.id===id))relationships.push({id,kind,family,sourceEntityId:from,targetEntityId:to,assertion:"fact",confidence:"verified",evidenceIds:[],properties:{},provenance:provenance(`${from}:${to}`,"sap-operational-intelligence"),temporal})};
const addField=(parent:string,prefix:string,label:string,value:unknown,kind="sap-field")=>{if(value===undefined||value===null||value==="")return;const id=add(kind,`${prefix}:${safe(label)}`,label,value,{},`${parent}:${label}`);link("contains","structure",parent,id)};
if(bom.ok){const final=rec(bom.value?.finalBom)?bom.value!.finalBom as R:{};const root=rec(final.bomRoot)?final.bomRoot:rec(final.bomRootNode)?final.bomRootNode:null;const mapBom=(node:R,parent?:string,path="0")=>{const native=str(node.itemId)||str(node.id)||`${materialId}-${path}`;const id=path==="0"?subjectId:add("part-occurrence",`sap:occurrence:${safe(native)}:${safe(path)}`,str(node.name)||native,undefined,{materialId:native},native);if(parent&&id!==subjectId)link("contains","structure",parent,id);arr(node.children).forEach((child,index)=>mapBom(child,id,`${path}.${index}`))};if(root)mapBom(root)}
const businessImpact=recordAt(business.value,"sapImpact");const operationalImpact=recordAt(op,"currentState");
const businessMaterials=arrayAt(businessImpact,"materials");const operationalMaterials=arrayAt(operationalImpact,"materials");
const directImpact=Object.keys(recordAt(op,"stock")).length?op:{};
const materials=[...operationalMaterials,...businessMaterials,...(Object.keys(directImpact).length?[directImpact]:[])];
const material=materials.find(item=>[str(read(item,"materialId")),str(read(item,"internalMaterialId")),str(read(item,"requestedMaterialId"))].includes(materialId))||materials[0]||{};
const materialName=str(read(material,"description"))||str(read(historyMaterial,"description"))||handoff.subjectLabel;
add("material-master",subjectId,materialName,undefined,{materialId,jobId,dataSource,fallbackActive:isFallback},materialId);
addField(subjectId,"sap:product-detail:material-type","Material type",read(material,"materialType"),"product-detail");addField(subjectId,"sap:product-detail:base-unit","Base unit of measure",read(material,"baseUnit")||read(historyMaterial,"baseUnit"),"product-detail");
const stock=recordAt(material,"stock");const inventory=recordAt(material,"inventory");const historyCurrent=recordAt(history,"currentState");const storageLocations=arrayAt(history,"storageLocations");
const number=(value:unknown):number|undefined=>{if(typeof value==="number"&&Number.isFinite(value))return value;const text=str(value).replace(/,/g,"");if(!text)return undefined;const parsed=Number(text);return Number.isFinite(parsed)?parsed:undefined};
const firstNumber=(...values:unknown[])=>values.map(number).find(value=>value!==undefined);
const sumStorage=(key:string)=>{const values=storageLocations.map(item=>number(read(item,key))).filter((value):value is number=>value!==undefined);return values.length?values.reduce((sum,value)=>sum+value,0):undefined};
const unit=str(material.baseUnit)||str(historyMaterial.baseUnit)||"EA";const stockPlant=str((rec(material.organization)?material.organization:{}).plant)||str(historyMaterial.plant)||plant;const currency=str((rec(material.organization)?material.organization:{}).currency)||str(read(historyCurrent,"currency"));
const stockFields:[string,unknown,Record<string,unknown>?][]=[
 ["Physical stock",firstNumber(read(stock,"totalPhysical"),read(historyCurrent,"physicalStock"),sumStorage("LABST")),{unit,plant:stockPlant}],
 ["Unrestricted stock",firstNumber(read(stock,"unrestricted"),sumStorage("LABST")),{unit,plant:stockPlant}],
 ["Valuated quantity",firstNumber(read(inventory,"valuatedQuantity"),read(historyCurrent,"valuatedQuantity")),{unit,plant:stockPlant}],
 ["Inventory value",firstNumber(read(inventory,"totalStockValue"),read(historyCurrent,"inventoryValue")),{currency,plant:stockPlant}],
 ["Quality-inspection stock",firstNumber(read(stock,"qualityInspection"),sumStorage("INSME")),{unit,plant:stockPlant}],
 ["Restricted-use stock",firstNumber(read(stock,"restrictedUse"),sumStorage("EINME")),{unit,plant:stockPlant}],
 ["Blocked stock",firstNumber(read(stock,"blocked"),sumStorage("SPEME")),{unit,plant:stockPlant}],
 ["Stock in transfer",firstNumber(read(stock,"inTransfer"),sumStorage("UMLME")),{unit,plant:stockPlant}],
 ["Returns stock",firstNumber(read(stock,"returns"),sumStorage("RETME")),{unit,plant:stockPlant}],
 ["ATP availability",firstNumber(read(stock,"atpAvailable")),{unit,plant:stockPlant}]
];for(const [label,value,extra] of stockFields)if(value!==undefined)add("stock-metric",`sap:stock-metric:${safe(label)}`,label,value,extra??{},`${materialId}:${label}`);
const events=arrayAt(history,"events").length?arrayAt(history,"events"):arrayAt(history,"movements");const movementValues:number[]=[];const inventoryValues:number[]=[];for(const [index,event] of events.entries()){const document=str(event.materialDocument)||`${materialId}-${index}`;const movementType=str(event.movementType)||"Movement";const movementId=add("material-movement",`sap:movement:${safe(document)}:${safe(str(event.documentItem)||String(index))}`,`Movement ${movementType}`,undefined,{materialDocument:document,movementType,postingDate:event.postingDate,quantityDelta:event.quantityDelta,unit:event.unit,inventoryValueDelta:event.inventoryValueDelta,currency:event.currency},document);const movementLabel=movementType==="101"?"Goods receipt":movementType==="261"?"Production-order goods issue":movementType==="561"?"Initial stock entry":str(event.movementDescription)||str(event.sourceTransaction)||"Material movement";addField(movementId,`${movementId}:field:type`,"Type",movementLabel);addField(movementId,`${movementId}:field:document`,"Material document",document);addField(movementId,`${movementId}:field:posting-date`,"Posting date",event.postingDate);addField(movementId,`${movementId}:field:quantity-change`,"Quantity change",`${str(event.quantityDelta)} ${str(event.unit)}`.trim());addField(movementId,`${movementId}:field:value-change`,"Inventory-value change",`${str(event.inventoryValueDelta)} ${str(event.currency)}`.trim());addField(movementId,`${movementId}:field:purchase-order`,"Purchase order",event.purchaseOrder);addField(movementId,`${movementId}:field:production-order`,"Production order",event.productionOrder);if(typeof event.quantityDelta==="number")movementValues.push(event.quantityDelta);if(typeof event.inventoryValueDelta==="number")inventoryValues.push(event.inventoryValueDelta);
 const documents=arr(event.accountingDocuments).length?arr(event.accountingDocuments):(rec(event.accountingDocument)?[event.accountingDocument as R]:[]);for(const [docIndex,documentData] of documents.entries()){const number=str(documentData.accountingDocument)||str(documentData.documentNumber)||`${document}-${docIndex}`;const documentId=add("accounting-document",`sap:accounting:${safe(number)}:${safe(str(documentData.fiscalYear))}`,`Accounting document ${number}`,undefined,{accountingDocument:number,fiscalYear:documentData.fiscalYear,documentType:documentData.documentType,postingDate:documentData.postingDate,ledger:documentData.ledger,relatedMaterialMovement:document},number);link("referenced-in","accounting",movementId,documentId);addField(documentId,`${documentId}:field:fiscal-year`,"Fiscal year",documentData.fiscalYear);addField(documentId,`${documentId}:field:document-type`,"Document type",documentData.documentType);addField(documentId,`${documentId}:field:posting-date`,"Posting date",documentData.postingDate);addField(documentId,`${documentId}:field:ledger`,"Ledger",documentData.ledger);addField(documentId,`${documentId}:field:movement`,"Related material movement",document);
  for(const [lineIndex,line] of arr(documentData.lines).entries()){const lineNumber=str(line.line)||str(line.lineItem)||String(lineIndex+1);const lineId=add("accounting-line",`${documentId}:line:${safe(lineNumber)}`,`Accounting line ${lineNumber}`,undefined,{line:lineNumber,glAccount:line.glAccount,debitCredit:line.debitCredit||line.direction,amount:line.amount??line.signedAmount,currency:line.currency,quantity:line.quantity,unit:line.unit,productionOrder:line.productionOrder,profitCenter:line.profitCenter,businessArea:line.businessArea},`${number}:${lineNumber}`);link("contains","accounting",documentId,lineId);addField(lineId,`${lineId}:field:gl-account`,"G/L account",line.glAccount);addField(lineId,`${lineId}:field:debit-credit`,"Debit/credit indicator",line.debitCredit||line.direction);addField(lineId,`${lineId}:field:signed-amount`,"Signed amount",line.amount??line.signedAmount);addField(lineId,`${lineId}:field:currency`,"Currency",line.currency);addField(lineId,`${lineId}:field:quantity`,"Quantity",line.quantity);addField(lineId,`${lineId}:field:unit`,"Unit",line.unit);addField(lineId,`${lineId}:field:production-order`,"Production-order reference",line.productionOrder);addField(lineId,`${lineId}:field:profit-center`,"Profit center",line.profitCenter);addField(lineId,`${lineId}:field:business-area`,"Business area",line.businessArea)}
 }}
const summary=recordAt(history,"historySummary");const movementCount=read(summary,"movementCount")??events.length;const accountingLineCount=read(summary,"accountingLineCount")??events.reduce((total,event)=>total+(arr(event.accountingDocuments).length?arr(event.accountingDocuments):rec(event.accountingDocument)?[event.accountingDocument as R]:[]).reduce((sum,doc)=>sum+arr(doc.lines).length,0),0);const quantityExpression=movementValues.length?`${movementValues.map(value=>value>0?`+${value}`:String(value)).join(" ")} = ${str(read(summary,"netQuantityDelta")||movementValues.reduce((a,b)=>a+b,0))}`:"";const valueExpression=inventoryValues.length?`${inventoryValues.map(value=>value>0?`+${value}`:String(value)).join(" ")} = ${str(read(summary,"netInventoryValueDelta")||inventoryValues.reduce((a,b)=>a+b,0))}`:"";const historyFields:[string,unknown][]=[["Movement count",movementCount],["Accounting-line count",accountingLineCount],["Net quantity delta",read(summary,"netQuantityDelta")],["Net inventory-value delta",read(summary,"netInventoryValueDelta")],["Quantity reconciliation",read(summary,"quantityReconciledToCurrentValuation")===true?"Yes":read(summary,"quantityReconciledToCurrentValuation")===false?"No":undefined],["Value reconciliation",read(summary,"valueReconciledToCurrentInventory")===true?"Yes":read(summary,"valueReconciledToCurrentInventory")===false?"No":undefined],["Historical reconstruction method",read(summary,"historicalBeforeAfterMethod")],["Quantity reconstruction",quantityExpression],["Value reconstruction",valueExpression]];for(const [label,value] of historyFields)if(value!==undefined&&value!==null&&value!=="")add("history-metric",`sap:history:${safe(label)}`,label,value,{derived:["Quantity reconstruction","Value reconstruction"].includes(label)},`${materialId}:${label}`);
if(isFallback){const eid=`sap:evidence:fallback:${safe(materialId)}`;evidence.push({id:eid,kind:"sap-fallback-snapshot",summary:`Validated SAP snapshot captured ${captured}. Values are not live.`,source:"sap",provenance:provenance(materialId,"sap-fallback","backend-derived"),temporal})}
const status=isFallback||!bom.ok?"partial":"available";const result:EngineeringIntelligenceInvestigationV1={contractVersion:"1.0",investigationId:`sap-${safe(handoff.handoffId)}`,subject:{id:subjectId,displayName:handoff.subjectLabel,preferredProductId:materialId,candidateIds:[materialId],confidence:"verified",reasons:["Selected SAP material","Existing SAP extraction and fallback infrastructure reused"],provenance:provenance(materialId,"sap-engineering-intelligence"),temporal},entities:entities.filter(entity=>entity.id!==subjectId),relationships,evidence,findings,sources:[{entityId:subjectId,source:"sap",status,provenance:provenance(materialId,"sap-engineering-intelligence")}],identityClusters:[],temporal:{requestedAt:handoff.createdAt,capturedAt:captured,assembledAt:assembled,freshness:isFallback?"stale":"current"},summary:{entityCount:entities.length-1,relationshipCount:relationships.length,evidenceCount:evidence.length,findingCount:findings.length,availableSourceCount:status==="available"?1:0,partialSourceCount:status==="partial"?1:0,status:status==="available"?"success":"partial-success"}};return NextResponse.json(result)}catch(error){return NextResponse.json({message:error instanceof Error?error.message:"SAP intelligence failed."},{status:500})}finally{clearTimeout(timer)}}
