using System.Security.Cryptography;using System.Text.Json;using Orchestration.API.Engineering.Contracts;using Orchestration.API.Models;
namespace Orchestration.API.Engineering.Adapters;
internal static class EngineeringAdapterSupport
{
 internal static string CreateRuntimeDirectory(string jobId,EngineeringSource source){var root=Path.GetFullPath(Path.Combine(AppContext.BaseDirectory,"runtime","engineering-jobs",Safe(jobId),source.ToString().ToLowerInvariant()));Directory.CreateDirectory(root);return root;}
 internal static string CaptureCanonical(string jobId,EngineeringSource source,string sourcePath,string fileName){if(!File.Exists(sourcePath))throw new FileNotFoundException("Canonical artifact source is missing.");var target=Path.Combine(CreateRuntimeDirectory(jobId,source),Path.GetFileName(fileName));if(!string.Equals(Path.GetFullPath(sourcePath),Path.GetFullPath(target),StringComparison.OrdinalIgnoreCase))File.Copy(sourcePath,target,true);return target;}
 internal static SourceArtifactReference Artifact(string jobId,EngineeringSource source,string type,string path,ArtifactSensitivity sensitivity=ArtifactSensitivity.Sensitive){var canonical=CaptureCanonical(jobId,source,path,Path.GetFileName(path));var checksum=Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(canonical))).ToLowerInvariant();return new($"artifact-{Guid.NewGuid():N}",source,type,DateTimeOffset.UtcNow,EvidenceAvailability.Available,checksum,$"engineering-jobs/{Safe(jobId)}/{source.ToString().ToLowerInvariant()}/{Path.GetFileName(canonical)}",sensitivity,"delete-after-24-hours");}
 internal static (BomRoot root,CanonicalStructureNode structure) ParseNormalizedStructure(string path,string fallbackId){using var d=JsonDocument.Parse(File.ReadAllText(path));var root=d.RootElement;if(!root.TryGetProperty("bom",out var bom)||bom.ValueKind!=JsonValueKind.Array||bom.GetArrayLength()==0)throw new InvalidDataException("The extractor output did not contain a normalized BOM root.");var canonical=Canonical(bom[0],null);var legacy=Legacy(canonical);return(new(){SourceItemId=Text(root,"productId")??fallbackId,SourceRevId=Text(root,"version")??"",ExtractedAt=Text(root,"generatedDate")??DateTimeOffset.UtcNow.ToString("O"),BomRootNode=legacy},canonical);}
 internal static BomRoot ParseNormalizedBom(string path,string fallbackId)=>ParseNormalizedStructure(path,fallbackId).root;
 static CanonicalStructureNode Canonical(JsonElement value,string? parent){var a=value.TryGetProperty("attributes",out var x)&&x.ValueKind==JsonValueKind.Object?x:default;var occurrence=Text(a,"Occurrence ID")??Text(value,"id")??Guid.NewGuid().ToString("N");var children=new List<CanonicalStructureNode>();if(value.TryGetProperty("children",out var rows)&&rows.ValueKind==JsonValueKind.Array)foreach(var row in rows.EnumerateArray())children.Add(Canonical(row,occurrence));var metadata=new Dictionary<string,string?>();if(a.ValueKind==JsonValueKind.Object)foreach(var item in a.EnumerateObject())metadata[item.Name]=item.Value.ValueKind==JsonValueKind.String?item.Value.GetString():item.Value.ToString();var part=Text(a,"Item ID")??Text(value,"name")??"unknown";return new(Text(value,"id")??occurrence,Text(a,"Part ID")??part,part,Text(value,"name")??part,occurrence,Text(a,"Part Use ID"),parent,Text(a,"Tree Path")??occurrence,Text(a,"Revision"),Text(a,"Version"),Text(value,"quantity")??Text(a,"Quantity"),Text(a,"Sequence"),Text(a,"Lifecycle State"),metadata,children);}
 static BomNode Legacy(CanonicalStructureNode n)=>new(){ItemId=n.ItemOrPartNumber,Name=n.DisplayName,Qty=n.Quantity??"",RevId=n.Revision??"",Sequence=n.Sequence??"",VariantCondition="",VariantState="",Children=n.Children.Select(Legacy).ToList()};
 internal static string? Text(JsonElement v,string p)=>v.ValueKind==JsonValueKind.Object&&v.TryGetProperty(p,out var i)&&i.ValueKind is not JsonValueKind.Null and not JsonValueKind.Undefined?(i.ValueKind==JsonValueKind.String?i.GetString():i.ToString()):null;
 static string Safe(string value)=>string.Concat(value.Select(c=>char.IsLetterOrDigit(c)||c is '-' or '_'?c:'_'));
}
