"use client";
import { memo, useEffect, useState } from "react";
import { EdgeLabelRenderer,getBezierPath,getSmoothStepPath,getStraightPath,useStore,type EdgeProps,type Position } from "@xyflow/react";
import { AnimatePresence,motion,useReducedMotion } from "motion/react";
import type { LatticeEdgeCategory,LatticeFlowEdge } from "../canvas/lattice-flow-types";
import { latticeMotion } from "../motion/lattice-motion";
const palette:Record<LatticeEdgeCategory,string>={structure:"#94a3b8",correspondence:"#38bdf8",requirement:"#22d3ee","change-impact":"#f59e0b","operational-impact":"#34d399",configuration:"#e879f9",evidence:"#94a3b8",pending:"#64748b",unavailable:"#fb7185"};
type RouteArguments={sourceX:number;sourceY:number;targetX:number;targetY:number;sourcePosition:Position;targetPosition:Position};
function route(args:RouteArguments,category:LatticeEdgeCategory){
 const distance=Math.hypot(args.targetX-args.sourceX,args.targetY-args.sourceY);
 const aligned=Math.abs(args.targetX-args.sourceX)<28||Math.abs(args.targetY-args.sourceY)<28;
 if(aligned&&distance<260)return getStraightPath(args);
 return getBezierPath({...args,curvature:distance>700?0.18:distance>350?0.24:0.32});
}
function EdgeView({id,sourceX,sourceY,targetX,targetY,sourcePosition,targetPosition,selected,data}:EdgeProps<LatticeFlowEdge>){const zoom=useStore(state=>state.transform[2]);const reduced=useReducedMotion();const[moving,setMoving]=useState(false);useEffect(()=>{const handler=(event:Event)=>setMoving(Boolean((event as CustomEvent).detail?.active));window.addEventListener("lattice:geometry-motion",handler);return()=>window.removeEventListener("lattice:geometry-motion",handler)},[]);const edgeData=data??{category:"evidence",relationshipKind:"represented-by",direction:"forward",importance:"normal",animation:"settled",authoritative:true};const [path,labelX,labelY]=route({sourceX,sourceY,targetX,targetY,sourcePosition,targetPosition},edgeData.category);const color=palette[edgeData.category];const markerId=`lattice-marker-${id.replace(/[^a-zA-Z0-9_-]/g,"-")}`;const label=String(edgeData.fullLabel??edgeData.label??"").trim();const showLabel=Boolean(label)&&!moving&&(selected||zoom>=(edgeData.importance==="primary"?0.42:0.58));return <><defs><marker id={markerId} markerWidth="8" markerHeight="8" refX="7.2" refY="4" orient="auto-start-reverse" markerUnits="userSpaceOnUse"><motion.path d={edgeData.direction==="inferred"?"M 1 1 L 7 4 L 1 7":"M 1 1 L 7 4 L 1 7 Z"} fill={edgeData.direction==="inferred"?"none":color} stroke={color} strokeWidth="1" initial={{opacity:reduced?1:0}} animate={{opacity:1}} transition={{delay:reduced?0:0.2,duration:0.08}}/></marker></defs><motion.path d={path} fill="none" stroke={color} strokeWidth={selected?1.8:edgeData.importance==="primary"?1.5:1.25} strokeDasharray={edgeData.category==="evidence"?"2 5":edgeData.category==="pending"?"8 8":undefined} markerStart={edgeData.direction==="bidirectional"?`url(#${markerId})`:undefined} markerEnd={`url(#${markerId})`} className={`react-flow__edge-path lattice-intelligent-edge edge-${edgeData.category}`} initial={reduced?{opacity:1,pathLength:1}:{opacity:0.35,pathLength:0}} animate={{opacity:edgeData.importance==="low"?0.56:1,pathLength:1}} transition={reduced?{duration:0}:latticeMotion.edge}/><AnimatePresence>{showLabel?<EdgeLabelRenderer><motion.button initial={{opacity:0,scale:0.98,y:2}} animate={{opacity:1,scale:1,y:0}} exit={{opacity:0,scale:0.98,y:2}} transition={latticeMotion.label} type="button" data-edge-action="open-details" data-edge-id={id} className={`lattice-edge-label nodrag nopan ${selected?"is-selected":""}`} style={{transform:`translate(-50%,-50%) translate(${labelX}px,${labelY}px)`}}>{label}</motion.button></EdgeLabelRenderer>:null}</AnimatePresence></>}
export const IntelligentRelationshipEdge=memo(EdgeView);
