"use client";
import { memo, useEffect, type ComponentType, type ReactNode } from "react";
import { Handle, NodeToolbar, Position, useStore, useUpdateNodeInternals, type NodeProps } from "@xyflow/react";
import { LayoutGroup, motion, useMotionValue, useReducedMotion, useTransform } from "motion/react";
import { IconAlertTriangle, IconAtom, IconBox, IconChevronRight, IconClipboardCheck, IconFlask, IconFocus2, IconGitCompare, IconHierarchy3, IconInfoCircle, IconPinnedOff, IconRulerMeasure, IconScale, IconVersions, IconX } from "@tabler/icons-react";
import type { LatticeFlowNode, RelationshipFamily } from "../canvas/lattice-flow-types";
import type { LatticeNodeAction } from "../canvas/lattice-node-actions";
import { directionVector, nodeVariants, valueVariants } from "../motion/lattice-motion";
const tones: Record<string,string> = { teamcenter:"cyan", windchill:"violet", sap:"emerald", configit:"fuchsia", unified:"slate" };
export type NodeZoomTier="far"|"working"|"close";
export const nodeZoomTier=(zoom:number):NodeZoomTier=>zoom<0.58?"far":zoom<1.08?"working":"close";
const actions:{action:LatticeNodeAction;label:string;icon:ComponentType<{className?:string}>}[]=[{action:"focus",label:"Focus branch",icon:IconFocus2},{action:"expand-one",label:"Expand one level",icon:IconChevronRight},{action:"collapse-descendants",label:"Collapse branch",icon:IconX},{action:"open-details",label:"Open details",icon:IconInfoCircle},{action:"reset-position",label:"Reset position",icon:IconPinnedOff}];
function Toolbar({id,data}:{id:string;data:LatticeFlowNode["data"]}){return <NodeToolbar isVisible={data.selected} position={Position.Top} offset={10}><motion.div initial={{opacity:0,y:4}} animate={{opacity:1,y:0}} exit={{opacity:0,y:4}} className="lattice-node-toolbar nodrag nopan nowheel" role="toolbar" aria-label={`Actions for ${data.label}`}>{actions.filter(item=>data.hasChildren||!["expand-one","collapse-descendants"].includes(item.action)).map(({action,label,icon:Icon})=><motion.button whileHover={{y:-1}} whileTap={{scale:0.96}} whileFocus={{outline:"2px solid #94a3b8"}} key={action} type="button" data-node-action={action} data-node-id={id} title={label} aria-label={label}><Icon className="h-3.5 w-3.5"/></motion.button>)}</motion.div></NodeToolbar>}
const handlePosition={NORTH:Position.Top,EAST:Position.Right,SOUTH:Position.Bottom,WEST:Position.Left} as const;
function Handles({data}:{data:LatticeFlowNode["data"]}){
 const configured=(data.relationshipFamilies?.length?data.relationshipFamilies:["structure"]) as RelationshipFamily[];
 const families=[...new Set<RelationshipFamily>(["structure",...configured])];
 const sides=[
  {name:"north",position:Position.Top},{name:"east",position:Position.Right},
  {name:"south",position:Position.Bottom},{name:"west",position:Position.Left},
 ] as const;
 return <>{families.flatMap(family=>sides.flatMap(side=>[
  <Handle key={`target:${side.name}:${family}`} id={`target:${side.name}:${family}`} type="target" position={side.position} className={`lattice-handle family-${family}`}/>,
  <Handle key={`source:${side.name}:${family}`} id={`source:${side.name}:${family}`} type="source" position={side.position} className={`lattice-handle family-${family}`}/>,
 ]))}</>;
}
function Chrome({id,data,children}:{id:string;data:LatticeFlowNode["data"];children:ReactNode}){const update=useUpdateNodeInternals();useEffect(()=>{let second=0;const first=requestAnimationFrame(()=>{update(id);second=requestAnimationFrame(()=>update(id))});return()=>{cancelAnimationFrame(first);if(second)cancelAnimationFrame(second)}},[id,data.geometryRevision,data.expanded,update]);return <><Toolbar id={id} data={data}/><Handles data={data}/>{children}</>}
const icons:Record<string,ComponentType<{className?:string}>>={material:IconAtom,chemical:IconFlask,weight:IconScale,dimension:IconRulerMeasure,version:IconVersions,state:IconInfoCircle,view:IconHierarchy3,source:IconBox};
function Shell({id,data,children,className=""}:{id:string;data:LatticeFlowNode["data"];children:ReactNode;className?:string}){const reduced=useReducedMotion();const direction=directionVector(data.layoutDirection);return <motion.article custom={direction} variants={nodeVariants} initial={reduced?{opacity:0}:{opacity:0,x:direction.x*12,y:direction.y*12}} animate={{opacity:1,x:0,y:0}} exit={{opacity:0,x:direction.x*8,y:direction.y*8}} onAnimationStart={()=>window.dispatchEvent(new CustomEvent("lattice:geometry-motion",{detail:{active:true,id}}))} onAnimationComplete={()=>window.dispatchEvent(new CustomEvent("lattice:geometry-motion",{detail:{active:false,id}}))} onLayoutAnimationStart={()=>window.dispatchEvent(new CustomEvent("lattice:geometry-motion",{detail:{active:true,id}}))} onLayoutAnimationComplete={()=>window.dispatchEvent(new CustomEvent("lattice:geometry-motion",{detail:{active:false,id}}))} whileHover={reduced?undefined:{y:-1} as never} className={`lattice-premium-node ${className} ${data.selected?"is-selected":""} ${data.dimmed?"is-dimmed":""}`} style={{"--accent-strength":data.selected?1:0.62,"--border-opacity":data.selected?0.9:0.46} as never}><Chrome id={id} data={data}>{children}</Chrome></motion.article>}
function Subject({id,data}:NodeProps<LatticeFlowNode>){return <Shell id={id} data={data} className="lattice-subject-node"><div className="source-icon"><IconHierarchy3/></div><h2>{data.label}</h2></Shell>}
const domainIcons:Record<string,ComponentType<{className?:string}>>={"physical-attributes":IconAtom,"product-context":IconInfoCircle,requirements:IconClipboardCheck,changes:IconGitCompare};
function Domain({id,data}:NodeProps<LatticeFlowNode>){const domain=id.replace("projection:domain:","");const Icon=domainIcons[domain]??IconHierarchy3;return <Shell id={id} data={data} className={`lattice-domain-node domain-${domain}`}><div className="source-icon"><Icon/></div><h3>{data.label}</h3>{data.hasChildren?<motion.button whileHover={{y:-1}} whileTap={{scale:0.96}} whileFocus={{outline:"2px solid #94a3b8"}} type="button" data-expand-node={id} className="lattice-disclosure nodrag nopan nowheel" aria-expanded={data.expanded}>{data.expanded?"Collapse":"Explore"}</motion.button>:null}</Shell>}
function Entity({id,data}:NodeProps<LatticeFlowNode>){if(id.startsWith("projection:domain:"))return <Domain id={id} data={data}/>;const zoom=useStore(state=>state.transform[2]);const tier=nodeZoomTier(zoom);const zoomValue=useMotionValue(zoom);useEffect(()=>zoomValue.set(zoom),[zoom,zoomValue]);const valueOpacity=useTransform(zoomValue,[0.5,0.66],[0,1]);const kind=String(data.entityKind??data.category);const key=String(data.attributes?.attributeKey??data.label).toLowerCase();const Icon=icons[key]??(kind==="requirement"?IconClipboardCheck:kind==="change-notice"?IconAlertTriangle:kind==="change-task"?IconGitCompare:IconBox);const value=typeof data.attributes?.value==="string"&&data.attributes.value.trim()?data.attributes.value:"Unavailable";const requirementId=typeof data.attributes?.requirementId==="string"?data.attributes.requirementId:(kind==="requirement"&&data.nativeIdentifier?data.nativeIdentifier:undefined);const title=requirementId&&data.label.startsWith(requirementId)?data.label.slice(requirementId.length).replace(/^\s*[-–—:]\s*/,""):data.label;return <Shell id={id} data={data} className={`lattice-entity-node tone-${tones[data.source]??"slate"}`}><LayoutGroup id={`node-${id}`}><div className="source-icon"><Icon/></div><div className="node-copy">{requirementId?<><span className="node-identifier">{requirementId}</span><h3>{title||data.label}</h3></>:<><span className="node-field">{data.label}</span>{kind!=="physical-attribute"&&kind!=="product-context"&&!data.attributes?.value?<h3>{data.label}</h3>:null}</>}{(kind==="physical-attribute"||kind==="product-context"||data.attributes?.value)?<motion.p variants={valueVariants} initial="hidden" animate="visible" style={{opacity:tier==="far"?0:valueOpacity}} className={`node-value ${value==="Unavailable"?"is-unavailable":""}`}>{value}</motion.p>:null}</div></LayoutGroup>{data.hasChildren?<motion.button whileTap={{scale:0.96}} type="button" data-expand-node={id} className="lattice-disclosure nodrag nopan nowheel" aria-expanded={data.expanded}>{data.expanded?"Collapse":"Explore"}</motion.button>:null}</Shell>}
export const InvestigationSubjectNode=memo(Subject);export const SourceRepresentationNodeView=memo(Entity);export const PremiumEngineeringNode=memo(Entity);
