"use client";
import { memo, useEffect, type ComponentType, type ReactNode } from "react";
import { Handle, NodeResizeControl, NodeToolbar, Position, useStore, useUpdateNodeInternals, type NodeProps } from "@xyflow/react";
import { IconArrowsSplit, IconBox, IconChevronRight, IconFocus2, IconHierarchy3, IconInfoCircle, IconPinned, IconPinnedOff, IconRoute, IconStack2, IconX } from "@tabler/icons-react";
import type { LatticeFlowNode, RelationshipFamily } from "../canvas/lattice-flow-types";
import type { LatticeNodeAction } from "../canvas/lattice-node-actions";
const tones:Record<string,string>={teamcenter:"cyan",windchill:"violet",sap:"emerald",configit:"fuchsia",unified:"slate"};
export type NodeZoomTier="far"|"working"|"close";
export const nodeZoomTier=(zoom:number):NodeZoomTier=>zoom<.58?"far":zoom<1.08?"working":"close";
const actions:{action:LatticeNodeAction;label:string;icon:ComponentType<{className?:string}>}[]=[{action:"focus",label:"Focus branch",icon:IconFocus2},{action:"expand-one",label:"Expand one level",icon:IconChevronRight},{action:"collapse-descendants",label:"Collapse branch",icon:IconX},{action:"open-details",label:"Open details",icon:IconInfoCircle},{action:"reset-position",label:"Reset position",icon:IconPinnedOff}];
function Toolbar({id,data}:{id:string;data:LatticeFlowNode["data"]}){const relevant=actions.filter(item=>data.hasChildren||!["expand-one","expand-branch","collapse-descendants"].includes(item.action));return <NodeToolbar isVisible={data.selected} position={Position.Top} offset={12}><div className="lattice-node-toolbar nodrag nopan nowheel" role="toolbar" aria-label={`Actions for ${data.label}`}>{relevant.map(({action,label,icon:Icon})=><button key={action} type="button" data-node-action={action} data-node-id={id} title={label} aria-label={label} className="nodrag nopan nowheel"><Icon className="h-3.5 w-3.5"/></button>)}</div></NodeToolbar>}
const handlePosition={NORTH:Position.Top,EAST:Position.Right,SOUTH:Position.Bottom,WEST:Position.Left} as const;
function DynamicHandles({id,data}:{id:string;data:LatticeFlowNode["data"]}){
  const update=useUpdateNodeInternals();
  const families=data.relationshipFamilies.length?data.relationshipFamilies:["structure" as RelationshipFamily];
  const radial=data.radialHandles??[];
  const radialKey=radial.map(handle=>`${handle.id}:${handle.side}:${handle.offsetPercent??50}`).sort().join("|");
  const familyKey=families.join("|");
  const direction=data.layoutDirection??data.orientation;
  useEffect(()=>{update(id)},[id,update,direction,familyKey,radialKey]);
  const input=direction==="RIGHT"?Position.Left:direction==="LEFT"?Position.Right:direction==="DOWN"?Position.Top:Position.Bottom;
  const output=direction==="RIGHT"?Position.Right:direction==="LEFT"?Position.Left:direction==="DOWN"?Position.Bottom:Position.Top;
  const horizontal=direction==="RIGHT"||direction==="LEFT";
  return <>
    {families.map((family,index)=>{const offset=`${((index+1)/(families.length+1))*100}%`;return <span key={family}><Handle id={`in:${family}`} type="target" position={input} style={horizontal?{top:offset}:{left:offset}} className={`lattice-handle family-${family}`}/><Handle id={`out:${family}`} type="source" position={output} style={horizontal?{top:offset}:{left:offset}} className={`lattice-handle family-${family}`}/></span>})}
    {radial.map(handle=>{const position=handlePosition[handle.side];const offset=`${handle.offsetPercent??50}%`;const style=position===Position.Top||position===Position.Bottom?{left:offset}:{top:offset};const type=handle.id.startsWith("radial-source:")?"source":"target";return <Handle key={handle.id} id={handle.id} type={type} position={position} style={style} className="lattice-handle lattice-radial-handle"/>})}
  </>;
}
function Ring({value}:{value:number}){const safe=Math.max(0,Math.min(100,Math.round(value)));return <span className="lattice-completeness" style={{background:`conic-gradient(#22d3ee ${safe*3.6}deg,#1e293b 0)`}} aria-label={`${safe}% complete`}><span>{safe}</span></span>}
function Chrome({id,data,children,resizable=false}:{id:string;data:LatticeFlowNode["data"];children:ReactNode;resizable?:boolean}){return <>{resizable?<NodeResizeControl minWidth={272} minHeight={100} maxWidth={560} maxHeight={420} position="bottom-right" className="lattice-resize nodrag nopan"/>:null}<Toolbar id={id} data={data}/><DynamicHandles id={id} data={data}/>{children}</>}
function Subject({id,data}:NodeProps<LatticeFlowNode>){const tier=useStore(state=>nodeZoomTier(state.transform[2]));return <article className={`lattice-premium-node lattice-subject-node tone-slate ${data.selected?"is-selected":""} ${data.activeResolution?"is-resolving":""} ${data.dimmed?"is-dimmed":""}`} data-zoom-tier={tier} data-dimmed={data.dimmed} aria-label={`Investigation subject ${data.label}, ${data.resolutionState}`}><Chrome id={id} data={data}><div className="subject-mark"><IconHierarchy3/></div><div className="node-copy"><p className="node-eyebrow">Investigation subject</p><h3>{data.label}</h3><p className="node-identifier">{data.nativeIdentifier||data.subtitle}</p>{tier!=="far"?<div className="node-metrics"><span>{data.coverageSummary}</span><span>{data.participatingSystems} systems</span><span>{data.resolutionState}</span></div>:null}{tier==="close"?<p className="node-evidence">{data.evidenceSummary}</p>:null}</div><Ring value={data.completeness}/>{data.hasChildren?<button type="button" data-expand-node={id} className="lattice-disclosure nodrag nopan" aria-label={data.expanded?"Collapse branch":`Expand ${data.hiddenChildren} hidden descendants`}>{data.expanded?"Expanded":`+ ${data.hiddenChildren}`}</button>:null}</Chrome></article>}
function Source({id,data}:NodeProps<LatticeFlowNode>){const tier=useStore(state=>nodeZoomTier(state.transform[2]));const tone=data.resolutionState==="failed"?"rose":data.resolutionState==="warning"||data.resolutionState==="partial"?"amber":tones[data.source]??"slate";return <article className={`lattice-premium-node lattice-source-node tone-${tone} ${data.selected?"is-selected":""} ${data.dimmed?"is-dimmed":""}`} data-zoom-tier={tier} data-dimmed={data.dimmed} aria-label={`${data.source} representation ${data.label}`}><Chrome id={id} data={data}><div className="source-rail"/><div className="source-icon"><IconStack2/></div><div className="node-copy"><div className="node-heading"><span>{data.source}</span>{tier!=="far"&&data.resolutionState!=="ready"?<span>{data.resolutionState}</span>:null}</div><h3 title={data.label}>{data.label}</h3>{tier!=="far"?<p className="node-identifier">{data.nativeIdentifier||"Identifier unavailable"}{data.revision?` · Rev ${data.revision}`:""}</p>:null}{tier==="close"&&data.hasChildren?<p className="node-related">{data.childCount} direct {data.childCount===1?"child":"children"}</p>:null}</div>{data.hasChildren?<button type="button" data-expand-node={id} className="lattice-disclosure nodrag nopan nowheel" aria-expanded={data.expanded} aria-label={data.expanded?"Collapse branch":`Expand ${data.hiddenChildren} direct children`}>{data.expanded?"Collapse":`Expand ${data.hiddenChildren}`}</button>:null}</Chrome></article>}
function Entity({id,data}:NodeProps<LatticeFlowNode>){const tier=useStore(state=>nodeZoomTier(state.transform[2]));const Icon=data.entityKind==="assembly"?IconStack2:IconBox;return <article className={`lattice-premium-node lattice-entity-node tone-${tones[data.source]??"slate"} ${data.selected?"is-selected":""} ${data.dimmed?"is-dimmed":""}`} data-zoom-tier={tier} data-dimmed={data.dimmed} aria-label={`${data.entityKind??data.category} ${data.label}`}><Chrome id={id} data={data}><div className="source-icon"><Icon/></div><div className="node-copy"><div className="node-heading"><span>{data.source}</span>{tier!=="far"?<span>{data.entityKind??data.category}</span>:null}</div><h3 title={data.label}>{data.label}</h3>{tier!=="far"?<p className="node-identifier">{data.nativeIdentifier||data.subtitle}</p>:null}{tier==="close"&&data.hasChildren?<p className="node-related">{data.childCount} direct {data.childCount===1?"child":"children"}</p>:null}</div>{data.hasChildren?<button type="button" data-expand-node={id} className="lattice-disclosure nodrag nopan nowheel" aria-expanded={data.expanded} aria-label={data.expanded?"Collapse branch":`Expand ${data.hiddenChildren} direct children`}>{data.expanded?"Collapse":`Expand ${data.hiddenChildren}`}</button>:null}</Chrome></article>}
export const InvestigationSubjectNode=memo(Subject);export const SourceRepresentationNodeView=memo(Source);export const PremiumEngineeringNode=memo(Entity);
