export type ScenarioId="empty"|"resolved"|"product"|"plm"|"sap"|"configit"|"requirement"|"cluster"|"path"|"restored";
export type LayoutPreset="pillar"|"horizontal"|"vertical"|"focused-path"|"evidence-branches"|"incremental";
export interface DemoNode{id:string;label:string;kind:string;zone:string;width:number;height:number;clusterCount?:number;}
export interface DemoEdge{id:string;source:string;target:string;family:string;label:string;priority:"always"|"active"|"hover"|"zoom"|"inspector";}
const base:DemoNode[]=[{id:"focus",label:"Search / Active Investigation",kind:"focus",zone:"center",width:240,height:66},{id:"pillar:tc",label:"Teamcenter",kind:"pillar",zone:"tc",width:190,height:58},{id:"pillar:wc",label:"Windchill",kind:"pillar",zone:"wc",width:190,height:58},{id:"pillar:sap",label:"SAP",kind:"pillar",zone:"sap",width:190,height:58},{id:"pillar:cfg",label:"Configit",kind:"pillar",zone:"cfg",width:190,height:58}];
const resolved:DemoNode[]=[...base,{id:"product",label:"Screwjack_002403",kind:"product",zone:"center",width:190,height:54},{id:"tc-product",label:"Teamcenter 002403/A",kind:"source-record",zone:"tc",width:180,height:48},{id:"wc-product",label:"Windchill 002403 A.2",kind:"source-record",zone:"wc",width:180,height:48},{id:"sap-product",label:"SAP Material 002403",kind:"material",zone:"sap",width:180,height:48},{id:"cfg-product",label:"Screwjack configuration",kind:"configuration",zone:"cfg",width:180,height:48}];
const product:DemoNode[]=[...resolved,{id:"body",label:"Body_002409",kind:"assembly",zone:"tc",width:160,height:46},{id:"head",label:"Top Head_002412",kind:"assembly",zone:"tc",width:170,height:46},{id:"washer",label:"Washer_002405",kind:"part",zone:"tc",width:160,height:46},{id:"occ",label:"Spindle occurrence",kind:"occurrence",zone:"tc",width:168,height:46},{id:"spindle",label:"Screw Spindle_002410",kind:"part",zone:"tc",width:185,height:48}];
const plm:DemoNode[]=[...product,{id:"tc-spindle",label:"Teamcenter 002410/B",kind:"source-record",zone:"tc",width:180,height:46},{id:"wc-spindle",label:"Windchill 002410 B.1",kind:"source-record",zone:"wc",width:180,height:46},{id:"change",label:"CN-8 Spindle update",kind:"change",zone:"wc",width:170,height:46},{id:"document",label:"Spindle drawing D-410",kind:"document",zone:"wc",width:180,height:46}];
const sap:DemoNode[]=[...plm,{id:"sap-mat",label:"SAP Material 002410",kind:"material",zone:"sap",width:175,height:46},{id:"stock",label:"Stock at Plant 1000",kind:"stock",zone:"sap",width:165,height:46},{id:"movement",label:"Material Document 490001",kind:"movement",zone:"sap",width:190,height:46},{id:"financial",label:"FI Document 510001",kind:"financial",zone:"sap",width:170,height:46}];
const cfg:DemoNode[]=[...sap,{id:"cfg-rule",label:"BODY configuration rule",kind:"configuration",zone:"cfg",width:180,height:46},{id:"cfg-option",label:"Resolved BODY option",kind:"configuration",zone:"cfg",width:170,height:46}];
const requirement:DemoNode[]=[...cfg,{id:"requirement",label:"R-42 Load capacity",kind:"requirement",zone:"satellite",width:170,height:46},{id:"excel",label:"Excel BOM row 17",kind:"provenance",zone:"satellite",width:160,height:44},{id:"unresolved",label:"Unresolved supplier reference",kind:"unresolved",zone:"satellite",width:195,height:44}];
const edges:DemoEdge[]=[{id:"e-focus-product",source:"focus",target:"product",family:"focus",label:"investigates",priority:"always"},{id:"e-product-tc",source:"product",target:"tc-product",family:"deterministic",label:"represented in",priority:"active"},{id:"e-product-wc",source:"product",target:"wc-product",family:"deterministic",label:"represented in",priority:"active"},{id:"e-product-sap",source:"product",target:"sap-product",family:"deterministic",label:"represented in",priority:"active"},{id:"e-product-cfg",source:"product",target:"cfg-product",family:"configuration",label:"configured by",priority:"active"},{id:"e-body",source:"tc-product",target:"body",family:"structural",label:"contains",priority:"hover"},{id:"e-head",source:"tc-product",target:"head",family:"structural",label:"contains",priority:"hover"},{id:"e-washer",source:"tc-product",target:"washer",family:"structural",label:"contains",priority:"hover"},{id:"e-occ",source:"body",target:"occ",family:"occurrence",label:"contains occurrence",priority:"active"},{id:"e-spindle",source:"occ",target:"spindle",family:"occurrence",label:"occurrence of",priority:"active"},{id:"e-tc-spindle",source:"spindle",target:"tc-spindle",family:"deterministic",label:"represented in",priority:"active"},{id:"e-wc-spindle",source:"spindle",target:"wc-spindle",family:"deterministic",label:"represented in",priority:"active"},{id:"e-match",source:"tc-spindle",target:"wc-spindle",family:"deterministic",label:"deterministic match",priority:"active"},{id:"e-change",source:"wc-spindle",target:"change",family:"change",label:"affected by",priority:"hover"},{id:"e-doc",source:"wc-spindle",target:"document",family:"document",label:"documented by",priority:"hover"},{id:"e-sap-mat",source:"spindle",target:"sap-mat",family:"deterministic",label:"represented in",priority:"active"},{id:"e-stock",source:"sap-mat",target:"stock",family:"sap",label:"has stock",priority:"hover"},{id:"e-move",source:"sap-mat",target:"movement",family:"sap",label:"has movement",priority:"active"},{id:"e-fi",source:"movement",target:"financial",family:"financial",label:"posted through",priority:"active"},{id:"e-rule",source:"cfg-product",target:"cfg-rule",family:"configuration",label:"configured by",priority:"hover"},{id:"e-option",source:"cfg-rule",target:"cfg-option",family:"configuration",label:"resolves",priority:"hover"},{id:"e-req",source:"requirement",target:"spindle",family:"requirement",label:"satisfied by",priority:"active"},{id:"e-excel",source:"washer",target:"excel",family:"heuristic",label:"heuristic match",priority:"inspector"},{id:"e-unresolved",source:"washer",target:"unresolved",family:"unresolved",label:"unresolved reference",priority:"inspector"}];
const cluster={id:"movement-cluster",label:"18 additional movements",kind:"cluster",zone:"sap",width:185,height:48,clusterCount:18};
function ids(nodes:DemoNode[]){return new Set(nodes.map(n=>n.id))}function relevant(nodes:DemoNode[]){const set=ids(nodes);return edges.filter(e=>set.has(e.source)&&set.has(e.target))}
export function scenario(id:ScenarioId,budget=28){let nodes=id==="empty"?base:id==="resolved"?resolved:id==="product"?product:id==="plm"?plm:id==="sap"?sap:id==="configit"?cfg:requirement;if(id==="cluster")nodes=[...requirement,cluster];const original=nodes.length;let prevented=0;if(nodes.length>budget){const keep=nodes.filter(n=>n.kind==="focus"||n.kind==="pillar"||n.id==="product"||n.id==="requirement"||n.id==="sap-mat"||n.id==="movement"||n.id==="financial");const remainder=nodes.filter(n=>!keep.includes(n)).slice(0,Math.max(0,budget-keep.length-1));prevented=original-keep.length-remainder.length;nodes=[...keep,...remainder,{...cluster,label:`${prevented} hidden evidence records`,clusterCount:prevented}]}
let selectedEdges=relevant(nodes);if(id==="path")selectedEdges=selectedEdges.filter(e=>["e-req","e-sap-mat","e-move","e-fi","e-spindle"].includes(e.id));return{nodes,edges:selectedEdges,prevented};}
