import Graph from "graphology";
import forceAtlas2 from "graphology-layout-forceatlas2";
import louvain from "graphology-communities-louvain";
import pagerank from "graphology-metrics/centrality/pagerank";
import { bidirectional } from "graphology-shortest-path/unweighted";
import type{CanonicalGraphFixture,Domain,EntityId,EvidenceClass}from"@lattice-lab/contracts/canonical-graph";
export type Analytics={communities:Map<string,number>;pagerank:Map<string,number>;components:Map<string,number>;maxPageRank:number;communityCount:number;componentCount:number};
const domainColor:Record<string,string>={product:"#22d3ee",plm:"#818cf8",erp:"#34d399",cpq:"#f472b6",requirements:"#a78bfa",change:"#fb923c",document:"#facc15",data:"#94a3b8",source:"#f87171",manufacturing:"#14b8a6",supplier:"#e879f9"};
export const communityPalette=["#38bdf8","#a78bfa","#34d399","#fb923c","#f472b6","#facc15","#2dd4bf","#60a5fa","#c084fc","#fb7185"];
function seed(id:string){let value=2166136261;for(const char of id){value^=char.charCodeAt(0);value=Math.imul(value,16777619)}return Math.abs(value)}
export function buildGraph(fixture:CanonicalGraphFixture){const graph=new Graph({type:"mixed",multi:true,allowSelfLoops:false});for(const entity of fixture.entities){const angle=(seed(entity.id)%6283)/1000,radius=1+Math.sqrt(seed(entity.id)%1000)/10;graph.addNode(entity.id,{label:entity.label,kind:entity.kind,domain:entity.domain,evidence:entity.evidenceClass,x:Math.cos(angle)*radius,y:Math.sin(angle)*radius,size:3,color:domainColor[entity.domain]??"#64748b",hidden:false})}for(const edge of fixture.relationships){if(!graph.hasNode(edge.sourceId)||!graph.hasNode(edge.targetId))continue;graph.addDirectedEdgeWithKey(edge.id,edge.sourceId,edge.targetId,{kind:edge.kind,evidence:edge.evidenceClass,color:edge.evidenceClass==="heuristic-match"?"#f59e0b":edge.evidenceClass==="unavailable-evidence"?"#f87171":"#526079",size:1,hidden:false})}return graph}
export function computeAnalytics(graph:Graph):Analytics{const rawCommunities=louvain(graph as any) as Record<string,number>;const rawPagerank=pagerank(graph as any) as Record<string,number>;const communities=new Map(Object.entries(rawCommunities));const ranks=new Map(Object.entries(rawPagerank));let maxPageRank=0;ranks.forEach(value=>{maxPageRank=Math.max(maxPageRank,value)});const components=new Map<string,number>();let component=0;for(const start of graph.nodes()){if(components.has(start))continue;const queue=[start];components.set(start,component);while(queue.length){const node=queue.shift()!;for(const neighbor of graph.neighbors(node))if(!components.has(neighbor)){components.set(neighbor,component);queue.push(neighbor)}}component++}return{communities,pagerank:ranks,components,maxPageRank,communityCount:new Set(communities.values()).size,componentCount:component}}
export function applyAnalytics(graph:Graph,analytics:Analytics,colorMode:"domain"|"community"){graph.updateEachNodeAttributes((id,attrs)=>({...attrs,community:analytics.communities.get(id)??0,component:analytics.components.get(id)??0,pagerank:analytics.pagerank.get(id)??0,size:Math.min(12,2.8+Math.sqrt((analytics.pagerank.get(id)??0)/(analytics.maxPageRank||1))*9),color:colorMode==="community"?communityPalette[(analytics.communities.get(id)??0)%communityPalette.length]:domainColor[attrs.domain]??"#64748b"}),{attributes:["community","component","pagerank","size","color"]})}
export function stabilize(graph:Graph,iterations:number){if(graph.order<2)return;forceAtlas2.assign(graph as any,{iterations,settings:{gravity:1,scalingRatio:8,strongGravityMode:false,barnesHutOptimize:graph.order>300,slowDown:8}})}
export function shortestPath(graph:Graph,start:string,target:string){return (bidirectional(graph as any,start,target)??[]) as string[]}
export function neighborhood(graph:Graph,start:string,depth:number){const result=new Set<string>([start]),queue:[string,number][]=[[start,0]];while(queue.length){const[node,currentDepth]=queue.shift()!;if(currentDepth>=depth)continue;for(const neighbor of graph.neighbors(node))if(!result.has(neighbor)){result.add(neighbor);queue.push([neighbor,currentDepth+1])}}return result}
export function filterGraph(graph:Graph,domains:Set<Domain>,evidence:Set<EvidenceClass>){graph.updateEachNodeAttributes((_id,attrs)=>({...attrs,hidden:!domains.has(attrs.domain)||!evidence.has(attrs.evidence)}),{attributes:["hidden"]});graph.updateEachEdgeAttributes((_id,attrs,source,target)=>({...attrs,hidden:graph.getNodeAttribute(source,"hidden")||graph.getNodeAttribute(target,"hidden")||!evidence.has(attrs.evidence)}),{attributes:["hidden"]})}
export function fixturePathEntityIds(fixture:CanonicalGraphFixture){return new Set<EntityId>(["requirement:R42","part:spindle","sap:material:002410","sap:movement:490001","sap:financial:510001"].filter(id=>fixture.entities.some(entity=>entity.id===id)))}
