export type Evidence="authoritative"|"deterministic"|"verified"|"heuristic"|"unresolved"|"proposed"|"approved";
export type LinkState="source-fact"|"proposed"|"user-approved"|"rejected"|"investigation-only";
export type Item={id:string;label:string;kind:string;source:string;evidence:Evidence;branch:string;detail:string;parent?:string};
export type Link={id:string;from:string;to:string;type:string;evidence:Evidence;state:LinkState;rationale?:string;createdBy?:string;createdAt?:string;updatedAt?:string;investigationId?:string;scoped?:boolean};
export const items:Item[]=[
{id:"product",label:"Screwjack_002403",kind:"Product",source:"Lattice",evidence:"authoritative",branch:"root",detail:"Active engineering investigation"},
{id:"tc",label:"Teamcenter",kind:"Source pillar",source:"Teamcenter",evidence:"authoritative",branch:"tc",detail:"Authoritative PLM structure",parent:"product"},{id:"tc-record",label:"Item 002403 / A",kind:"Item Revision",source:"Teamcenter",evidence:"authoritative",branch:"tc",detail:"Released product revision",parent:"tc"},{id:"body",label:"Body_002409",kind:"Assembly",source:"Teamcenter",evidence:"authoritative",branch:"tc",detail:"Expandable product structure",parent:"tc-record"},{id:"occ",label:"Spindle occurrence",kind:"BOM Occurrence",source:"Teamcenter",evidence:"authoritative",branch:"tc",detail:"Independent occurrence",parent:"body"},{id:"spindle",label:"Screw Spindle_002410",kind:"Part",source:"Teamcenter",evidence:"authoritative",branch:"tc",detail:"Canonical engineering part",parent:"occ"},
{id:"wc",label:"Windchill",kind:"Source pillar",source:"Windchill",evidence:"authoritative",branch:"wc",detail:"Authoritative part and change context",parent:"product"},{id:"wc-record",label:"Part 002410 / B.1",kind:"Part Version",source:"Windchill",evidence:"deterministic",branch:"wc",detail:"Deterministic cross-source record",parent:"wc"},{id:"change",label:"CN-8 Spindle update",kind:"Change Notice",source:"Windchill",evidence:"verified",branch:"wc",detail:"Verified change impact",parent:"wc-record"},{id:"document",label:"Drawing D-410",kind:"Engineering Document",source:"Windchill",evidence:"authoritative",branch:"wc",detail:"Spindle drawing",parent:"wc-record"},{id:"requirement",label:"R-42 Load capacity",kind:"Requirement",source:"Requirements",evidence:"verified",branch:"wc",detail:"Verified requirement trace",parent:"wc-record"},
{id:"sap",label:"SAP",kind:"Source pillar",source:"SAP",evidence:"authoritative",branch:"sap",detail:"Operational and financial evidence",parent:"product"},{id:"material",label:"Material 002410",kind:"SAP Material",source:"SAP",evidence:"deterministic",branch:"sap",detail:"Deterministic part representation",parent:"sap"},{id:"stock",label:"Plant 1000 · 84 units",kind:"Stock",source:"SAP",evidence:"authoritative",branch:"sap",detail:"Current plant stock",parent:"material"},{id:"movement",label:"Material Doc 490001",kind:"Movement",source:"SAP",evidence:"authoritative",branch:"sap",detail:"Operational movement",parent:"material"},{id:"financial",label:"FI Doc 510001",kind:"Financial Document",source:"SAP",evidence:"authoritative",branch:"sap",detail:"Financial posting",parent:"movement"},{id:"cluster",label:"18 more movements",kind:"Summary Cluster",source:"SAP",evidence:"authoritative",branch:"sap",detail:"18 hidden movement records",parent:"material"},
{id:"cfg",label:"Configit",kind:"Source pillar",source:"Configit",evidence:"authoritative",branch:"cfg",detail:"Configuration context",parent:"product"},{id:"rule",label:"BODY configuration rule",kind:"Configuration Rule",source:"Configit",evidence:"authoritative",branch:"cfg",detail:"Resolved product rule",parent:"cfg"},
{id:"excel",label:"Excel BOM row 17",kind:"Provenance",source:"Excel",evidence:"heuristic",branch:"tc",detail:"Heuristic source correspondence",parent:"body"},{id:"unresolved",label:"Supplier reference missing",kind:"Unresolved Evidence",source:"Unknown",evidence:"unresolved",branch:"tc",detail:"Authoritative evidence unavailable",parent:"body"}
];
export const sourceLinks:Link[]=items.filter(i=>i.parent).map((i,index)=>({id:`fact-${index}`,from:i.parent!,to:i.id,type:i.id==="spindle"?"occurrence of":i.id==="financial"?"posted through":i.id==="requirement"?"satisfied by":"contains",evidence:i.evidence,state:"source-fact" as const})).concat([{id:"match",from:"spindle",to:"wc-record",type:"deterministic match",evidence:"deterministic",state:"source-fact"},{id:"represented",from:"spindle",to:"material",type:"represented in",evidence:"deterministic",state:"source-fact"}]);
export const branchStages:Record<string,string[]>={root:["product","tc","wc","sap","cfg"],tc:["tc-record","body","excel","unresolved"],spindle:["occ","spindle"],wc:["wc-record","change","document","requirement"],sap:["material","stock","movement","financial","cluster"],cfg:["rule"]};
export const pathIds=new Set(["requirement","wc-record","spindle","material","movement","financial"]);
