using System.Security.Cryptography;
using Orchestration.API.Engineering.Contracts;
using Orchestration.API.Models;
using Orchestration.API.Services;
namespace Orchestration.API.Engineering.Adapters.Teamcenter;
public sealed class TeamcenterEngineeringAdapter: IEngineeringSourceAdapter {
 readonly ISubprocessExecutor executor; public TeamcenterEngineeringAdapter(ISubprocessExecutor executor)=>this.executor=executor; public EngineeringSource Source=>EngineeringSource.Teamcenter;
 static SourceCapability Capability()=>new(EngineeringSource.Teamcenter,SourceReadiness.CapabilityLimited,[DiscoveryMode.ExactId,DiscoveryMode.Unsupported],true,false,false,true,true,false,false,false,true,true,true,true,[],["Product-name saved-query discovery has not been verified in the installed Teamcenter environment.","The legacy batch does not emit machine-readable status for every optional downstream stage."]);
 public Task<SourceCapability> GetCapabilitiesAsync(CancellationToken token)=>Task.FromResult(Capability());
 public Task<SourceDiscoveryOutcome> DiscoverAsync(EngineeringDiscoveryRequest request,QueryNormalizationRecord normalized,CancellationToken token){var q=request.Query; if(string.IsNullOrWhiteSpace(q.ProductId)){var warning=new StructuredWarning("teamcenter-name-search-unverified",Source,EngineeringStage.Discovery,"Teamcenter product-name discovery is capability-limited because a saved-query endpoint has not been verified.",DateTimeOffset.UtcNow);return Task.FromResult(new SourceDiscoveryOutcome(Source,StandardStatus.CapabilityLimited,Capability(),[],[warning],[],false));}var id=q.ProductId.Trim();var candidate=new SourceCandidate($"teamcenter:{id}",Source,id,id,"teamcenter-item",q.Revision,q.Version,"Teamcenter Item ID accepted by the existing extraction pipeline; existence is verified only after extraction.",null,MatchCategory.SourceNativeReference,"The identifier was supplied as a Teamcenter Item ID and has not yet been verified against the source.",ConfidenceClass.Unverified,["structure"],new Dictionary<string,string?>(),new(ProvenanceKind.CapabilityOnly,"teamcenter-legacy-pipeline",DateTimeOffset.UtcNow),true);return Task.FromResult(new SourceDiscoveryOutcome(Source,StandardStatus.Success,Capability(),[candidate],[],[],false));}
 public async Task<StandardExtractionResult> ExtractAsync(string jobId,EngineeringExtractionRequest request,IProgress<StandardProgress> progress,CancellationToken token){var started=DateTimeOffset.UtcNow;var candidate=request.Candidate;if(string.IsNullOrWhiteSpace(candidate.NativeId))return Failure(request,started,"teamcenter-item-id-required","A Teamcenter Item ID is required.",false);progress.Report(new(jobId,Source,EngineeringStage.TeamcenterStructureExtraction,JobState.Extracting,10,"Starting Teamcenter structure extraction.",DateTimeOffset.UtcNow));try{var legacy=new ExtractionRequest{Kind=ExtractionKind.Teamcenter,JobId=jobId,TeamcenterItemId=candidate.NativeId};var result=await executor.ExecuteAsync(legacy,m=>{progress.Report(new(jobId,Source,EngineeringStage.TeamcenterStructureExtraction,JobState.Extracting,50,"Teamcenter extraction is running.",DateTimeOffset.UtcNow));return Task.CompletedTask;},token);token.ThrowIfCancellationRequested();if(!result.Success||result.Bom?.BomRootNode is null)return Failure(request,started,"teamcenter-extraction-failed","Teamcenter did not produce a valid structure.",true);var verified=candidate with{ConfidenceClass=ConfidenceClass.Verified,MatchCategory=MatchCategory.VerifiedIdentifierMatch,MatchReason="A valid Teamcenter extraction output verified the source-native Item ID.",Provenance=new(ProvenanceKind.LiveSource,"teamcenter-soa",DateTimeOffset.UtcNow)};var warning=!string.IsNullOrWhiteSpace(result.OptionalStageWarning)?new StructuredWarning("teamcenter-optional-stage-partial",Source,EngineeringStage.ConfigitTransformation,"Teamcenter structure extraction succeeded, but an optional downstream stage was not fully successful.",DateTimeOffset.UtcNow):null;var warnings=warning is null?Array.Empty<StructuredWarning>():new[]{warning};var status=warning is null?StandardStatus.Success:StandardStatus.PartialSuccess;var completed=DateTimeOffset.UtcNow;var artifact=new SourceArtifactReference($"artifact-{Guid.NewGuid():N}",Source,"normalized-bom",completed,EvidenceAvailability.Available,Checksum(result.Bom),$"engineering-jobs/{jobId}/teamcenter/normalized-bom",ArtifactSensitivity.Sensitive,"job-retention-policy");return new(EngineeringContractVersions.V1,request.RequestId,request.CorrelationId,jobId,Source,status,new(status,verified,candidate.NativeId,warnings,[]),Capability(),result.Bom,[],new Dictionary<string,object?>(),warnings,[],new(jobId,Source,EngineeringStage.TeamcenterNormalization,status==StandardStatus.Success?JobState.Success:JobState.PartialSuccess,100,"Teamcenter structure extraction completed.",completed),[artifact],new(ProvenanceKind.LiveSource,"teamcenter-soa",completed),Stages(warning!=null),started,completed,(long)(completed-started).TotalMilliseconds);}catch(TimeoutException){return Failure(request,started,"teamcenter-timeout","Teamcenter extraction timed out.",true,StandardStatus.TimedOut,EngineeringStage.Timeout);}}
 static IReadOnlyList<StageObservation> Stages(bool optionalWarning)=>[new(EngineeringStage.TeamcenterSession,EvidenceAvailability.NotObserved,null,"Legacy batch does not emit machine-readable session status."),new(EngineeringStage.TeamcenterResolution,EvidenceAvailability.Available,StandardStatus.Success,"Item ID verified by valid extraction output."),new(EngineeringStage.TeamcenterStructureExtraction,EvidenceAvailability.Available,StandardStatus.Success,"Valid normalized structure produced."),new(EngineeringStage.TeamcenterPlmxmlExport,EvidenceAvailability.NotObserved,null,"Not independently observed."),new(EngineeringStage.TeamcenterNormalization,EvidenceAvailability.Available,StandardStatus.Success,"Legacy output normalized."),new(EngineeringStage.ConfigitTransformation,optionalWarning?EvidenceAvailability.Partial:EvidenceAvailability.NotObserved,optionalWarning?StandardStatus.PartialSuccess:null,"Optional downstream status is not fully machine-readable."),new(EngineeringStage.ConfigitCompilation,EvidenceAvailability.NotObserved,null,"Not independently observed."),new(EngineeringStage.ConfigitPublication,EvidenceAvailability.NotObserved,null,"Not independently observed.")];
 static string Checksum(BomRoot root){var bytes=System.Text.Json.JsonSerializer.SerializeToUtf8Bytes(root);return Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant();}
 static StandardExtractionResult Failure(EngineeringExtractionRequest r,DateTimeOffset started,string code,string message,bool retryable,StandardStatus status=StandardStatus.Failed,EngineeringStage stage=EngineeringStage.Extraction){var now=DateTimeOffset.UtcNow;var error=new StructuredError(code,EngineeringSource.Teamcenter,stage,message,message,retryable,now);var state=status==StandardStatus.Cancelled?JobState.Cancelled:status==StandardStatus.TimedOut?JobState.TimedOut:JobState.Failed;return new(EngineeringContractVersions.V1,r.RequestId,r.CorrelationId,$"failed-{Guid.NewGuid():N}",EngineeringSource.Teamcenter,status,new(status,r.Candidate,null,[],[error]),Capability(),null,[],new Dictionary<string,object?>(),[],[error],new("",EngineeringSource.Teamcenter,stage,state,100,message,now),[],new(ProvenanceKind.Unavailable,"teamcenter-legacy-pipeline",now),Stages(false),started,now,(long)(now-started).TotalMilliseconds);}
}
