import type { InvestigationGraph } from "../domain/model";
import type { ProjectedEdge,ProjectedNode } from "../contracts/projection";
import { INTELLIGENCE_DOMAINS,domainForEntity,domainForRelationship } from "./intelligence-domain-registry";
import { domainLevel,graphScalePolicy,visibilityBudget } from "./intelligence-visibility-policy";
import type { IntelligenceProjection,IntelligenceProjectionOptions } from "./intelligence-projection-types";
const domainNodeId=(id:string)=>`projection:domain:${id}`;
const WINDCHILL_DOMAINS=new Set(["physical-attributes","product-context","requirements","changes"]);
export function projectIntelligenceExperience(graph:InvestigationGraph,options:IntelligenceProjectionOptions):IntelligenceProjection{
 const subject=graph.entities.find(entity=>entity.kind==="identity")??graph.byId[graph.roots[0]];if(!subject)return{nodes:[],edges:[],structuralKey:"empty",domainIds:[],deferredCounts:{}};
 const windchillInvestigation=subject.source==="windchill"||graph.entities.some(entity=>entity.source==="windchill");
 const scale=graphScalePolicy(graph.entities.length,graph.relationships.length),nodes:ProjectedNode[]=[],edges:ProjectedEdge[]=[],deferred:Record<string,number>={};
 const projectEntity=(entity:typeof graph.entities[number]):ProjectedNode=>({id:entity.id,label:entity.name,subtitle:String(entity.attributes.value??entity.attributes.title??entity.canonicalKind??entity.kind),kind:entity.kind,source:entity.source,level:entity.level,selected:options.selectedId===entity.id,expanded:options.expanded.has(entity.id),hasChildren:false,hiddenChildren:0,nativeIdentifier:entity.sourceNodeId,attributes:entity.attributes,relationshipCount:graph.relationships.filter(r=>r.from===entity.id||r.to===entity.id).length,childCount:0,resolutionState:entity.sourceStatus,dimmed:false});
 nodes.push(projectEntity(subject));
 const definitions=INTELLIGENCE_DOMAINS.filter(definition=>windchillInvestigation?WINDCHILL_DOMAINS.has(definition.id):definition.id!=="cross-source");
 const available=definitions.map(definition=>{const members=graph.entities.filter(entity=>entity.id!==subject.id&&entity.canonicalKind!=="source-representation"&&domainForEntity(entity.kind)===definition.id);const relations=graph.relationships.filter(relationship=>domainForRelationship(relationship.family??relationship.kind)===definition.id);return{definition,members,relations}}).filter(item=>item.members.length||item.relations.length);
 for(const {definition,members,relations} of available){const id=domainNodeId(definition.id),level=domainLevel(id,options.expanded),budget=visibilityBudget(level,members.length),shown=level==="summary"?[]:members.slice(0,Math.min(scale.maxPerDomain,budget.entities)),hidden=members.length-shown.length;deferred[definition.id]=hidden;nodes.push({id,label:definition.title,subtitle:"",kind:"identity",source:"platform",level:1,selected:options.selectedId===id,expanded:level!=="summary",hasChildren:members.length>0,hiddenChildren:hidden,attributes:{domain:definition.id,itemCount:members.length,accent:definition.accent},relationshipCount:relations.length,childCount:members.length,resolutionState:"ready",dimmed:false});edges.push({id:`projection:domain-edge:${definition.id}`,source:subject.id,target:id,kind:"contains",selected:false});for(const entity of shown){if(!nodes.some(node=>node.id===entity.id))nodes.push(projectEntity(entity));edges.push({id:`projection:member:${definition.id}:${entity.id}`,source:id,target:entity.id,kind:"contains",selected:false});}}
 return{nodes:nodes.sort((a,b)=>a.id.localeCompare(b.id)),edges:edges.sort((a,b)=>a.id.localeCompare(b.id)),structuralKey:nodes.map(n=>n.id).sort().join("|"),domainIds:available.map(x=>x.definition.id),deferredCounts:Object.freeze(deferred)};
}
