import type { EngineeringEntity,InvestigationGraph } from "../domain/model";
import type { ProjectedEdge,ProjectedNode } from "../contracts/projection";
import { INTELLIGENCE_DOMAINS,domainForEntity } from "./intelligence-domain-registry";
import type { IntelligenceDomainId,IntelligenceProjection,IntelligenceProjectionOptions } from "./intelligence-projection-types";
const domainNodeId=(id:string)=>`projection:domain:${id}`;
export function projectIntelligenceExperience(graph:InvestigationGraph,options:IntelligenceProjectionOptions):IntelligenceProjection{
 const subject=graph.entities.find(entity=>entity.kind==="identity")??graph.byId[graph.roots[0]];if(!subject)return{nodes:[],edges:[],structuralKey:"empty",domainIds:[],deferredCounts:{}};
 const nodes:ProjectedNode[]=[];const edges:ProjectedEdge[]=[];const deferred:Record<string,number>={};
 const projectEntity=(entity:EngineeringEntity):ProjectedNode=>({id:entity.id,label:entity.name,subtitle:String(entity.attributes.value??entity.attributes.title??entity.canonicalKind??entity.kind),kind:entity.kind,source:entity.source,level:entity.level,selected:options.selectedId===entity.id,expanded:options.expanded.has(entity.id),hasChildren:false,hiddenChildren:0,nativeIdentifier:entity.sourceNodeId,capturedAt:entity.provenance.capturedAt,attributes:entity.attributes,relationshipCount:graph.relationships.filter(r=>r.from===entity.id||r.to===entity.id).length,childCount:0,resolutionState:entity.sourceStatus,dimmed:false});
 nodes.push(projectEntity(subject));
 const subjectExcluded=new Set([subject.id]);const parentLinks=graph.relationships.filter(r=>r.kind==="contains");
 const explicitDomain=new Map<string,IntelligenceDomainId>();for(const entity of graph.entities){const domain=domainForEntity(entity.canonicalKind??entity.kind);if(domain)explicitDomain.set(entity.id,domain)}
 const resolveDomain=(entityId:string,seen=new Set<string>()):IntelligenceDomainId|undefined=>{if(explicitDomain.has(entityId))return explicitDomain.get(entityId);if(seen.has(entityId))return undefined;seen.add(entityId);const parent=parentLinks.find(link=>link.to===entityId);return parent?resolveDomain(parent.from,seen):undefined};
 const domainOf=new Map(graph.entities.map(entity=>[entity.id,resolveDomain(entity.id)]));
 for(const definition of INTELLIGENCE_DOMAINS){const members=graph.entities.filter(entity=>!subjectExcluded.has(entity.id)&&entity.canonicalKind!=="source-representation"&&domainOf.get(entity.id)===definition.id);if(!members.length)continue;const memberIds=new Set(members.map(entity=>entity.id));const internal=parentLinks.filter(link=>memberIds.has(link.from)&&memberIds.has(link.to));const children=new Map<string,string[]>();const hasParent=new Set<string>();for(const link of internal){children.set(link.from,[...(children.get(link.from)??[]),link.to]);hasParent.add(link.to)}const roots=members.filter(entity=>!hasParent.has(entity.id));const id=domainNodeId(definition.id);const domainExpanded=options.expanded.has(id);const visible=new Set<string>();const reveal=(entityId:string)=>{visible.add(entityId);if(options.expanded.has(entityId))for(const child of children.get(entityId)??[])reveal(child)};if(domainExpanded)roots.forEach(root=>reveal(root.id));deferred[definition.id]=members.length-visible.size;
  nodes.push({id,label:definition.title,subtitle:"",kind:"identity",source:"platform",level:1,selected:options.selectedId===id,expanded:domainExpanded,hasChildren:true,hiddenChildren:deferred[definition.id],attributes:{domain:definition.id,itemCount:members.length,accent:definition.accent},relationshipCount:internal.length,childCount:roots.length,resolutionState:"ready",dimmed:false});edges.push({id:`projection:domain-edge:${definition.id}`,source:subject.id,target:id,kind:"contains",selected:false});
  for(const entity of members.filter(item=>visible.has(item.id))){const childIds=children.get(entity.id)??[];nodes.push({...projectEntity(entity),level:2,hasChildren:childIds.length>0,childCount:childIds.length,hiddenChildren:options.expanded.has(entity.id)?0:childIds.length});const parent=internal.find(link=>link.to===entity.id)?.from;edges.push({id:`projection:member:${definition.id}:${entity.id}`,source:parent&&visible.has(parent)?parent:id,target:entity.id,kind:"contains",selected:false})}
 }
 const structuralKey=nodes.map(node=>node.id).sort().join("|")+"::"+edges.map(edge=>edge.id).sort().join("|");return{nodes:nodes.sort((a,b)=>a.id.localeCompare(b.id)),edges:edges.sort((a,b)=>a.id.localeCompare(b.id)),structuralKey,domainIds:INTELLIGENCE_DOMAINS.filter(domain=>nodes.some(node=>node.id===domainNodeId(domain.id))).map(domain=>domain.id),deferredCounts:Object.freeze(deferred)}
}
