using System.Collections.Concurrent;using Orchestration.API.Engineering.Contracts;
namespace Orchestration.API.Engineering.Federation;
public interface IFederatedExtractionJobStore{FederatedExtractionJobSnapshot Create(string discoveryId,string requestId,string correlationId,IReadOnlyList<(EngineeringSource source,string candidateId)> selected);bool TryGet(string id,out FederatedExtractionJobSnapshot? snapshot);bool TryProgress(string id,string executionId,StandardStatus status,int progress);bool TryComplete(string id,string executionId,StandardExtractionResult result);bool TryStartRetry(string id,EngineeringSource source,out FederatedExtractionChildSnapshot? child);bool TryRequestCancellation(string id);bool TryFinish(string id,FederatedExtractionJobState state,FederatedEngineeringExtractionResult result);}
public sealed class FederatedExtractionJobStore:IFederatedExtractionJobStore
{
 readonly ConcurrentDictionary<string,FederatedExtractionJobSnapshot> jobs=new();static readonly HashSet<FederatedExtractionJobState> terminal=[FederatedExtractionJobState.Success,FederatedExtractionJobState.PartialSuccess,FederatedExtractionJobState.Empty,FederatedExtractionJobState.Unavailable,FederatedExtractionJobState.AwaitingContext,FederatedExtractionJobState.Failed,FederatedExtractionJobState.Cancelled,FederatedExtractionJobState.TimedOut];
 public FederatedExtractionJobSnapshot Create(string d,string r,string c,IReadOnlyList<(EngineeringSource source,string candidateId)> selected){var now=DateTimeOffset.UtcNow;var id=$"federated-extraction-{Guid.NewGuid():N}";var children=selected.Select(x=>new FederatedExtractionChildSnapshot($"extract-{x.source.ToString().ToLowerInvariant()}-{Guid.NewGuid():N}",x.source,x.candidateId,1,StandardStatus.Queued,0,now,null,true,false,null)).ToArray();var job=new FederatedExtractionJobSnapshot(id,d,r,c,FederatedExtractionJobState.Accepted,0,now,null,null,children,null);jobs[id]=job;return job;}
 public bool TryGet(string id,out FederatedExtractionJobSnapshot? s)=>jobs.TryGetValue(id,out s);
 public bool TryProgress(string id,string e,StandardStatus status,int progress)=>Update(id,o=>{if(terminal.Contains(o.State))return o;var rows=o.Sources.Select(x=>x.SourceExecutionId==e&&x.Active?x with{Status=status,ProgressPercent=Math.Max(x.ProgressPercent,Math.Clamp(progress,0,99))}:x).ToArray();return o with{State=FederatedExtractionJobState.Extracting,ProgressPercent=Progress(rows),Sources=rows};});
 public bool TryComplete(string id,string e,StandardExtractionResult result)=>Update(id,o=>{var child=o.Sources.FirstOrDefault(x=>x.SourceExecutionId==e);if(child is null||!child.Active||child.Attempt!=o.Sources.Where(x=>x.Source==child.Source).Max(x=>x.Attempt))return o;if(o.State==FederatedExtractionJobState.CancellationRequested&&result.Status is not StandardStatus.Cancelled)return o;var rows=o.Sources.Select(x=>x.SourceExecutionId==e?x with{Status=result.Status,ProgressPercent=100,CompletedAt=DateTimeOffset.UtcNow,Active=false,Retryable=result.Errors.Any(y=>y.Retryable),Result=result}:x).ToArray();return o with{Sources=rows,ProgressPercent=Progress(rows)};});
 public bool TryStartRetry(string id,EngineeringSource source,out FederatedExtractionChildSnapshot? child){child=null;while(jobs.TryGetValue(id,out var o)){if(o.State is FederatedExtractionJobState.Cancelled or FederatedExtractionJobState.CancellationRequested)return false;var prior=o.Sources.Where(x=>x.Source==source).OrderByDescending(x=>x.Attempt).FirstOrDefault();if(prior is null||prior.Active||!prior.Retryable||prior.Status==StandardStatus.AwaitingContext)return false;child=new($"extract-{source.ToString().ToLowerInvariant()}-{Guid.NewGuid():N}",source,prior.CandidateId,prior.Attempt+1,StandardStatus.Queued,0,DateTimeOffset.UtcNow,null,true,false,null);var n=o with{State=FederatedExtractionJobState.Extracting,CompletedAt=null,Result=null,Sources=o.Sources.Append(child).ToArray()};if(jobs.TryUpdate(id,n,o))return true;}return false;}
 public bool TryRequestCancellation(string id)=>Update(id,o=>terminal.Contains(o.State)||o.State==FederatedExtractionJobState.CancellationRequested?o:o with{State=FederatedExtractionJobState.CancellationRequested,CancellationRequestedAt=DateTimeOffset.UtcNow,Sources=o.Sources.Select(x=>x.Active?x with{Status=StandardStatus.Cancelled}:x).ToArray()});
 public bool TryFinish(string id,FederatedExtractionJobState state,FederatedEngineeringExtractionResult result)=>Update(id,o=>terminal.Contains(o.State)?o:o with{State=state,ProgressPercent=100,CompletedAt=result.CompletedAt,Result=result});
 static int Progress(IReadOnlyList<FederatedExtractionChildSnapshot> rows){var latest=rows.GroupBy(x=>x.Source).Select(x=>x.OrderByDescending(y=>y.Attempt).First()).ToArray();return latest.Length==0?0:(int)Math.Floor(latest.Average(x=>x.ProgressPercent));}
 bool Update(string id,Func<FederatedExtractionJobSnapshot,FederatedExtractionJobSnapshot> f){while(jobs.TryGetValue(id,out var o)){var n=f(o);if(ReferenceEquals(n,o))return false;if(jobs.TryUpdate(id,n,o))return true;}return false;}
}
