
using System.Text.Json;using Microsoft.AspNetCore.Mvc;using Orchestration.API.Controllers;using Orchestration.API.Engineering.Contracts;using Orchestration.API.Engineering.Controllers;using Orchestration.API.Engineering.Federation;using Orchestration.API.Models;
namespace Orchestration.API.Tests.Engineering.Federation;
public sealed class FederatedExtractionSprint2Tests
{
 [Fact]public void OneSelectionCreatesOneAuthoritativeChild(){var s=new FederatedExtractionJobStore();var j=s.Create("d","r","c",[(EngineeringSource.Teamcenter,"tc:1")]);Assert.Single(j.Sources);Assert.Equal(1,j.Sources[0].Attempt);}
 [Fact]public void FourSelectionsCreateFourChildren(){var s=new FederatedExtractionJobStore();var selected=Enum.GetValues<EngineeringSource>().Select(x=>(x,$"{x}:1")).ToArray();Assert.Equal(4,s.Create("d","r","c",selected).Sources.Count);}
 [Fact]public void UnselectedSourcesNeverCreateChildren(){var s=new FederatedExtractionJobStore();var j=s.Create("d","r","c",[(EngineeringSource.Sap,"sap:1")]);Assert.DoesNotContain(j.Sources,x=>x.Source==EngineeringSource.Windchill);}
 [Fact]public void ParentProgressIsConservativeAverage(){var s=new FederatedExtractionJobStore();var j=s.Create("d","r","c",[(EngineeringSource.Sap,"sap:1"),(EngineeringSource.Configit,"configit:1")]);s.TryProgress(j.ParentExtractionJobId,j.Sources[0].SourceExecutionId,StandardStatus.Extracting,80);Assert.True(s.TryGet(j.ParentExtractionJobId,out var current));Assert.Equal(40,current!.ProgressPercent);}
 [Fact]public void MixedSourceResultsRemainIndependent(){var s=new FederatedExtractionJobStore();var j=s.Create("d","r","c",[(EngineeringSource.Teamcenter,"tc:1"),(EngineeringSource.Sap,"sap:1")]);s.TryComplete(j.ParentExtractionJobId,j.Sources[0].SourceExecutionId,Result(EngineeringSource.Teamcenter,StandardStatus.Success));s.TryComplete(j.ParentExtractionJobId,j.Sources[1].SourceExecutionId,Result(EngineeringSource.Sap,StandardStatus.Failed,true));Assert.True(s.TryGet(j.ParentExtractionJobId,out var current));Assert.Equal(StandardStatus.Success,current!.Sources[0].Result!.Status);Assert.Equal(StandardStatus.Failed,current.Sources[1].Result!.Status);}
 [Fact]public void RetryCreatesImmutableNewAttempt(){var s=new FederatedExtractionJobStore();var j=s.Create("d","r","c",[(EngineeringSource.Sap,"sap:1")]);s.TryComplete(j.ParentExtractionJobId,j.Sources[0].SourceExecutionId,Result(EngineeringSource.Sap,StandardStatus.Failed,true));Assert.True(s.TryStartRetry(j.ParentExtractionJobId,EngineeringSource.Sap,out var retry));Assert.Equal(2,retry!.Attempt);Assert.True(s.TryGet(j.ParentExtractionJobId,out var current));Assert.Equal(2,current!.Sources.Count);}
 [Fact]public void SupersededAttemptCannotOverwriteRetry(){var s=new FederatedExtractionJobStore();var j=s.Create("d","r","c",[(EngineeringSource.Sap,"sap:1")]);s.TryComplete(j.ParentExtractionJobId,j.Sources[0].SourceExecutionId,Result(EngineeringSource.Sap,StandardStatus.Failed,true));s.TryStartRetry(j.ParentExtractionJobId,EngineeringSource.Sap,out var retry);Assert.False(s.TryComplete(j.ParentExtractionJobId,j.Sources[0].SourceExecutionId,Result(EngineeringSource.Sap,StandardStatus.Success)));Assert.True(s.TryComplete(j.ParentExtractionJobId,retry!.SourceExecutionId,Result(EngineeringSource.Sap,StandardStatus.Success)));}
 [Fact]public void ResultSerializationDoesNotExposeAbsolutePathsOrSecrets(){var json=JsonSerializer.Serialize(Result(EngineeringSource.Windchill,StandardStatus.Success));Assert.DoesNotContain("C:\\\\",json);Assert.False(json.Contains("Authorization",StringComparison.OrdinalIgnoreCase));Assert.False(json.Contains("password",StringComparison.OrdinalIgnoreCase));}
 [Fact]public void FederatedControllerPublishesPollingResultCancelAndRetryRoutes(){var methods=typeof(FederatedEngineeringExtractionController).GetMethods();foreach(var name in new[]{"Post","Get","Result","Cancel","Retry"})Assert.Contains(methods,x=>x.Name==name);}
 [Fact]public void LegacyPipelineControllerRemainsAvailable(){var route=typeof(PipelineController).GetCustomAttributes(typeof(RouteAttribute),true).Cast<RouteAttribute>().Single();Assert.Equal("api/[controller]",route.Template);}
 static StandardExtractionResult Result(EngineeringSource source,StandardStatus status,bool retryable=false){var now=DateTimeOffset.UtcNow;IReadOnlyList<StructuredError> error=status==StandardStatus.Failed?[new StructuredError("failed",source,EngineeringStage.Extraction,"failed","failed",retryable,now)]:[];var candidate=new SourceCandidate($"{source}:1",source,"1","One","product",null,null,null,null,MatchCategory.VerifiedIdentifierMatch,"verified",ConfidenceClass.Verified,[],new Dictionary<string,string?>(),new(ProvenanceKind.DeterministicTestFixture,"test",now),true);var cap=new SourceCapability(source,SourceReadiness.Ready,[],true,true,true,true,false,false,false,false,false,true,true,true,[],[]);return new("1.0","r","c","e",source,status,new(status,candidate,"1",[],error),cap,new BomRoot{SourceItemId="1",BomRootNode=new BomNode{ItemId="1"}},[],new Dictionary<string,object?>(),[],error,new("e",source,EngineeringStage.Extraction,status==StandardStatus.Success?JobState.Success:JobState.Failed,100,"done",now),[],new(ProvenanceKind.DeterministicTestFixture,"test",now),[],now,now,0);}
}
