jco.client.ashost=172.28.236.11
jco.client.sysnr=00
jco.client.client=800
jco.client.user=T4SUSER
jco.client.passwd=MbseSap@25!
jco.client.lang=EN

jco.destination.pool_capacity=3
jco.destination.peak_limit=10
