/* eslint-disable react-hooks/set-state-in-effect */
"use client";
import { useEffect, useMemo, useState } from "react";
import { motion } from "motion/react";
import { IconBuildingWarehouse, IconCash, IconFileInvoice, IconHistory, IconPackage, IconRefresh } from "@tabler/icons-react";
import { toast } from "sonner";
import { ApiError, getSapOperationalImpact } from "@/lib/api";
import type { SapMaterialMovement, SapOperationalImpact } from "@/types/sap-operational-impact";
import { OutcomeNotice, RetryButton } from "@/components/feedback/OutcomeNotice";
import { TechnicalDetails } from "@/components/feedback/TechnicalDetails";
import { userFacingError } from "@/lib/user-facing-errors";

const wait=(ms:number)=>new Promise((resolve)=>window.setTimeout(resolve,ms));
const number=(value:number|null|undefined)=>value==null?"Not available":new Intl.NumberFormat("en-IN",{maximumFractionDigits:3}).format(value);
const quantity=(value:number|null|undefined,unit="")=>value==null?"Not available":`${number(value)}${unit?` ${unit}`:""}`;
const money=(value:number|null|undefined,currency="INR")=>value==null?"Not available":new Intl.NumberFormat("en-IN",{style:"currency",currency:currency||"INR",maximumFractionDigits:2}).format(value);
const date=(value:string)=>{if(!value)return "Not available";const compact=value.replace(/\D/g,"");if(compact.length===8)return `${compact.slice(6,8)} ${new Date(Number(compact.slice(0,4)),Number(compact.slice(4,6))-1,1).toLocaleString("en",{month:"short"})} ${compact.slice(0,4)}`;return value;};

export function SapOperationalImpactPanel({jobId,active}:{jobId:string|null;active:boolean}){
 const [data,setData]=useState<SapOperationalImpact|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(false),[retry,setRetry]=useState(0),[selectedKey,setSelectedKey]=useState<string|null>(null);
 useEffect(()=>{if(!jobId||!active){setData(null);setSelectedKey(null);return;}let cancelled=false;setLoading(true);setError("");setData(null);void(async()=>{for(let attempt=0;attempt<60&&!cancelled;attempt++){try{const result=await getSapOperationalImpact(jobId);if(cancelled)return;setData(result);const first=result.history?.movements?.[0];setSelectedKey(first?`${first.materialDocument}-${first.materialDocumentYear}-${first.item}`:null);setLoading(false);const partial=result.status!=="complete"||result.warnings.length>0;toast[partial?"warning":"success"](partial?"SAP operational impact completed with warnings":"SAP operational impact ready",{id:"sap-operational-impact",description:"Current stock, movement and financial evidence are available."});return;}catch(cause){if(cause instanceof ApiError&&cause.status===404&&attempt<59){await wait(2000);continue;}if(!cancelled){const outcome=userFacingError("sap",cause,cause instanceof ApiError?cause.status:undefined);setError(outcome.message);setLoading(false);}return;}}})();return()=>{cancelled=true;};},[jobId,active,retry]);
 const movements=useMemo(()=>[...(data?.history?.movements??[])].sort((a,b)=>`${b.postingDate}${b.createdTime}`.localeCompare(`${a.postingDate}${a.createdTime}`)),[data]);
 const selected=movements.find((item)=>`${item.materialDocument}-${item.materialDocumentYear}-${item.item}`===selectedKey)??movements[0]??null;
 const current=data?.currentState?.materials?.find((item)=>item.materialId===data.sourceMaterialId)??data?.currentState?.materials?.[0]??null;
 if(!active||!jobId)return null;
 if(loading)return <section className="mt-5 rounded-2xl border border-slate-800 bg-slate-950/90 p-6 text-slate-200"><div className="flex items-center gap-3"><IconRefresh className="h-5 w-5 animate-spin text-cyan-400"/><div><p className="text-sm font-semibold">Building SAP operational trace</p><p className="mt-1 text-sm text-slate-400">Loading current state, material movements and financial evidence.</p></div></div><div className="mt-5 grid gap-3 md:grid-cols-4">{Array.from({length:4}).map((_,i)=><div key={i} className="h-24 animate-pulse rounded-xl bg-slate-900"/>)}</div></section>;
 if(error)return <div className="mt-5"><OutcomeNotice tone="error" title="SAP operational impact is unavailable" message={error} actions={<RetryButton onClick={()=>setRetry((v)=>v+1)} label="Retry trace"/>}/></div>;
 if(!data)return null;
 return <motion.section initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{duration:.22}} className="mt-5 overflow-hidden rounded-2xl border border-slate-800 bg-slate-950/95 text-slate-100">
  <header className="flex flex-wrap items-start justify-between gap-4 border-b border-slate-800 px-5 py-5"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-cyan-400">SAP operational evidence</p><h3 className="mt-1.5 text-xl font-semibold">Stock, valuation and transaction trace</h3><p className="mt-1.5 text-sm text-slate-400">Material {data.sourceMaterialId} · Plant {data.plant}</p></div><EvidenceBadge value={data.status}/></header>
  <div className="grid gap-px border-b border-slate-800 bg-slate-800 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<IconPackage/>} label="Unrestricted stock" value={quantity(current?.stock.unrestricted,current?.baseUnit)} note="Current physical stock"/><Metric icon={<IconBuildingWarehouse/>} label="Inventory value" value={money(current?.inventory.totalStockValue,current?.organization.currency)} note="Current SAP valuation"/><Metric icon={<IconCash/>} label="Effective unit cost" value={money(current?.cost.effectiveUnitCost,current?.organization.currency)} note={`Price control ${current?.cost.priceControl||"not available"}`}/><Metric icon={<IconHistory/>} label="Movements" value={String(movements.length)} note="Historical material documents"/></div>
  {current?<div className="border-b border-slate-800 px-5 py-5"><div className="flex items-center justify-between gap-4"><div><h4 className="font-semibold">Current state</h4><p className="mt-1 text-xs text-slate-500">Confirmed stock and valuation at extraction time.</p></div><EvidenceBadge value={current.status==="complete"?"confirmed":"partial_success"}/></div><dl className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Fact label="Material" value={`${current.materialId} · ${current.description||"Description unavailable"}`}/><Fact label="Organization" value={`Plant ${current.organization.plant||"-"} · Company ${current.organization.companyCode||"-"}`}/><Fact label="Valuated quantity" value={quantity(current.inventory.valuatedQuantity,current.baseUnit)}/><Fact label="Moving average price" value={money(current.cost.movingAveragePrice,current.organization.currency)}/><Fact label="Standard price" value={money(current.cost.standardPrice,current.organization.currency)}/><Fact label="Price unit" value={number(current.cost.priceUnit)}/><Fact label="Valuation class" value={current.cost.valuationClass}/><Fact label="Reconciliation" value={current.checks?.valuationReconciled===true?"Reconciled":current.checks?.valuationReconciled===false?"Difference detected":"Not available"}/></dl></div>:null}
  <div className="grid min-h-[540px] xl:grid-cols-[minmax(0,1.1fr)_minmax(420px,.9fr)]">
   <div className="border-b border-slate-800 xl:border-b-0 xl:border-r"><div className="flex items-center justify-between border-b border-slate-800 px-5 py-4"><div><h4 className="font-semibold">Movement history</h4><p className="mt-1 text-xs text-slate-400">Select a material document to inspect its operational and financial trace.</p></div><span className="text-xs text-slate-500">{movements.length} records</span></div>
    {movements.length?<div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-900/70 text-left text-[11px] uppercase tracking-wide text-slate-500"><tr>{["Posting date","Movement","Document / item","Quantity","Value"].map((x)=><th key={x} className="px-4 py-3 font-semibold">{x}</th>)}</tr></thead><tbody className="divide-y divide-slate-800">{movements.map((movement)=>{const key=`${movement.materialDocument}-${movement.materialDocumentYear}-${movement.item}`,chosen=key===selectedKey;return <tr key={key} onClick={()=>setSelectedKey(key)} className={`cursor-pointer transition ${chosen?"bg-cyan-500/[.09]":"hover:bg-slate-900/70"}`}><td className="whitespace-nowrap px-4 py-3 text-slate-300">{date(movement.postingDate)}</td><td className="px-4 py-3"><span className="font-semibold text-slate-100">{movement.movementType||"-"}</span><span className="mt-0.5 block text-xs text-slate-500">{movement.movementDescription||"Material movement"}</span></td><td className="px-4 py-3"><span className="font-medium">{movement.materialDocument}</span><span className="text-slate-500"> / {movement.item}</span><span className="mt-0.5 block text-xs text-slate-500">Year {movement.materialDocumentYear}</span></td><td className={`whitespace-nowrap px-4 py-3 font-semibold ${(movement.signedQuantity??0)<0?"text-rose-300":"text-emerald-300"}`}>{quantity(movement.signedQuantity,movement.unit)}</td><td className={`whitespace-nowrap px-4 py-3 font-semibold ${(movement.signedLocalAmount??0)<0?"text-rose-300":"text-emerald-300"}`}>{money(movement.signedLocalAmount,movement.currency||current?.organization.currency)}</td></tr>;})}</tbody></table></div>:<div className="p-6"><OutcomeNotice tone="info" title="No material movements returned" message="Current stock and valuation remain available. SAP did not return historical movement rows for this material and plant."/></div>}
   </div>
   <div className="bg-slate-900/25 p-5">{selected?<MovementTrace movement={selected}/>:<div className="flex min-h-[300px] items-center justify-center text-center text-sm text-slate-500">Select a movement to inspect its trace.</div>}</div>
  </div>
  {(data.warnings.length||data.history?.warnings?.length)?<div className="border-t border-slate-800 p-5"><OutcomeNotice compact tone="warning" title="SAP returned partial evidence" message="Confirmed information is shown. Referenced or unavailable details are labelled separately." technicalDetails={[...data.warnings,...(data.history?.warnings??[])].join("\n")}/></div>:null}
 </motion.section>;
}
function MovementTrace({movement}:{movement:SapMaterialMovement}){const accounting=movement.accountingDocument;return <div className="space-y-5"><div><div className="flex items-center justify-between gap-3"><div><p className="text-[11px] font-semibold uppercase tracking-[.14em] text-cyan-400">Transaction trace</p><h4 className="mt-1 text-lg font-semibold">{movement.materialDocument} / {movement.item}</h4></div><EvidenceBadge value={movement.evidenceConfidence}/></div><dl className="mt-4 grid gap-3 sm:grid-cols-2"><Fact label="Source transaction" value={movement.sourceTransaction}/><Fact label="Production order" value={movement.productionOrder}/><Fact label="Movement" value={`${movement.movementType}${movement.movementDescription?` · ${movement.movementDescription}`:""}`}/><Fact label="Posting date" value={date(movement.postingDate)}/><Fact label="Plant / location" value={`${movement.plant||"-"} / ${movement.storageLocation||"-"}`}/><Fact label="Business area" value={movement.businessArea}/><Fact label="Profit center" value={movement.profitCenter}/><Fact label="Material-item G/L" value={movement.materialItemGlAccount}/></dl></div>
 <div className="rounded-xl border border-slate-800 bg-slate-950/70 p-4"><div className="flex items-center gap-2"><IconFileInvoice className="h-5 w-5 text-cyan-400"/><h5 className="font-semibold">Financial trace</h5></div>{accounting.availability==="confirmed"?<><p className="mt-2 text-sm text-slate-400">Document {accounting.documentNumber} · Company code {accounting.companyCode} · FI fiscal year {accounting.fiscalYear} · Period {accounting.postingPeriod}</p><div className="mt-4 space-y-2">{accounting.lines.length?accounting.lines.map((line)=><div key={`${line.lineItem}-${line.glAccount}`} className="flex items-center justify-between gap-4 rounded-lg border border-slate-800 bg-slate-900/70 px-3 py-3"><div className="min-w-0"><p className="font-semibold">{line.glAccount||"G/L unavailable"}</p><p className="truncate text-xs text-slate-500">{line.accountName||line.text||line.direction}</p></div><span className={`shrink-0 font-semibold ${(line.signedAmount??0)<0?"text-rose-300":"text-emerald-300"}`}>{money(line.signedAmount,line.currency||accounting.currency)}</span></div>):<p className="text-sm text-slate-500">The accounting document was found, but no line items were returned.</p>}</div></>:<p className="mt-3 text-sm text-slate-400">No linked FI document was returned for this movement.</p>}</div>
 <div className="grid gap-3 sm:grid-cols-2"><Reference title="Controlling reference" value={movement.controllingReference}/><Reference title="Material Ledger reference" value={movement.materialLedgerReference}/></div>
 <TechnicalDetails details={`Material document year: ${movement.materialDocumentYear}\nFI fiscal year: ${accounting.fiscalYear||"Not available"}\nEvidence confidence: ${movement.evidenceConfidence}`} />
 </div>}
function Metric({icon,label,value,note}:{icon:React.ReactNode;label:string;value:string;note:string}){return <div className="bg-slate-950 px-5 py-4"><span className="text-cyan-400 [&_svg]:h-4 [&_svg]:w-4">{icon}</span><p className="mt-2 text-xs font-semibold uppercase tracking-[.12em] text-slate-500">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p><p className="mt-1 text-xs text-slate-500">{note}</p></div>}
function Fact({label,value}:{label:string;value?:string}){return <div className="rounded-lg border border-slate-800 bg-slate-950/50 px-3 py-3"><dt className="text-[11px] uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1.5 break-words text-sm font-medium text-slate-200">{value||"Not available"}</dd></div>}
function Reference({title,value}:{title:string;value:SapMaterialMovement["controllingReference"]}){return <div className="rounded-xl border border-slate-800 bg-slate-950/55 p-4"><p className="text-xs font-semibold text-slate-300">{title}</p><p className="mt-2 text-sm text-slate-100">{value.reference||"Not found"}</p><p className="mt-1 text-xs text-slate-500">{value.availability==="referenced"?"Reference confirmed; detailed line items were not verified.":"No reference returned."}</p></div>}
function EvidenceBadge({value}:{value:string}){const good=value==="complete"||value==="confirmed",warn=value==="partial_success"||value==="referenced"||value==="reconstructed";return <span className={`rounded-full border px-2.5 py-1 text-[10px] font-bold uppercase tracking-wide ${good?"border-emerald-500/30 bg-emerald-500/10 text-emerald-300":warn?"border-amber-500/30 bg-amber-500/10 text-amber-300":"border-slate-700 bg-slate-900 text-slate-400"}`}>{value.replace(/_/g," ")}</span>}
