"use client";
import { useEffect, useState } from "react";
import { IconArrowDown, IconArrowUp, IconBuildingBank, IconCoins, IconPackage, IconRefresh } from "@tabler/icons-react";
import { getSapOperationalImpact } from "@/lib/api";
import type { SapHistoryEvent, SapOperationalImpact } from "@/types/sap-operational-impact";

export function SapOperationalImpactPanel({jobId,active}:{jobId:string|null;active:boolean}) {
 const [data,setData]=useState<SapOperationalImpact|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(false);
 async function load(){if(!jobId||!active)return;setLoading(true);setError("");for(let i=0;i<60;i++){try{setData(await getSapOperationalImpact(jobId));setLoading(false);return}catch(e){const status=(e as {status?:number}).status;if(status===404&&i<59){await new Promise(r=>setTimeout(r,2000));continue}setError(e instanceof Error?e.message:"SAP operational impact unavailable");break}}setLoading(false)}
 useEffect(()=>{void load()},[jobId,active]);if(!active||!jobId)return null;if(loading&&!data)return <Box>Reconstructing SAP movement and financial history...</Box>;if(error&&!data)return <Box><span className="text-rose-300">{error}</span><button onClick={load} className="ml-3 underline">Retry</button></Box>;
 const h=data?.history;if(!h)return <Box>Current SAP evidence is available, but no accessible movement history was returned.</Box>;const c=h.currentState,s=h.historySummary,m=h.material;
 return <section className="mt-4 space-y-4 rounded-2xl border border-slate-800 bg-slate-950/45 p-4 text-slate-100">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-cyan-400">SAP material intelligence</p><h3 className="mt-1 text-lg font-semibold">{m.materialId} · {m.description}</h3><p className="text-xs text-slate-500">Plant {m.plant} · Storage {m.storageLocation||"Plant scope"} · {h.systemId}/{h.client}</p></div><button onClick={load} className="flex items-center gap-2 text-xs text-slate-400"><IconRefresh className="h-4 w-4"/>Refresh</button></div>
  <div className="grid grid-cols-2 gap-px overflow-hidden rounded-xl border border-slate-800 bg-slate-800 md:grid-cols-4"><Metric label="Physical stock" value={`${n(c.physicalStock)} EA`} icon={<IconPackage/>}/><Metric label="Valuated quantity" value={`${n(c.valuatedQuantity)} EA`} icon={<IconPackage/>}/><Metric label="Inventory value" value={`${money(c.inventoryValue)} INR`} icon={<IconCoins/>}/><Metric label="Moving average" value={`${money(c.movingAveragePrice)} INR`} icon={<IconCoins/>}/><Metric label="Price control" value={c.priceControl||"—"}/><Metric label="Price unit" value={n(c.priceUnit)}/><Metric label="Valuation class" value={c.valuationClass||"—"}/><Metric label="Movements / G/L lines" value={`${s.movementCount} / ${s.accountingLineCount}`}/></div>
  <div className={`rounded-xl border p-3 text-sm ${s.quantityReconciledToCurrentValuation&&s.valueReconciledToCurrentInventory?"border-emerald-500/25 bg-emerald-500/10 text-emerald-200":"border-amber-500/25 bg-amber-500/10 text-amber-200"}`}><strong>{s.quantityReconciledToCurrentValuation&&s.valueReconciledToCurrentInventory?"Reconciled":"Reconciliation attention required"}</strong><p className="mt-1 text-xs opacity-80">History totals: {signed(s.netQuantityDelta)} EA and {signed(s.netInventoryValueDelta)} INR. Quantity: {yn(s.quantityReconciledToCurrentValuation)} · Value: {yn(s.valueReconciledToCurrentInventory)}</p></div>
  {(data?.warnings||[]).concat(h.warnings||[]).map(w=><div key={w} className="rounded-lg border border-amber-500/20 bg-amber-500/10 p-3 text-xs text-amber-200">{w}</div>)}
  <div><h4 className="text-sm font-semibold">Material movement timeline</h4><p className="mt-1 text-xs text-slate-500">Chronological MATDOC reconstruction with ACDOCA financial correlation.</p></div>
  <div className="space-y-3">{h.events.map(e=><EventCard key={`${e.documentYear}-${e.materialDocument}-${e.documentItem}`} event={e}/>)}</div>
 </section>
}
function EventCard({event:e}:{event:SapHistoryEvent}){const positive=(e.quantityDelta??0)>=0,label=e.movementType==="101"?"Goods receipt":e.movementType==="261"?"Production-order goods issue":e.movementType==="561"?"Initial stock entry":"Material movement";return <article className="rounded-xl border border-slate-800 bg-slate-900/55 p-4"><div className="flex flex-wrap justify-between gap-3"><div className="flex gap-3"><span className={`mt-0.5 rounded-lg p-2 ${positive?"bg-emerald-500/10 text-emerald-300":"bg-orange-500/10 text-orange-300"}`}>{positive?<IconArrowUp className="h-4 w-4"/>:<IconArrowDown className="h-4 w-4"/>}</span><div><p className="text-xs text-slate-500">{e.postingDate} · {e.createdTime}</p><h5 className="font-semibold">Movement {e.movementType} · {label}</h5><p className="mt-1 text-xs text-slate-400">Material document {e.materialDocument} / {e.documentYear} / {e.documentItem} · {e.sourceTransaction}</p></div></div><div className={`text-right text-sm font-semibold ${positive?"text-emerald-300":"text-orange-300"}`}><p>{signed(e.quantityDelta)} {e.unit}</p><p>{signed(e.inventoryValueDelta)} {e.currency}</p></div></div><div className="mt-3 grid gap-2 text-xs sm:grid-cols-2"><Flow title="Stock" before={e.beforeQuantity} delta={e.quantityDelta} after={e.afterQuantity} unit={e.unit}/><Flow title="Inventory value" before={e.beforeInventoryValue} delta={e.inventoryValueDelta} after={e.afterInventoryValue} unit={e.currency}/></div><div className="mt-3 flex flex-wrap gap-2 text-[11px] text-slate-400">{e.purchaseOrder&&<Tag>PO {e.purchaseOrder} / {e.purchaseOrderItem}</Tag>}{e.productionOrder&&<Tag>Production order {e.productionOrder}</Tag>}<Tag>Company {e.companyCode}</Tag><Tag>Profit center {e.profitCenter}</Tag><Tag>Business area {e.businessArea}</Tag></div>{e.accountingDocuments.map(d=><details key={`${d.accountingDocument}-${d.fiscalYear}`} className="mt-3 rounded-lg border border-slate-800 bg-slate-950/60 p-3"><summary className="cursor-pointer text-xs font-semibold"><IconBuildingBank className="mr-2 inline h-4 w-4 text-cyan-400"/>Accounting document {d.accountingDocument} · FY {d.fiscalYear} · {d.documentType} · Ledger {d.ledger}</summary><div className="mt-3 space-y-1">{d.lines.map(l=><div key={l.line} className="grid grid-cols-[70px_1fr_auto] gap-2 rounded bg-slate-900 px-3 py-2 text-xs"><span>Line {l.line}</span><span>G/L {l.glAccount} · {l.debitCredit==="S"?"Debit":"Credit"}</span><span className={(l.amount??0)>=0?"text-emerald-300":"text-orange-300"}>{signed(l.amount)} {l.currency}</span></div>)}</div></details>)}</article>}
function Box({children}:{children:React.ReactNode}){return <div className="mt-4 rounded-xl border border-slate-800 p-4 text-sm text-slate-400">{children}</div>}function Metric({label,value,icon}:{label:string;value:string;icon?:React.ReactNode}){return <div className="bg-slate-950 p-4">{icon&&<span className="text-cyan-400 [&_svg]:h-4 [&_svg]:w-4">{icon}</span>}<p className="mt-1 text-[10px] uppercase text-slate-500">{label}</p><p className="mt-1 text-lg font-semibold">{value}</p></div>}function Flow({title,before,delta,after,unit}:{title:string;before:number;delta:number|null;after:number;unit:string}){return <div className="rounded-lg bg-slate-950 p-3"><p className="text-slate-500">{title}</p><p className="mt-1 text-slate-200">{n(before)} → {n(after)} {unit} <span className="text-slate-500">· Delta {signed(delta)}</span></p></div>}function Tag({children}:{children:React.ReactNode}){return <span className="rounded border border-slate-700 px-2 py-1">{children}</span>}function n(v:number|null|undefined){return v==null?"—":String(v)}function money(v:number|null|undefined){return v==null?"—":new Intl.NumberFormat("en-IN").format(v)}function signed(v:number|null|undefined){return v==null?"—":`${v>0?"+":""}${new Intl.NumberFormat("en-IN").format(v)}`}function yn(v:boolean|null){return v==null?"Not verified":v?"Matched":"Mismatch"}
