import Graph from"graphology";import{bidirectional}from"graphology-shortest-path/unweighted";
export type Evidence="authoritative"|"deterministic"|"verified"|"heuristic"|"unresolved";export type Zone="center"|"teamcenter"|"windchill"|"sap"|"configit"|"satellite";
export type Entity={id:string;label:string;kind:string;zone:Zone;evidence:Evidence;detail:string};export type Relation={id:string,source:string,target:string,label:string,family:string,evidence:Evidence};
export const entities:Entity[]=[
{id:"focus",label:"Screwjack_002403",kind:"active investigation",zone:"center",evidence:"authoritative",detail:"Selected product context"},
{id:"tc",label:"Teamcenter",kind:"enterprise pillar",zone:"teamcenter",evidence:"authoritative",detail:"PLM source anchor"},{id:"wc",label:"Windchill",kind:"enterprise pillar",zone:"windchill",evidence:"authoritative",detail:"PLM source anchor"},{id:"sap",label:"SAP",kind:"enterprise pillar",zone:"sap",evidence:"authoritative",detail:"ERP source anchor"},{id:"cfg",label:"Configit",kind:"enterprise pillar",zone:"configit",evidence:"authoritative",detail:"Configuration source anchor"},
{id:"tc-product",label:"Teamcenter 002403/A",kind:"source record",zone:"teamcenter",evidence:"authoritative",detail:"Resolved product revision"},{id:"body",label:"Body_002409",kind:"assembly",zone:"teamcenter",evidence:"authoritative",detail:"Product structure assembly · expandable"},{id:"head",label:"Top Head_002412",kind:"assembly",zone:"teamcenter",evidence:"authoritative",detail:"Product structure assembly"},{id:"washer",label:"Washer_002405",kind:"part",zone:"teamcenter",evidence:"authoritative",detail:"Product structure part"},{id:"occ",label:"Spindle occurrence",kind:"occurrence",zone:"teamcenter",evidence:"authoritative",detail:"Independent repeated BOM occurrence"},{id:"spindle",label:"Screw Spindle_002410",kind:"part",zone:"teamcenter",evidence:"authoritative",detail:"Canonical spindle part"},
{id:"wc-record",label:"Windchill 002410 B.1",kind:"source record",zone:"windchill",evidence:"authoritative",detail:"Resolved Windchill version"},{id:"change",label:"CN-8 Spindle update",kind:"change notice",zone:"windchill",evidence:"verified",detail:"Verified change impact"},{id:"document",label:"Spindle drawing D-410",kind:"document",zone:"windchill",evidence:"authoritative",detail:"Engineering document"},
{id:"sap-mat",label:"SAP Material 002410",kind:"material",zone:"sap",evidence:"authoritative",detail:"ERP material master"},{id:"stock",label:"Stock at Plant 1000",kind:"stock",zone:"sap",evidence:"authoritative",detail:"84 units"},{id:"movement",label:"Material Document 490001",kind:"movement",zone:"sap",evidence:"authoritative",detail:"Operational document"},{id:"financial",label:"FI Document 510001",kind:"financial document",zone:"sap",evidence:"authoritative",detail:"Financial posting evidence"},{id:"sap-cluster",label:"18 additional movements",kind:"cluster summary",zone:"sap",evidence:"authoritative",detail:"18 hidden records · intentional drill-down"},
{id:"cfg-record",label:"Screwjack configuration",kind:"product model",zone:"configit",evidence:"authoritative",detail:"Resolved configuration context"},{id:"cfg-rule",label:"BODY configuration rule",kind:"configuration rule",zone:"configit",evidence:"authoritative",detail:"Product configuration logic"},
{id:"requirement",label:"R-42 Load capacity",kind:"requirement",zone:"satellite",evidence:"verified",detail:"Verified trace to spindle"},{id:"excel",label:"Excel BOM row 17",kind:"provenance",zone:"satellite",evidence:"heuristic",detail:"Heuristic source correspondence"},{id:"unresolved",label:"Unresolved supplier reference",kind:"unresolved evidence",zone:"satellite",evidence:"unresolved",detail:"Source evidence unavailable"}];
export const relations:Relation[]=[
{id:"r1",source:"focus",target:"tc",label:"resolved in",family:"resolution",evidence:"deterministic"},{id:"r2",source:"focus",target:"wc",label:"resolved in",family:"resolution",evidence:"deterministic"},{id:"r3",source:"focus",target:"sap",label:"resolved in",family:"resolution",evidence:"deterministic"},{id:"r4",source:"focus",target:"cfg",label:"resolved in",family:"resolution",evidence:"deterministic"},{id:"r5",source:"tc",target:"tc-product",label:"owns record",family:"source",evidence:"authoritative"},{id:"r6",source:"tc-product",target:"body",label:"contains",family:"structural",evidence:"authoritative"},{id:"r7",source:"tc-product",target:"head",label:"contains",family:"structural",evidence:"authoritative"},{id:"r8",source:"tc-product",target:"washer",label:"contains",family:"structural",evidence:"authoritative"},{id:"r9",source:"body",target:"occ",label:"contains occurrence",family:"occurrence",evidence:"authoritative"},{id:"r10",source:"occ",target:"spindle",label:"occurrence of",family:"occurrence",evidence:"authoritative"},{id:"r11",source:"spindle",target:"wc-record",label:"deterministic match",family:"cross-source",evidence:"deterministic"},{id:"r12",source:"wc-record",target:"change",label:"affected by",family:"change",evidence:"verified"},{id:"r13",source:"wc-record",target:"document",label:"documented by",family:"document",evidence:"authoritative"},{id:"r14",source:"spindle",target:"sap-mat",label:"represented in",family:"cross-source",evidence:"deterministic"},{id:"r15",source:"sap",target:"sap-mat",label:"owns material",family:"source",evidence:"authoritative"},{id:"r16",source:"sap-mat",target:"stock",label:"has stock",family:"sap",evidence:"authoritative"},{id:"r17",source:"sap-mat",target:"movement",label:"has movement",family:"sap",evidence:"authoritative"},{id:"r18",source:"movement",target:"financial",label:"posted through",family:"financial",evidence:"authoritative"},{id:"r19",source:"sap-mat",target:"sap-cluster",label:"more evidence",family:"cluster",evidence:"authoritative"},{id:"r20",source:"cfg",target:"cfg-record",label:"owns model",family:"source",evidence:"authoritative"},{id:"r21",source:"cfg-record",target:"cfg-rule",label:"configured by",family:"configuration",evidence:"authoritative"},{id:"r22",source:"requirement",target:"spindle",label:"satisfied by",family:"requirement",evidence:"verified"},{id:"r23",source:"washer",target:"excel",label:"heuristic match",family:"heuristic",evidence:"heuristic"},{id:"r24",source:"washer",target:"unresolved",label:"unresolved reference",family:"unresolved",evidence:"unresolved"}];
export function graphology(){const g=new Graph({multi:true,type:"directed"});entities.forEach(e=>g.addNode(e.id,e));relations.forEach(r=>g.addEdgeWithKey(r.id,r.source,r.target,r));return g}export function path(){return bidirectional(graphology(),"requirement","financial")??[]}export const stages:Record<string,string[]>={empty:["tc","wc","sap","cfg"],resolved:["focus","tc","wc","sap","cfg","tc-product","wc-record","sap-mat","cfg-record"],product:["focus","tc","wc","sap","cfg","tc-product","wc-record","sap-mat","cfg-record","body","head","washer","occ","spindle"],evidence:entities.map(e=>e.id)};
