import type { EngineeringIntelligenceInvestigationV1, IntelligenceProperty } from "../contracts/intelligence-v1";
import type { EngineeringEntity, EngineeringRelationship, EntityKind, EntitySource, InvestigationGraph, RelationshipKind } from "../domain/model";
import { canonicalEntityId, deduplicateIntelligenceEntities } from "./deduplicate-intelligence-entities";
import { immutableInvestigationGraph } from "./immutable-investigation-graph";
import { validateIntelligenceInput } from "./validate-intelligence-input";

const sourceOf=(value?:string):EntitySource=>value==="teamcenter"||value==="windchill"||value==="sap"||value==="configit"?value:"platform";
const primitive=(value:unknown):string|number|boolean|undefined=>{
 if(value===null||value===undefined)return undefined;
 if(typeof value==="string"||typeof value==="number"||typeof value==="boolean")return value;
 if(Array.isArray(value))return value.map(item=>primitive(item)).filter(item=>item!==undefined).join(", ");
 if(typeof value==="object"){
  const record=value as Record<string,unknown>;
  for(const key of ["displayValue","value","label","text","name","formattedValue"]){const resolved=primitive(record[key]);if(resolved!==undefined&&String(resolved).trim())return resolved;}
 }
 return undefined;
};
const scalar=(value:IntelligenceProperty):string|number|boolean|undefined=>primitive(value.text)??primitive(value.number)??primitive(value.boolean)??primitive(value.timestamp)??primitive(value.reference)??primitive(value.items);
const attributes=(properties:Record<string,IntelligenceProperty>)=>Object.fromEntries(Object.entries(properties).sort(([a],[b])=>a.localeCompare(b)).flatMap(([key,value])=>{const resolved=scalar(value);return resolved===undefined?[]:[[key,resolved]]}));
const confidence=(value?:string)=>value==="verified"?1:value==="deterministic"?.9:value==="probable"?.72:value==="ambiguous"?.45:value==="unresolved"?.2:undefined;
const kind=(value:string):EntityKind=>value as EntityKind;
const relationshipKind=(value:string):RelationshipKind=>value as RelationshipKind;

export function buildIntelligenceInvestigation(input:EngineeringIntelligenceInvestigationV1):InvestigationGraph{
 validateIntelligenceInput(input);
 const deduplicated=deduplicateIntelligenceEntities(input);
 const evidenceById=Object.fromEntries(input.evidence.map(item=>[item.id,item]));
 const clustersByEntity=new Map<string,string[]>();
 for(const cluster of input.identityClusters)for(const entityId of cluster.entityIds)clustersByEntity.set(entityId,[...(clustersByEntity.get(entityId)??[]),cluster.id]);
 const subjectSourceIds=input.sources.map(item=>item.entityId).filter(Boolean);
 const subject:EngineeringEntity={id:input.subject.id,sourceNodeId:input.subject.preferredProductId??input.subject.id,source:"unified",name:input.subject.displayName,kind:"identity",level:0,attributes:{"Preferred product ID":input.subject.preferredProductId??"","Candidate IDs":input.subject.candidateIds.join(", "),"Source coverage":input.summary.availableSourceCount,"Partial sources":input.summary.partialSourceCount,"Investigation status":input.summary.status,"Evidence completeness":input.sources.length?`${input.summary.availableSourceCount}/${input.sources.length} sources available`:"not observed","Contract version":input.contractVersion},provenance:{sourceLabel:input.subject.provenance.provider,nativeId:input.subject.provenance.nativeId,capturedAt:input.subject.provenance.observedAt},representationSources:input.sources.map(x=>x.source).filter((x):x is "teamcenter"|"windchill"|"sap"|"configit"=>x==="teamcenter"||x==="windchill"||x==="sap"||x==="configit").sort(),canonicalKind:"part",assertion:"fact",temporal:{assembledAt:input.subject.temporal.assembledAt,capturedAt:input.subject.temporal.capturedAt,freshness:input.subject.temporal.freshness},identityClusterIds:clustersByEntity.get(input.subject.id)??[]};
 const levels=new Map<string,number>([[subject.id,0]]);for(const id of subjectSourceIds)levels.set(id,1);
 const entities:EngineeringEntity[]=[subject,...deduplicated.entities.map(entity=>({id:entity.id,sourceNodeId:entity.provenance.nativeId??entity.id,source:sourceOf(entity.provenance.source),name:entity.displayName,kind:kind(entity.kind),level:levels.get(entity.id)??1,attributes:attributes(entity.properties),provenance:{sourceLabel:entity.provenance.provider,nativeId:entity.provenance.nativeId,capturedAt:entity.provenance.observedAt},canonicalKind:entity.kind,assertion:entity.assertion,sourceStatus:input.sources.find(x=>x.entityId===entity.id)?.status,temporal:{assembledAt:entity.temporal.assembledAt,capturedAt:entity.temporal.capturedAt,freshness:entity.temporal.freshness},identityClusterIds:clustersByEntity.get(entity.id)??[]}))];
 const entityIds=new Set(entities.map(x=>x.id));
 const relationships:EngineeringRelationship[]=input.relationships.map(r=>{const from=canonicalEntityId(r.sourceEntityId,deduplicated.aliases),to=canonicalEntityId(r.targetEntityId,deduplicated.aliases);return {...r,sourceEntityId:from,targetEntityId:to}}).filter(r=>entityIds.has(r.sourceEntityId)&&entityIds.has(r.targetEntityId)).map(r=>({id:r.id,from:r.sourceEntityId,to:r.targetEntityId,kind:relationshipKind(r.kind),confidence:confidence(r.confidence),verified:r.confidence==="verified",label:r.kind.replaceAll("-"," "),evidence:r.evidenceIds.map(id=>evidenceById[id]).filter(Boolean).map(item=>({sourceLabel:item.source,reason:item.summary,nativeId:item.provenance.nativeId,capturedAt:item.provenance.observedAt})),family:r.family,assertion:r.assertion,evidenceIds:[...r.evidenceIds].sort()}));
 for(const finding of [...input.findings].sort((a,b)=>a.id.localeCompare(b.id))){const findingId=`entity:${finding.id}`;entities.push({id:findingId,sourceNodeId:finding.id,source:"platform",name:finding.title,kind:"finding",level:1,attributes:{Summary:finding.summary},provenance:{sourceLabel:finding.provenance.provider,nativeId:finding.provenance.nativeId,capturedAt:finding.provenance.observedAt},canonicalKind:"finding",assertion:"finding",temporal:{assembledAt:finding.temporal.assembledAt,capturedAt:finding.temporal.capturedAt,freshness:finding.temporal.freshness},evidenceIds:[...finding.evidenceIds].sort()});for(const rawTarget of [...finding.subjectEntityIds].sort()){const target=canonicalEntityId(rawTarget,deduplicated.aliases);if(entityIds.has(target)){relationships.push({id:`rel:${finding.id}:${target}`,from:findingId,to:target,kind:"supported-by",label:"supported by",evidence:finding.evidenceIds.map(id=>evidenceById[id]).filter(Boolean).map(item=>({sourceLabel:item.source,reason:item.summary,capturedAt:item.provenance.observedAt})),family:"evidence",assertion:"finding",evidenceIds:[...finding.evidenceIds].sort()});}}}
 const sortedEntities=entities.sort((a,b)=>a.id.localeCompare(b.id));const sortedRelationships=relationships.sort((a,b)=>a.id.localeCompare(b.id));
 return immutableInvestigationGraph({entities:sortedEntities,relationships:sortedRelationships,roots:[subject.id],byId:Object.fromEntries(sortedEntities.map(x=>[x.id,x])),relationshipById:Object.fromEntries(sortedRelationships.map(x=>[x.id,x])),metadata:{investigationId:input.investigationId,contractVersion:input.contractVersion,sourceStatuses:Object.fromEntries(input.sources.map(x=>[x.source,x.status]).sort(([a],[b])=>a.localeCompare(b))),identityClusters:input.identityClusters.map(c=>({id:c.id,entityIds:[...c.entityIds].sort(),confidence:c.confidence,reasons:[...c.reasons].sort()})).sort((a,b)=>a.id.localeCompare(b.id)),evidence:Object.fromEntries(input.evidence.map(e=>[e.id,{id:e.id,kind:e.kind,summary:e.summary,source:e.source}] as const).sort(([a],[b])=>a.localeCompare(b))),findings:input.findings.map(f=>({id:f.id,kind:f.kind,title:f.title,summary:f.summary,subjectEntityIds:[...f.subjectEntityIds].sort(),evidenceIds:[...f.evidenceIds].sort()})).sort((a,b)=>a.id.localeCompare(b.id)),entityAliases:deduplicated.aliases}});
}
