import type { LatticeHandoff } from "../contracts/handoff";
import type { EngineeringEntity,EngineeringRelationship,InvestigationGraph } from "../domain/model";
type Attr=Record<string,string|number|boolean>;
const qty=(a:Attr)=>{const v=a.Qty??a.Quantity;return typeof v==="string"||typeof v==="number"?v:undefined};
const normalize=(v:unknown)=>String(v??"").toLowerCase().replace(/[^a-z0-9]/g,"");
const cleanSubject=(value:string)=>{const v=value.trim();if(!v)return"Engineering investigation";return v.replace(/_/g," ").replace(/^./,c=>c.toUpperCase())};
export function buildInvestigation(handoff:LatticeHandoff):InvestigationGraph{
 const entities:EngineeringEntity[]=[],relationships:EngineeringRelationship[]=[],sourceRoots:string[]=[],matches=new Map<string,{id:string;source:string;verified:boolean}[]>();
 handoff.sources.forEach((source,sourceIndex)=>{const visit=(node:typeof source.root,level:number,parent?:string,path:number[]=[sourceIndex])=>{const id=`${source.source}:${path.join(".")}:${node.id}`,attributes=node.attributes??{},entity:EngineeringEntity={id,sourceNodeId:node.id,source:source.source,name:node.name,kind:node.children?.length?"assembly":"component",level:level+1,attributes,provenance:{sourceLabel:source.label,nativeId:source.nativeId,capturedAt:source.capturedAt}};entities.push(entity);if(!parent)sourceRoots.push(id);else relationships.push({id:`contains:${parent}:${id}`,from:parent,to:id,kind:"contains",quantity:qty(attributes),label:qty(attributes)?`Contains Â· Qty ${qty(attributes)}`:"Contains",evidence:[{sourceLabel:source.label,reason:"Direct BOM parent-child occurrence",nativeId:source.nativeId,capturedAt:source.capturedAt}]});const native=String(attributes["Item ID"]??attributes["Part Number"]??attributes.Number??"");const key=normalize(native||node.name);if(key)matches.set(key,[...(matches.get(key)??[]),{id,source:source.source,verified:Boolean(native)}]);node.children?.forEach((child,index)=>visit(child,level+1,id,[...path,index]))};visit(source.root,0)});
 const subjectId=`subject:${normalize(handoff.subjectLabel)||handoff.handoffId}`,sources=handoff.sources.map(item=>item.source).filter((item):item is Exclude<typeof item,"excel">=>item!=="excel");
 entities.push({id:subjectId,sourceNodeId:handoff.subjectLabel,source:"unified",name:cleanSubject(handoff.subjectLabel),kind:"identity",level:0,attributes:{"Selected representations":sourceRoots.length,"Investigation query":handoff.subjectLabel},provenance:{sourceLabel:"Investigation subject",capturedAt:handoff.createdAt},representationSources:sources});
 sourceRoots.forEach(rootId=>{const root=entities.find(item=>item.id===rootId)!;const idEvidence=normalize(root.provenance.nativeId),query=normalize(handoff.subjectLabel),name=normalize(root.name),verified=Boolean(query&&(idEvidence.includes(query)||name.includes(query)||query.includes(name)));relationships.push({id:`represented:${subjectId}:${rootId}`,from:subjectId,to:rootId,kind:"represented-by",confidence:verified?1:.72,verified,label:verified?`Represented in ${root.provenance.sourceLabel} Â· Verified`:`Selected from ${root.provenance.sourceLabel} Â· Review`,evidence:[{sourceLabel:"Investigation selection",reason:verified?"Search subject agrees with the source root":"Selected by the user; identity review remains available"}]})});
 for(const group of matches.values()){const per=[...new Map(group.map(x=>[x.source,x])).values()],first=per[0];if(!first)continue;for(let i=1;i<per.length;i++){const other=per[i];if(!other)continue;const verified=first.verified&&other.verified;relationships.push({id:`corresponds:${first.id}:${other.id}`,from:first.id,to:other.id,kind:"corresponds-to",confidence:verified?1:.72,verified,label:verified?"Same part Â· Verified":"Likely same part Â· 72%",evidence:[{sourceLabel:"Cross-source correspondence",reason:verified?"Verified identifier match":"Normalized-name match"}]})}}
 const roots=[subjectId];return{entities,relationships,roots,byId:Object.fromEntries(entities.map(e=>[e.id,e])),relationshipById:Object.fromEntries(relationships.map(r=>[r.id,r]))};
}


