import type { LatticeSource, SourceCapability } from "./contracts";
export const LATTICE_SOURCES:LatticeSource[]=["teamcenter","windchill","sap","configit"];
export const SOURCE_CAPABILITIES:Record<LatticeSource,SourceCapability>={
teamcenter:{source:"teamcenter",readiness:"ready",discoveryModes:["exact-id","name","number","contextual-handoff"],supportsExactId:true,supportsNameSearch:true,supportsNumberSearch:true,supportsStructureExtraction:true,supportsRevisionContext:true,supportsChangeContext:false,supportsRequirements:true,supportsOperationalImpact:false,supportsConfigurationContext:false,supportsCancellation:true,supportsRetry:true,supportsPartialSuccess:true,resultLimit:10,timeoutPolicy:{defaultMs:30000,maximumMs:120000,sourceLevel:true},knownLimitations:["Teamcenter discovery uses the authoritative name-or-ID extraction resolver and is serialized by the connector runtime."]},
windchill:{source:"windchill",readiness:"ready",discoveryModes:["exact-id","name","number","contextual-handoff"],supportsExactId:true,supportsNameSearch:true,supportsNumberSearch:true,supportsStructureExtraction:true,supportsRevisionContext:true,supportsChangeContext:true,supportsRequirements:true,supportsOperationalImpact:false,supportsConfigurationContext:false,supportsCancellation:true,supportsRetry:true,supportsPartialSuccess:true,resultLimit:10,timeoutPolicy:{defaultMs:30000,maximumMs:300000,sourceLevel:true},knownLimitations:["Availability depends on the Windchill extractor runtime and connector authentication."]},
sap:{source:"sap",readiness:"ready",discoveryModes:["exact-id","name","number","material-catalog","contextual-handoff"],supportsExactId:true,supportsNameSearch:true,supportsNumberSearch:true,supportsStructureExtraction:true,supportsRevisionContext:false,supportsChangeContext:false,supportsRequirements:false,supportsOperationalImpact:true,supportsConfigurationContext:false,supportsCancellation:true,supportsRetry:true,supportsPartialSuccess:true,resultLimit:10,timeoutPolicy:{defaultMs:25000,maximumMs:180000,sourceLevel:true},knownLimitations:["Discovery uses the latest available SAP material catalogue; operational evidence may return partial success."]},
configit:{source:"configit",readiness:"ready",discoveryModes:["exact-id","name","product-id","contextual-handoff"],supportsExactId:true,supportsNameSearch:true,supportsNumberSearch:false,supportsStructureExtraction:true,supportsRevisionContext:false,supportsChangeContext:false,supportsRequirements:false,supportsOperationalImpact:false,supportsConfigurationContext:true,supportsCancellation:true,supportsRetry:true,supportsPartialSuccess:true,resultLimit:10,timeoutPolicy:{defaultMs:30000,maximumMs:300000,sourceLevel:true},knownLimitations:["Package-path discovery and structure extraction require live Configit connectivity and credentials."]}
};
export const SOURCE_LABELS:Record<LatticeSource,string>={teamcenter:"Teamcenter",windchill:"Windchill",sap:"SAP",configit:"Configit"};
export const SOURCE_TONES:Record<LatticeSource,string>={teamcenter:"cyan",windchill:"violet",sap:"emerald",configit:"fuchsia"};


