"use client";
import { useEffect, useMemo, useReducer, useRef, useState } from "react";
import { IconPlayerStop, IconRefresh, IconSearch, IconTopologyStar3 } from "@tabler/icons-react";
import type { LatticeSource, NormalizedSearchResult, SourceSearchOutcome } from "./contracts";
import { LATTICE_SOURCES, SOURCE_LABELS } from "./capability-matrix";
import { FederatedSearchOrchestrator } from "./federated-search-orchestrator";
import { buildCorrespondenceCandidates } from "./identity-resolution";
import { discoveryReducer, initialDiscoveryState } from "./discovery-reducer";

export function DiscoveryWorkspace({onInvestigate,recent}:{onInvestigate:(results:NormalizedSearchResult[])=>Promise<void>;recent:{id:string;label:string}[]}){
 const orchestrator=useMemo(()=>new FederatedSearchOrchestrator(),[]),[state,dispatch]=useReducer(discoveryReducer,initialDiscoveryState),[starting,setStarting]=useState(false),input=useRef<HTMLInputElement>(null);
 useEffect(()=>orchestrator.subscribe(snapshot=>dispatch({type:"snapshot",value:snapshot})),[orchestrator]);useEffect(()=>()=>orchestrator.dispose(),[orchestrator]);
 const results=useMemo(()=>state.snapshot?Object.values(state.snapshot.outcomes).flatMap(item=>item.results):[],[state.snapshot]);useEffect(()=>dispatch({type:"correspondences",value:buildCorrespondenceCandidates(results)}),[results]);
 const selected=results.filter(item=>state.selectedResultIds.has(item.resultId));
 const submit=async()=>{if(!state.query.trim())return;await orchestrator.search(state.query);};
 return <main className="min-h-[calc(100vh-64px)] bg-[#050914] px-4 py-10 text-white sm:px-8"><section className="mx-auto max-w-6xl"><div className="mx-auto max-w-3xl text-center"><p className="text-[11px] font-bold uppercase tracking-[.2em] text-cyan-400">Federated engineering intelligence</p><h1 className="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">Start with the engineering identifier</h1><p className="mx-auto mt-3 max-w-2xl text-sm leading-6 text-slate-400">Search Teamcenter, Windchill, SAP, and Configit once. Lattice preserves each source identity and lets you investigate with partial coverage.</p><form className="mt-7 flex rounded-2xl border border-slate-700 bg-slate-950/90 p-2 shadow-[0_20px_60px_-35px_rgba(34,211,238,.55)] focus-within:border-cyan-500" onSubmit={event=>{event.preventDefault();void submit();}}><IconSearch className="ml-3 mt-3 h-5 w-5 text-slate-500"/><input ref={input} value={state.query} onChange={event=>dispatch({type:"query",value:event.target.value})} placeholder="Product name, part number, material ID, requirement or change ID" className="h-11 min-w-0 flex-1 bg-transparent px-3 text-sm outline-none placeholder:text-slate-600"/><button disabled={!state.query.trim()||Boolean(state.snapshot?.active)} className="rounded-xl bg-cyan-600 px-5 text-sm font-semibold disabled:opacity-45">Investigate</button>{state.snapshot?.active?<button type="button" onClick={()=>orchestrator.cancel("user")} aria-label="Cancel search" className="ml-2 rounded-xl border border-slate-700 px-3"><IconPlayerStop className="h-4 w-4"/></button>:null}</form></div>
 <div className="mt-8 divide-y divide-slate-800 overflow-hidden rounded-2xl border border-slate-800 bg-slate-950/65">{LATTICE_SOURCES.map(source=><SourceRow key={source} source={source} outcome={state.snapshot?.outcomes[source]??null} selected={state.selectedResultIds} onSelect={result=>dispatch({type:"select",result})} onRetry={()=>void orchestrator.retry(source)}/>)}</div>
 {state.snapshot&&!state.snapshot.active?<section className="mt-5 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-800 bg-slate-950/60 px-4 py-3"><div><p className="text-sm font-semibold">{selected.length?`${selected.length} source record${selected.length===1?"":"s"} selected`:"Select a source record to continue"}</p><p className="mt-1 text-xs text-slate-500">Probable and ambiguous records are never merged automatically.</p></div><button disabled={!selected.length||starting} onClick={async()=>{setStarting(true);try{await onInvestigate(selected);}finally{setStarting(false);}}} className="inline-flex h-10 items-center gap-2 rounded-lg bg-cyan-600 px-4 text-sm font-semibold disabled:opacity-45"><IconTopologyStar3 className="h-4 w-4"/>{starting?"Resolving structure...":"Start investigation"}</button></section>:null}
 {recent.length?<section className="mt-8"><h2 className="text-xs font-semibold uppercase tracking-[.15em] text-slate-500">Restorable investigations</h2><div className="mt-3 flex flex-wrap gap-2">{recent.map(item=><a key={item.id} href={`/lattice?investigation=${encodeURIComponent(item.id)}`} className="rounded-lg border border-slate-800 px-3 py-2 text-sm text-slate-300">{item.label}</a>)}</div></section>:null}<p className="sr-only" aria-live="polite">{state.announcement}</p></section></main>;
}
function SourceRow({source,outcome,selected,onSelect,onRetry}:{source:LatticeSource;outcome:SourceSearchOutcome|null;selected:Set<string>;onSelect:(result:NormalizedSearchResult)=>void;onRetry:()=>void}){const capability=outcome?.capabilitySnapshot;const tone={teamcenter:"text-cyan-300",windchill:"text-violet-300",sap:"text-emerald-300",configit:"text-fuchsia-300"}[source];const status=outcome?.status??"idle";return <section className="grid gap-3 px-4 py-4 md:grid-cols-[180px_1fr]"><div><p className={`text-sm font-semibold ${tone}`}>{SOURCE_LABELS[source]}</p><p className="mt-1 text-xs text-slate-500">{capability?capability.readiness==="capability-limited"?capability.knownLimitations[0]:"Connector ready for its supported discovery modes.":source==="teamcenter"?"Exact Item ID discovery available":source==="configit"?"Product ID discovery available":source==="windchill"?"Live name and number search ready":"Material catalogue search ready"}</p></div><div><div className="flex items-center justify-between"><span className="text-[10px] font-bold uppercase tracking-[.14em] text-slate-500">{status.replaceAll("-"," ")}</span>{["failed","timed-out"].includes(status)?<button onClick={onRetry} className="inline-flex items-center gap-1 text-xs text-cyan-300"><IconRefresh className="h-3.5 w-3.5"/>Retry</button>:null}</div>{outcome?.error?<p className="mt-2 text-xs text-rose-300">{outcome.error.message}</p>:null}{outcome?.warning?<p className="mt-2 text-xs text-amber-300/80">{outcome.warning}</p>:null}<div className="mt-2 grid gap-2">{(outcome?.results??[]).map((result:NormalizedSearchResult)=><button key={result.resultId} onClick={()=>onSelect(result)} className={`rounded-xl border p-3 text-left transition ${selected.has(result.resultId)?"border-cyan-400 bg-cyan-500/10":"border-slate-800 bg-slate-900/55 hover:border-slate-700"}`}><div className="flex items-start justify-between gap-3"><div><strong className="text-sm">{result.displayName}</strong><p className="mt-1 text-xs text-slate-500">{result.nativeId}{result.revision?` · Rev ${result.revision}`:""}</p></div><span className="rounded-full border border-slate-700 px-2 py-1 text-[9px] uppercase text-slate-400">{result.matchCategory.replaceAll("-"," ")}</span></div><p className="mt-2 text-xs text-slate-400">{result.matchReason}</p></button>)}</div>{status==="empty"?<p className="mt-2 text-xs text-slate-500">No matching source records.</p>:null}</div></section>}
