import type { LatticeHandoff } from "../contracts/handoff";
import type { InvestigationGraph, InvestigationSelection } from "../domain/model";
import type { CorrespondenceCandidate, FederatedSearchSnapshot, LatticeSource, NormalizedSearchResult, SourceSearchOutcome } from "./contracts";
export type InvestigationEntryMode="direct-discovery"|"contextual-handoff"|"restored-investigation";
export interface CanonicalSourceRecord{recordId:string;source:LatticeSource;nativeId:string;displayName:string;resultId?:string;selected:boolean;capabilities:string[];metadata:Record<string,string|number|boolean|null>;}
export interface CanonicalInvestigation{
  investigationId:string;schemaVersion:3;entryMode:InvestigationEntryMode;query?:string;
  rootContext:{label:string;primarySource?:LatticeSource;primaryNativeId?:string};sourceRecords:CanonicalSourceRecord[];
  correspondenceRecords:CorrespondenceCandidate[];entities:InvestigationGraph["entities"];relationships:InvestigationGraph["relationships"];
  sourceOutcomes:Partial<Record<LatticeSource,SourceSearchOutcome>>;evidenceCoverage:Record<string,"available"|"partial"|"unavailable"|"not-requested">;
  selection:InvestigationSelection;expansion:string[];filters:{sources:LatticeSource[];relationships:string[]};activePath:string[];viewport:{x:number;y:number;zoom:number};createdAt:string;updatedAt:string;
}
export function createDirectInvestigation(input:{selected:NormalizedSearchResult[];correspondences:CorrespondenceCandidate[];snapshot:FederatedSearchSnapshot;graph:InvestigationGraph;}):CanonicalInvestigation{const primary=input.selected[0],timestamp=new Date().toISOString();return{investigationId:`lattice-${crypto.randomUUID()}`,schemaVersion:3,entryMode:"direct-discovery",query:input.snapshot.request.query,rootContext:{label:primary.displayName,primarySource:primary.source,primaryNativeId:primary.nativeId},sourceRecords:input.selected.map(result=>({recordId:`${result.source}:${result.nativeId}`,source:result.source,nativeId:result.nativeId,displayName:result.displayName,resultId:result.resultId,selected:true,capabilities:result.capabilityHints,metadata:result.sourceMetadata})),correspondenceRecords:input.correspondences,entities:input.graph.entities,relationships:input.graph.relationships,sourceOutcomes:input.snapshot.outcomes,evidenceCoverage:{structure:"available",requirements:"not-requested",changes:"not-requested",operations:"not-requested",configuration:"not-requested"},selection:{type:"none"},expansion:input.graph.roots,filters:{sources:[...new Set(input.graph.entities.map(item=>item.source).filter((item):item is LatticeSource=>item!=="excel"))],relationships:["contains","corresponds-to"]},activePath:[],viewport:{x:0,y:0,zoom:1},createdAt:timestamp,updatedAt:timestamp};}
export function handoffInvestigationShell(handoff:LatticeHandoff,graph:InvestigationGraph):CanonicalInvestigation{const timestamp=new Date().toISOString();return{investigationId:`lattice-${handoff.handoffId}`,schemaVersion:3,entryMode:"contextual-handoff",rootContext:{label:handoff.subjectLabel,primarySource:handoff.sources[0]?.source as LatticeSource|undefined,primaryNativeId:handoff.sources[0]?.nativeId},sourceRecords:handoff.sources.filter(item=>item.source!=="excel").map(item=>({recordId:`${item.source}:${item.nativeId??item.root.id}`,source:item.source as LatticeSource,nativeId:item.nativeId??item.root.id,displayName:item.root.name,selected:true,capabilities:[],metadata:{}})),correspondenceRecords:[],entities:graph.entities,relationships:graph.relationships,sourceOutcomes:{},evidenceCoverage:{structure:"available",requirements:"not-requested",changes:"not-requested",operations:"not-requested",configuration:"not-requested"},selection:{type:"none"},expansion:graph.roots,filters:{sources:handoff.sources.map(item=>item.source).filter((item):item is LatticeSource=>item!=="excel"),relationships:["contains","corresponds-to"]},activePath:[],viewport:{x:0,y:0,zoom:1},createdAt:timestamp,updatedAt:timestamp};}
