import type { TreeNodeData } from "@/types/bom-comparison";
import { getConfigitRoot,getTeamcenterRoot,getWindchillRoot } from "@/components/BomStreamViewer";
import type { LatticeSource,NormalizedSearchResult } from "./contracts";
const API_BASE=process.env.NEXT_PUBLIC_API_URL||"http://localhost:5212/api";
const policy:Record<LatticeSource,{timeoutMs:number;pollMs:number}>={sap:{timeoutMs:330000,pollMs:2200},teamcenter:{timeoutMs:330000,pollMs:1800},windchill:{timeoutMs:300000,pollMs:0},configit:{timeoutMs:180000,pollMs:0}};
export type ResolutionState="queued"|"starting"|"extracting"|"ready"|"partial"|"failed"|"timed-out"|"cancelled";
export type ResolutionUpdate={resultId:string;source:LatticeSource;nativeId:string;state:ResolutionState;message:string;progressPercent?:number;jobId?:string;updatedAt:string};
export type ResolvedStructure={root:TreeNodeData;warning?:string;jobId?:string;state:Extract<ResolutionState,"ready"|"partial"|"failed"|"timed-out"|"cancelled">};
const update=(result:NormalizedSearchResult,state:ResolutionState,message:string,extra:Partial<ResolutionUpdate>,notify?:(value:ResolutionUpdate)=>void)=>notify?.({resultId:result.resultId,source:result.source,nativeId:result.nativeId,state,message,updatedAt:new Date().toISOString(),...extra});
const sleep=(ms:number,signal:AbortSignal)=>new Promise<void>((resolve,reject)=>{const id=window.setTimeout(resolve,ms);signal.addEventListener("abort",()=>{window.clearTimeout(id);reject(new DOMException("Cancelled","AbortError"))},{once:true})});
function fallback(result:NormalizedSearchResult,state:ResolutionState,message:string):TreeNodeData{return{id:`${result.source}:${result.nativeId}`,name:result.displayName,attributes:{"Item ID":result.nativeId,"Resolution Status":state,"Resolution Message":message},children:[]}}
function record(value:unknown){return value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:null}
function sapNode(value:unknown,path:string):TreeNodeData{const node=record(value)??{},material=String(node.itemId??node.id??path),children=Array.isArray(node.children)?node.children:[];return{id:`${path}:${material}`,name:String(node.name??material),attributes:{"Item ID":material,...(typeof node.qty==="string"?{Qty:node.qty}:{})},children:children.map((child,index)=>sapNode(child,`${path}.${index}`))}}
function sapRoot(payload:unknown){const body=record(payload),inner=record(body?.payload)??body,final=record(inner?.finalBom)??inner,root=record(final?.bomRoot)??record(final?.bomRootNode);return root?sapNode(root,"sap-root"):null}
function requestSignal(signal:AbortSignal,timeoutMs:number){return AbortSignal.any([signal,AbortSignal.timeout(timeoutMs)])}
function metadata(result:NormalizedSearchResult,key:string){const value=result.sourceMetadata[key];return typeof value==="string"&&value.trim()?value.trim():undefined}
async function startPipeline(result:NormalizedSearchResult,signal:AbortSignal,notify?:(value:ResolutionUpdate)=>void){const body=result.source==="sap"?{kind:"sap",materialId:result.nativeId,materialQuery:result.displayName,plant:metadata(result,"plant")??"1001",includeSapBusinessImpact:true}:{kind:"teamcenter",teamcenterItemId:result.nativeId};update(result,"starting",`Starting ${result.source} extraction.`,{},notify);const response=await fetch(`${API_BASE}/pipeline/start`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body),signal});if(!response.ok)throw new Error(`${result.source} structure request could not start (${response.status}).`);const payload=await response.json() as {jobId?:string};if(!payload.jobId)throw new Error("Pipeline did not return a job ID.");return payload.jobId}
function monitorProgress(result:NormalizedSearchResult,jobId:string,signal:AbortSignal,notify?:(value:ResolutionUpdate)=>void){return new Promise<{terminal?:"complete"|"error";message?:string}>((resolve)=>{let settled=false;const source=new EventSource(`${API_BASE}/pipeline/progress/${encodeURIComponent(jobId)}`),finish=(value:{terminal?:"complete"|"error";message?:string})=>{if(settled)return;settled=true;source.close();resolve(value)},abort=()=>finish({message:"Cancelled"});signal.addEventListener("abort",abort,{once:true});source.onmessage=event=>{try{const progress=JSON.parse(event.data) as {status?:string;phase?:string;progressPercent?:number;message?:string;error?:string};update(result,"extracting",progress.message??`Extracting from ${result.source}.`,{jobId,progressPercent:progress.progressPercent},notify);if(progress.status==="error"||progress.error)finish({terminal:"error",message:progress.error??progress.message});else if(progress.status==="complete"||progress.progressPercent===100)finish({terminal:"complete",message:progress.message})}catch{}};source.onerror=()=>finish({message:"Progress stream unavailable; continuing with result polling."});window.setTimeout(()=>finish({message:"Progress monitoring switched to result polling."}),Math.min(policy[result.source].timeoutMs,300000))})}
async function pipeline(result:NormalizedSearchResult,signal:AbortSignal,notify?:(value:ResolutionUpdate)=>void){
 const jobId=await startPipeline(result,signal,notify),started=Date.now();void monitorProgress(result,jobId,signal,notify);let misses=0;
 while(Date.now()-started<policy[result.source].timeoutMs){
  if(signal.aborted)throw new DOMException("Cancelled","AbortError");
  const bom=await fetch(`${API_BASE}/pipeline/bom/${encodeURIComponent(jobId)}`,{cache:"no-store",signal});
  if(bom.ok)return{payload:await bom.json(),jobId,operational:false};
  if(result.source==="sap"){
   const operational=await fetch(`${API_BASE}/pipeline/sap-operational-impact/${encodeURIComponent(jobId)}`,{cache:"no-store",signal});
   if(operational.ok)return{payload:null,jobId,operational:true};
   const statusResponse=await fetch(`${API_BASE}/pipeline/status/${encodeURIComponent(jobId)}`,{cache:"no-store",signal});
   if(statusResponse.ok){const status=await statusResponse.json() as {terminal?:boolean;status?:string;error?:string};if(status.terminal){if(String(status.status).startsWith("failed"))throw new Error(status.error||"SAP extraction failed.");throw new Error("SAP completed without BOM or operational intelligence.")}}
  }
  if(bom.status!==404&&bom.status!==202){if(bom.status>=500&&misses++<3){await sleep(Math.min(8000,1000*2**misses),signal);continue}throw new Error(`${result.source} structure request failed (${bom.status}).`)}
  update(result,"extracting",misses?`Waiting for ${result.source}; retrying result retrieval.`:`${result.source} extraction is still running.`,{jobId},notify);await sleep(policy[result.source].pollMs,signal)
 }
 throw new DOMException(`${result.source} structure resolution exceeded ${Math.round(policy[result.source].timeoutMs/1000)} seconds. The backend job may still be running.`,"TimeoutError")
}
export async function resolveSelectedStructure(result:NormalizedSearchResult,signal:AbortSignal,notify?:(value:ResolutionUpdate)=>void):Promise<ResolvedStructure>{try{update(result,"extracting",`Resolving ${result.displayName}.`,{},notify);if(result.source==="windchill"){const response=await fetch(`/api/bom-windchill?partId=${encodeURIComponent(result.nativeId)}`,{cache:"no-store",signal:requestSignal(signal,policy.windchill.timeoutMs)});if(!response.ok)throw new Error(`Windchill extraction failed (${response.status}).`);const root=getWindchillRoot(await response.json());if(!root)throw new Error("Windchill returned no usable structure.");update(result,"ready","Windchill structure ready.",{progressPercent:100},notify);return{root,state:"ready"}}if(result.source==="configit"){const packagePath=metadata(result,"resolvedPackagePath")??metadata(result,"packagePath")??metadata(result,"configuration")??metadata(result,"logicalPackagePath"),query=new URLSearchParams();if(packagePath)query.set("packagePath",packagePath);else query.set("productId",result.nativeId);query.set("productIdOverride",result.nativeId);const response=await fetch(`/api/bom-configit?${query}`,{cache:"no-store",signal:requestSignal(signal,policy.configit.timeoutMs)});if(!response.ok)throw new Error(`Configit solve failed (${response.status}).`);const root=getConfigitRoot(await response.json());if(!root)throw new Error("Configit returned no usable structure.");update(result,"ready","Configit structure ready.",{progressPercent:100},notify);return{root,state:"ready"}}const {payload,jobId,operational}=await pipeline(result,signal,notify),root=result.source==="sap"?sapRoot(payload):getTeamcenterRoot(payload);
if(result.source==="sap"&&operational){const message="SAP operational intelligence is ready; no SAP BOM was available.";update(result,"partial",message,{jobId,progressPercent:100},notify);return{root:fallback(result,"partial",message),warning:message,jobId,state:"partial"}}if(!root){const message=`${result.source} completed without a usable structure.`;update(result,"partial",message,{jobId,progressPercent:100},notify);return{root:fallback(result,"partial",message),warning:message,jobId,state:"partial"}}update(result,"ready",`${result.source} structure ready.`,{jobId,progressPercent:100},notify);return{root,jobId,state:"ready"}}catch(cause){const aborted=cause instanceof DOMException&&cause.name==="AbortError",timedOut=cause instanceof DOMException&&cause.name==="TimeoutError",state=aborted?"cancelled":timedOut?"timed-out":"failed",message=cause instanceof Error?cause.message:"Structure is temporarily unavailable.";update(result,state,message,{},notify);return{root:fallback(result,state,message),warning:message,state}}}
