import type { TreeNodeData } from "@/types/bom-comparison";
import { getConfigitRoot, getTeamcenterRoot, getWindchillRoot } from "@/components/BomStreamViewer";
import type { NormalizedSearchResult } from "./contracts";
const API_BASE=process.env.NEXT_PUBLIC_API_URL||"http://localhost:5212/api";
function fallback(result:NormalizedSearchResult):TreeNodeData{return{id:`${result.source}:${result.nativeId}`,name:result.displayName,attributes:{"Item ID":result.nativeId,"Resolution Status":"Structure pending"},children:[]};}
function record(value:unknown){return value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:null;}
function sapNode(value:unknown,path:string):TreeNodeData{const node=record(value)??{},material=String(node.itemId??node.id??path),children=Array.isArray(node.children)?node.children:[];return{id:`${path}:${material}`,name:String(node.name??material),attributes:{"Item ID":material,...(typeof node.qty==="string"?{Qty:node.qty}:{})},children:children.map((child,index)=>sapNode(child,`${path}.${index}`))};}
function sapRoot(payload:unknown){const body=record(payload),inner=record(body?.payload)??body,final=record(inner?.finalBom)??inner,root=record(final?.bomRoot)??record(final?.bomRootNode);return root?sapNode(root,"sap-root"):null;}
async function pipeline(result:NormalizedSearchResult,signal:AbortSignal){const kind=result.source==="sap"?"sap":"teamcenter";const body=kind==="sap"?{kind:"sap",materialId:result.nativeId}:{kind:"teamcenter",teamcenterItemId:result.nativeId};const started=await fetch(`${API_BASE}/pipeline/start`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body),signal});if(!started.ok)throw new Error(`${result.source} structure request could not start.`);const startPayload=await started.json() as {jobId?:string};if(!startPayload.jobId)throw new Error("Pipeline did not return a job ID.");for(let attempt=0;attempt<60;attempt+=1){await new Promise(resolve=>window.setTimeout(resolve,1500));const response=await fetch(`${API_BASE}/pipeline/bom/${encodeURIComponent(startPayload.jobId)}`,{cache:"no-store",signal});if(response.ok)return await response.json();if(response.status!==404)throw new Error(`${result.source} structure request failed.`);}throw new Error(`${result.source} structure resolution timed out.`);}
export async function resolveSelectedStructure(result:NormalizedSearchResult,signal:AbortSignal):Promise<{root:TreeNodeData;warning?:string}>{try{if(result.source==="windchill"){const response=await fetch(`/api/bom-windchill?partId=${encodeURIComponent(result.nativeId)}`,{cache:"no-store",signal});if(!response.ok)throw new Error("Windchill extraction failed.");return{root:getWindchillRoot(await response.json())??fallback(result)};}if(result.source==="configit"){const response=await fetch(`/api/bom-configit?productId=${encodeURIComponent(result.nativeId)}`,{cache:"no-store",signal});if(!response.ok)throw new Error("Configit solve failed.");return{root:getConfigitRoot(await response.json())??fallback(result)};}const payload=await pipeline(result,signal);const root=result.source==="sap"?sapRoot(payload):getTeamcenterRoot(payload);return{root:root??fallback(result),warning:root?undefined:"The source record was selected, but its structure was not returned."};}catch(cause){return{root:fallback(result),warning:cause instanceof Error?cause.message:"Structure is temporarily unavailable."};}}
