using System.Net;using System.Text;using System.Text.Json;using Orchestration.API.Engineering.Governance;
namespace Orchestration.API.Tests.Engineering;
public sealed class Aud006To010ImplementationTests
{
 [Fact]public void Aud006_identity_requires_authority_evidence_and_preserves_review_history(){var service=new IdentityGovernanceService();var proposed=service.Propose(new[]{"sap:1","windchill:1"},.8m,"normalized identifiers",new[]{new IdentityEvidenceRecord("normalized-id","1","sap",null)});Assert.Equal(IdentityDecisionState.Proposed,proposed.State);var reviewed=service.Review(proposed.Id,true,"reviewer@tenant","confirmed against engineering cross-reference");Assert.Equal(IdentityDecisionAuthority.HumanReviewer,reviewed.Authority);Assert.Equal(2,service.History("sap:1").Count);Assert.Equal(IdentityDecisionState.NonMatch,service.DeclareNonMatch(new[]{"sap:2","windchill:2"},"reviewer@tenant","different products").State);}
 [Fact]public void Aud007_shape_variations_normalize_identically_and_unknown_mandatory_shape_is_quarantined(){var sut=new TolerantPayloadNormalizer();var wrapped=JsonDocument.Parse("{\"Envelope\":{\"MaterialId\":{\"DisplayValue\":\"31\"}}}").RootElement;var primitive=JsonDocument.Parse("{\"material_id\":\"31\"}").RootElement;Assert.Equal("31",sut.Normalize("sap","1.0",wrapped,"material-id").Values.Values.Single());Assert.Equal("31",sut.Normalize("sap","1.0",primitive,"material-id").Values.Values.Single());var error=Assert.Throws<PayloadContractException>(()=>sut.Normalize("sap","1.0",primitive,"plant"));Assert.Equal("mandatory-shape-unknown",error.Quarantine.Code);}
 [Theory][InlineData(AvailabilityState.Available,CompletenessState.Complete,false)][InlineData(AvailabilityState.Fallback,CompletenessState.Partial,true)][InlineData(AvailabilityState.Stale,CompletenessState.Partial,true)][InlineData(AvailabilityState.Unavailable,CompletenessState.Missing,true)][InlineData(AvailabilityState.TimedOut,CompletenessState.Missing,true)]public void Aud008_each_data_trust_state_remains_distinct(AvailabilityState state,CompletenessState completeness,bool action){var result=DataTrustPolicy.Create(state,DateTimeOffset.UtcNow,"source-authoritative",state.ToString());Assert.Equal(state,result.Availability);Assert.Equal(completeness,result.Completeness);Assert.Equal(action,result.UserActionRequired);}
 [Fact]public async Task Aud009_connected_certification_records_environment_contract_and_evidence_hash(){var client=new HttpClient(new StubHandler()){BaseAddress=new Uri("https://connected.test")};var result=await new ConnectedCertificationService(client).Execute(new("teamcenter","qa","tenant-a","1.0",new Uri("https://connected.test/health")),default);Assert.True(result.Passed);Assert.Equal("qa",result.Environment);Assert.Equal(64,result.EvidenceHash.Length);}
 [Fact]public void Aud010_versioned_service_negotiates_contract_and_is_idempotent(){var assembler=new Orchestration.API.Engineering.Intelligence.LegacyHandoffCanonicalAssembler();var sut=new VersionedInvestigationService(assembler);var handoff=JsonDocument.Parse("{\"version\":2,\"handoffId\":\"inv-1\",\"createdAt\":\"2026-09-16T00:00:00Z\",\"subjectLabel\":\"Pump\",\"sources\":[{\"source\":\"sap\",\"label\":\"SAP\",\"nativeId\":\"31\",\"completeness\":\"complete\",\"root\":{\"id\":\"31\",\"name\":\"Pump\",\"attributes\":{},\"children\":[]}}]}").RootElement;var first=sut.Create(new(handoff,"idem-1"),"1.0");var second=sut.Create(new(handoff,"idem-1"),"1.0");Assert.Same(first,second);Assert.Equal("1.0",sut.Status(first.InvestigationId).ContractVersion);Assert.Throws<NotSupportedException>(()=>sut.Create(new(handoff,"other"),"2.0"));}
 sealed class StubHandler:HttpMessageHandler{protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request,CancellationToken cancellationToken)=>Task.FromResult(new HttpResponseMessage(HttpStatusCode.OK){Content=new StringContent("connected-ok",Encoding.UTF8,"application/json")});}
}
