export const API_BASE=process.env.NEXT_PUBLIC_API_URL||"http://localhost:5212/api";
async function readError(response:Response){const text=await response.text();try{const body=JSON.parse(text) as{message?:string;error?:string};return body.message||body.error||response.statusText;}catch{return text||response.statusText;}}
async function postPipeline(body:Record<string,unknown>){const response=await fetch(`${API_BASE}/pipeline/start`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!response.ok)throw new Error(`Pipeline error: ${await readError(response)}`);return response.json();}
export function startPipeline(request:{teamcenterItemId:string}){return postPipeline({kind:"teamcenter",...request});}
export function startConfigitExtraction(request:{workItemId:string;productModelCode:string}){return postPipeline({kind:"configit",...request});}
export function startSapExtraction(request:{materialId:string;plant?:string;bomUsage?:string;alternative?:string;includeSapBusinessImpact?:boolean}){return postPipeline({kind:"sap",...request});}
export interface BomNode{itemId:string;sequence?:string;variantState?:string;revId?:string;name?:string;qty?:string;variantCondition?:string;children?:BomNode[];}
export interface PipelineProgress{jobId:string;phase:string;status:string;progressPercent:number;message:string;timestamp:string;bomStructure?:BomNode;error?:string;}
export interface SapOrganization{plant:string;valuationArea:string;companyCode:string;currency:string;}
export interface SapValuationChecks{calculatedInventoryValue:number|null;reportedInventoryValue:number|null;valuationReconciled:boolean|null;}
export interface SapStorageLocation{storageLocation:string;unrestricted:number|null;qualityInspection:number|null;restrictedUse:number|null;blocked:number|null;inTransfer:number|null;returns:number|null;}
export interface SapMaterialImpact{materialId:string;internalMaterialId:string;requestedMaterialId:string;description:string;materialType:string;baseUnit:string;batchManaged:boolean|null;crossPlantStatus:string;status:string;organization:SapOrganization;stock:{unrestricted:number|null;qualityInspection:number|null;restrictedUse:number|null;blocked:number|null;inTransfer:number|null;returns:number|null;totalPhysical:number|null;atpAvailable:number|null};inventory:{valuatedQuantity:number|null;totalStockValue:number|null;valuationType:string};cost:{priceControl:string;standardPrice:number|null;movingAveragePrice:number|null;priceUnit:number|null;effectiveUnitCost:number|null;valuationClass:string};checks:SapValuationChecks;storageLocations:SapStorageLocation[];warnings:string[];extractedAt:string;}
export interface SapBusinessImpact{sourceMaterialId:string;plant:string;status:string;materials:SapMaterialImpact[];warnings:string[];extractedAt:string;}
export function subscribeToProgress(jobId:string,onProgress:(p:PipelineProgress)=>void,onError:(e:string)=>void,onComplete:()=>void){const es=new EventSource(`${API_BASE}/pipeline/progress/${encodeURIComponent(jobId)}`);let done=false;const complete=()=>{if(!done){done=true;es.close();onComplete();}};es.onmessage=e=>{try{const p=JSON.parse(e.data) as PipelineProgress;if(p.status==="error"||p.error){onError(p.error||p.message||"Pipeline error");complete();return;}onProgress(p);if(p.status==="complete"||p.progressPercent===100)complete();}catch{onError("Failed to parse progress data");complete();}};es.onerror=()=>es.close();return()=>es.close();}
export async function getPipelineBom(jobId:string){const r=await fetch(`${API_BASE}/pipeline/bom/${encodeURIComponent(jobId)}`);if(!r.ok)throw new Error((await readError(r))||"Failed to fetch BOM");return r.json();}
export async function getSapBusinessImpact(jobId:string):Promise<SapBusinessImpact>{const r=await fetch(`${API_BASE}/pipeline/sap-impact/${encodeURIComponent(jobId)}`,{cache:"no-store"});if(!r.ok)throw new Error(await readError(r));const body=await r.json();return body.sapImpact as SapBusinessImpact;}
export async function getLogs(){const r=await fetch(`${API_BASE}/pipeline/logs`);if(!r.ok)throw new Error("Failed to fetch logs");return r.json();}
export async function getLogByJobId(jobId:string){try{const r=await fetch(`${API_BASE}/pipeline/logs/${encodeURIComponent(jobId)}`);return r.ok?r.json():null;}catch{return null;}}
export async function getBomStructure(jobId:string):Promise<BomNode|null>{try{const result=await getPipelineBom(jobId);return result?.finalBom?.bomRoot??result?.finalBom?.bomRootNode??null;}catch{return null;}}
export async function healthCheck(){const r=await fetch(`${API_BASE}/pipeline/health`);if(!r.ok)throw new Error("Health check failed");return r.json();}
