import { scanBomDataQuality } from "@/lib/bom-data-quality";
import type { NodeComparison } from "@/types/bom-comparison";
import type { ReverseRequirementTraceResult } from "@/types/requirement-trace";
import type { BranchComparisonSummary, RequirementCoverage, ThreeAnalysisSnapshot, ThreeBranchAnalytics } from "@/types/bom-three";
import type { VisualBomGraph } from "@/types/bom-visualization";
const rank = { matched: 0, probable: 1, changed: 2, missing: 3, "source-only": 3 } as const;
function emptySummary(): BranchComparisonSummary { return { total: 0, matched: 0, changed: 0, missing: 0, sourceOnly: 0, probable: 0, health: 100 }; }
function mergeSummary(target: BranchComparisonSummary, source: BranchComparisonSummary) { target.total += source.total; target.matched += source.matched; target.changed += source.changed; target.missing += source.missing; target.sourceOnly += source.sourceOnly; target.probable += source.probable; if (source.worstStatus && (!target.worstStatus || rank[source.worstStatus] > rank[target.worstStatus])) target.worstStatus = source.worstStatus; }
function complexity(node: VisualBomGraph["nodes"][number], comparison: BranchComparisonSummary, qualityCount: number, maxDescendants: number) { const structural = node.childIds.length * 4 + Math.sqrt(node.descendantCount) * 12 + node.level * 3, risk = comparison.changed * 5 + comparison.missing * 9 + comparison.sourceOnly * 8 + comparison.probable * 4 + qualityCount * 2; return Math.min(100, Math.round((structural + risk) / Math.max(1, 1 + Math.sqrt(maxDescendants) * .15))); }
export function buildThreeAnalysis(graph: VisualBomGraph, comparisons?: Record<string, NodeComparison>, requirementFocus?: ReverseRequirementTraceResult | null): ThreeAnalysisSnapshot {
  const quality = scanBomDataQuality(graph), linkedSourceIds = new Set(requirementFocus?.occurrences.filter((item) => item.source === graph.nodes[0]?.source).map((item) => item.nodeId) ?? []), maxDescendants = Math.max(1, ...graph.nodes.map((node) => node.descendantCount));
  const complexityByNode: Record<string, number> = {}, comparisonByNode: Record<string, BranchComparisonSummary> = {}, requirementCoverageByNode: Record<string, RequirementCoverage> = {}, qualityCountByNode: Record<string, number> = {}, subtreeSize: Record<string, number> = {}, linkedCount: Record<string, number> = {};
  for (let index = graph.nodes.length - 1; index >= 0; index -= 1) {
    const node = graph.nodes[index], summary = emptySummary(), own = comparisons?.[node.sourceNodeId];
    if (own) { summary.total = 1; if (own.status === "matched") summary.matched = 1; else if (own.status === "changed") summary.changed = 1; else if (own.status === "missing") summary.missing = 1; else if (own.status === "source-only") summary.sourceOnly = 1; else summary.probable = 1; summary.worstStatus = own.status; }
    let size = 1, linked = linkedSourceIds.has(node.sourceNodeId) ? 1 : 0, qualityCount = quality.findingIdsByNode[node.id]?.length ?? 0;
    for (const childId of node.childIds) { mergeSummary(summary, comparisonByNode[childId] ?? emptySummary()); size += subtreeSize[childId] ?? 0; linked += linkedCount[childId] ?? 0; qualityCount += qualityCountByNode[childId] ?? 0; }
    summary.health = summary.total ? Math.round(summary.matched / summary.total * 100) : 100;
    subtreeSize[node.id] = size; linkedCount[node.id] = linked; qualityCountByNode[node.id] = qualityCount; comparisonByNode[node.id] = summary; complexityByNode[node.id] = complexity(node, summary, qualityCount, maxDescendants); requirementCoverageByNode[node.id] = { linked, total: size, percentage: Math.round(linked / size * 100) };
  }
  return { quality, complexityByNode, comparisonByNode, requirementCoverageByNode, qualityCountByNode };
}
export function branchAnalytics(graph: VisualBomGraph, nodeId: string, analysis: ThreeAnalysisSnapshot): ThreeBranchAnalytics | null {
  const node = graph.byId[nodeId]; if (!node) return null; const comparison = analysis.comparisonByNode[nodeId], coverage = analysis.requirementCoverageByNode[nodeId], qualityCount = analysis.qualityCountByNode[nodeId] ?? 0, branchShare = Math.round((node.descendantCount + 1) / Math.max(1, graph.nodes.length) * 1000) / 10;
  const summary = [`${node.name} is a level-${node.level + 1} ${node.isAssembly ? "assembly" : "component"} representing ${branchShare}% of the loaded BOM.`]; if (node.isAssembly) summary.push(`The branch contains ${node.childIds.length} direct children, ${node.descendantCount} total descendants, and ${node.leafCount} leaf components.`); if (comparison.total) summary.push(`Comparison health is ${comparison.health}% with ${comparison.changed} changed, ${comparison.missing} missing, ${comparison.sourceOnly} source-only, and ${comparison.probable} probable result${comparison.total === 1 ? "" : "s"}.`); summary.push(coverage.linked ? `${coverage.linked} of ${coverage.total} branch occurrences are linked by the active requirement focus.` : "No active requirement-linked occurrences are present in this branch."); if (qualityCount) summary.push(`${qualityCount} data-quality observation${qualityCount === 1 ? " requires" : "s require"} review in this branch.`);
  return { node, branchShare, directChildren: node.childIds.length, totalDescendants: node.descendantCount, leafDescendants: node.leafCount, complexity: analysis.complexityByNode[nodeId], comparison, requirementCoverage: coverage, qualityFindingCount: qualityCount, summary };
}
