namespace Orchestration.API.Engineering.Contracts;

public static class EngineeringIntelligenceContractVersions { public const string V1 = "1.0"; }
public static class EngineeringEntityKinds { public const string Part="part", PartOccurrence="part-occurrence", Assembly="assembly", Material="material", Requirement="requirement", RequirementRevision="requirement-revision", ChangeNotice="change-notice", ChangeTask="change-task", ProductionOrder="production-order", ConfigurationFeature="configuration-feature", ConfigurationOption="configuration-option", Document="document", AccountingDocument="accounting-document", Plant="plant", StorageLocation="storage-location", SourceRepresentation="source-representation"; }
public static class EngineeringRelationshipFamilies { public const string Structure="structure", Requirement="requirement", Change="change", Configuration="configuration", Operation="operation", CostAndInventory="cost-and-inventory", Correspondence="correspondence", Evidence="evidence"; }
public static class EngineeringRelationshipKinds { public const string Contains="contains", RepresentedBy="represented-by", Satisfies="satisfies", GovernedBy="governed-by", AffectedBy="affected-by", Supersedes="supersedes", ConfiguredBy="configured-by", SelectedOption="selected-option", ProducedBy="produced-by", StockedAt="stocked-at", ReferencedIn="referenced-in", CorrespondsTo="corresponds-to", SupportedBy="supported-by"; }

public enum IntelligenceAuthority { SourceAuthoritative, BackendDerived, FrontendDerived, Hardcoded, Mocked }
public enum IntelligenceAssertionKind { Fact, Inference, Finding }
public enum SourceExtractionStatus { Available, Partial, Unavailable, Failed, Cancelled, TimedOut, CapabilityLimited, NotObserved }
public enum IdentityQuality { Native, DeterministicDerived, Provisional }
public enum FreshnessState { Current, Stale, Unknown, NotApplicable }
public enum FindingReviewState { NotRequired, NeedsReview, Confirmed, Dismissed }

public sealed record TemporalContext(DateTimeOffset? RequestedAt,DateTimeOffset? CapturedAt,DateTimeOffset AssembledAt,DateTimeOffset? EffectiveAt,DateTimeOffset? ValidFrom,DateTimeOffset? ValidTo,FreshnessState Freshness);
public sealed record EngineeringProvenance(EngineeringSource? Source,string Provider,string? NativeId,string? NativeRevision,string? SourceExecutionId,string? ArtifactReference,string? Checksum,DateTimeOffset ObservedAt,IntelligenceAuthority Authority);
public sealed record IntelligenceProperty(string Type,string? Text=null,decimal? Number=null,bool? Boolean=null,DateTimeOffset? Timestamp=null,IReadOnlyList<string>? Items=null,string? Reference=null);
public sealed record EngineeringSubject(string Id,string DisplayName,string? PreferredProductId,IReadOnlyList<string> CandidateIds,IntelligenceConfidence Confidence,IReadOnlyList<string> Reasons,EngineeringProvenance Provenance,TemporalContext Temporal);
public sealed record EngineeringIntelligenceEntity(string Id,string Kind,string DisplayName,IdentityQuality IdentityQuality,IntelligenceAssertionKind Assertion,IReadOnlyDictionary<string,IntelligenceProperty> Properties,EngineeringProvenance Provenance,TemporalContext Temporal);
public sealed record EngineeringIntelligenceRelationship(string Id,string Kind,string Family,string SourceEntityId,string TargetEntityId,IntelligenceAssertionKind Assertion,IntelligenceConfidence? Confidence,IReadOnlyList<string> EvidenceIds,IReadOnlyDictionary<string,IntelligenceProperty> Properties,EngineeringProvenance Provenance,TemporalContext Temporal);
public sealed record EngineeringIntelligenceEvidence(string Id,string Kind,string Summary,EngineeringSource Source,string? SourceExecutionId,string? Reference,string? Checksum,IReadOnlyDictionary<string,IntelligenceProperty> Properties,EngineeringProvenance Provenance,TemporalContext Temporal);
public sealed record EngineeringIntelligenceFinding(string Id,string Kind,string Title,string Summary,IntelligenceSeverity Severity,IntelligenceAssertionKind Assertion,IntelligenceConfidence? Confidence,IReadOnlyList<string> SubjectEntityIds,IReadOnlyList<string> EvidenceIds,FindingReviewState ReviewState,EngineeringProvenance Provenance,TemporalContext Temporal);
public sealed record SourceRepresentation(string EntityId,EngineeringSource Source,SourceExtractionStatus Status,string? NativeId,string? Revision,string? Version,IReadOnlyList<string> WarningCodes,IReadOnlyList<string> ErrorCodes,EngineeringProvenance Provenance);
public sealed record IdentityCluster(string Id,string? PreferredEntityId,IReadOnlyList<string> EntityIds,IntelligenceConfidence Confidence,IReadOnlyList<string> Reasons,IReadOnlyList<string> EvidenceIds);
public sealed record InvestigationSummary(int EntityCount,int RelationshipCount,int EvidenceCount,int FindingCount,int AvailableSourceCount,int PartialSourceCount,StandardStatus Status);
public sealed record EngineeringIntelligenceInvestigation(string ContractVersion,string InvestigationId,EngineeringSubject Subject,IReadOnlyList<EngineeringIntelligenceEntity> Entities,IReadOnlyList<EngineeringIntelligenceRelationship> Relationships,IReadOnlyList<EngineeringIntelligenceEvidence> Evidence,IReadOnlyList<EngineeringIntelligenceFinding> Findings,IReadOnlyList<SourceRepresentation> Sources,IReadOnlyList<IdentityCluster> IdentityClusters,TemporalContext Temporal,InvestigationSummary Summary);
