
using Orchestration.API.Engineering.Contracts;
namespace Orchestration.API.Engineering.Intelligence;
public interface IEngineeringFindingEvaluator{IReadOnlyList<EngineeringFinding> Evaluate(UnifiedProductIdentity identity,IReadOnlyList<SourceIntelligenceEnvelope> sources,IReadOnlyList<CandidateCorrespondence> correspondences);}
public sealed class EngineeringFindingEvaluator:IEngineeringFindingEvaluator
{
 public IReadOnlyList<EngineeringFinding> Evaluate(UnifiedProductIdentity identity,IReadOnlyList<SourceIntelligenceEnvelope> sources,IReadOnlyList<CandidateCorrespondence> correspondences){var findings=new List<EngineeringFinding>();foreach(var source in sources.Where(x=>x.Status!=StandardStatus.Success).OrderBy(x=>x.Source)){var code=source.Status switch{StandardStatus.PartialSuccess=>"source-evidence-partial",StandardStatus.Empty=>"source-evidence-empty",StandardStatus.Unavailable=>"source-unavailable",StandardStatus.AwaitingContext=>"source-awaiting-context",StandardStatus.TimedOut=>"source-timed-out",_=>"source-evidence-failed"};findings.Add(new($"finding-{source.Source.ToString().ToLowerInvariant()}-{code}",code,$"{source.Source} evidence is {source.Status.ToString().ToLowerInvariant()}.","The unified result preserves this source outcome without inventing missing evidence.",IntelligenceSeverity.Warning,IntelligenceConfidence.Verified,[source.Source],source.References,new Dictionary<string,string?>{{"status",source.Status.ToString()}}));}if(identity.Confidence is IntelligenceConfidence.Ambiguous or IntelligenceConfidence.Unresolved)findings.Add(new("finding-identity-review","identity-review-required","Product identity requires review.","Selected source candidates do not have sufficient deterministic correspondence evidence.",IntelligenceSeverity.Warning,identity.Confidence,sources.Select(x=>x.Source).Distinct().Order().ToArray(),sources.SelectMany(x=>x.References).ToArray(),new Dictionary<string,string?>()));foreach(var c in correspondences.Where(x=>x.ReviewState==CorrespondenceReviewState.Ambiguous))findings.Add(new($"finding-{c.CorrespondenceId}","ambiguous-correspondence","Candidate correspondence is ambiguous.",c.Reason,IntelligenceSeverity.Warning,IntelligenceConfidence.Ambiguous,sources.Where(x=>c.SourceCandidateIds.Contains(x.Candidate?.CandidateId??"")).Select(x=>x.Source).Distinct().ToArray(),[],new Dictionary<string,string?>{{"correspondenceId",c.CorrespondenceId}}));return findings;}
}



