using System.Text.Json;using System.Text.Json.Serialization;using Orchestration.API.Engineering.Contracts;using Orchestration.API.Engineering.Intelligence;
namespace Orchestration.API.Tests.Engineering.Intelligence;
public sealed class EngineeringIntelligenceContractTests
{
 [Fact]public void Stable_ids_are_order_independent(){var a=EngineeringIntelligenceIdentityFactory.Entity("part","Teamcenter","ITEM 001");var b=EngineeringIntelligenceIdentityFactory.Entity("part","teamcenter","item 001");Assert.Equal(a,b);Assert.NotEqual(a,EngineeringIntelligenceIdentityFactory.Entity("part","sap","item 001"));}
 [Fact]public void V1_contract_serializes_with_kebab_case_enums(){var value=Minimal();var options=new JsonSerializerOptions{PropertyNamingPolicy=JsonNamingPolicy.CamelCase};options.Converters.Add(new JsonStringEnumConverter(JsonNamingPolicy.KebabCaseLower));var json=JsonSerializer.Serialize(value,options);Assert.Contains("\"contractVersion\":\"1.0\"",json);Assert.Contains("\"authority\":\"backend-derived\"",json);}
 [Fact]public void Validator_rejects_unsubstantiated_inference(){var value=Minimal();var rel=new EngineeringIntelligenceRelationship("r","corresponds-to","correspondence",value.Subject.Id,value.Entities[0].Id,IntelligenceAssertionKind.Inference,IntelligenceConfidence.Probable,[],new Dictionary<string,IntelligenceProperty>(),value.Subject.Provenance,value.Temporal);var invalid=value with{Relationships=[rel]};var result=new EngineeringIntelligenceInvestigationValidator().Validate(invalid);Assert.False(result.IsValid);Assert.Contains(result.Errors,x=>x.StartsWith("inference-unsubstantiated:"));}
 static EngineeringIntelligenceInvestigation Minimal(){var now=DateTimeOffset.Parse("2026-09-01T00:00:00Z");var t=new TemporalContext(null,null,now,null,null,null,FreshnessState.Unknown);var p=new EngineeringProvenance(null,"test",null,null,null,null,null,now,IntelligenceAuthority.BackendDerived);var subject=new EngineeringSubject("subject","Part",null,[],IntelligenceConfidence.Deterministic,[],p,t);var e=new EngineeringIntelligenceEntity("source","source-representation","Teamcenter",IdentityQuality.Native,IntelligenceAssertionKind.Fact,new Dictionary<string,IntelligenceProperty>(),p,t);return new("1.0","i",subject,[e],[],[],[],[],[],t,new(1,0,0,0,0,0,StandardStatus.Success));}
}
