
using Orchestration.API.Engineering.Contracts;using Orchestration.API.Engineering.Intelligence;using Orchestration.API.Models;
namespace Orchestration.API.Tests.Engineering.Intelligence;
public sealed class Slice3AIntelligenceTests
{
 [Fact]public void IdentityIsDeterministicForSameCandidateSet(){var e=new UnifiedIdentityEvaluator();var a=e.Evaluate([Candidate(EngineeringSource.Sap,"sap:1","001","Pump"),Candidate(EngineeringSource.Windchill,"wc:1","001","Pump")],[]);var b=e.Evaluate([Candidate(EngineeringSource.Windchill,"wc:1","001","Pump"),Candidate(EngineeringSource.Sap,"sap:1","001","Pump")],[]);Assert.Equal(a.IdentityId,b.IdentityId);Assert.Equal(IntelligenceConfidence.Deterministic,a.Confidence);}
 [Fact]public void NameOnlyAgreementDoesNotBecomeVerified(){var e=new UnifiedIdentityEvaluator();var x=e.Evaluate([Candidate(EngineeringSource.Sap,"sap:1","MAT","Pump"),Candidate(EngineeringSource.Windchill,"wc:1","PART","Pump")],[]);Assert.Equal(IntelligenceConfidence.Probable,x.Confidence);}
 [Fact]public void ConflictingNamesRemainAmbiguous(){var e=new UnifiedIdentityEvaluator();var x=e.Evaluate([Candidate(EngineeringSource.Sap,"sap:1","MAT","Pump"),Candidate(EngineeringSource.Windchill,"wc:1","PART","Valve")],[]);Assert.Equal(IntelligenceConfidence.Ambiguous,x.Confidence);}
 [Fact]public void MapperCreatesSapTypedEvidence(){var mapped=new TypedSourceEvidenceMapper().Map(Result(EngineeringSource.Sap,StandardStatus.PartialSuccess,new Dictionary<string,object?>{{"plant","1001"},{"businessImpact",new{available=true}}}));var sap=Assert.IsType<SapTypedEvidence>(mapped.Evidence);Assert.Equal("1001",sap.Plant);Assert.Equal(EvidenceAvailability.Partial,sap.Availability);}
 [Fact]public void MapperCreatesConfigitTypedEvidence(){var mapped=new TypedSourceEvidenceMapper().Map(Result(EngineeringSource.Configit,StandardStatus.Success,new Dictionary<string,object?>{{"packagePath","approved/package"}}));Assert.Equal("approved/package",Assert.IsType<ConfigitTypedEvidence>(mapped.Evidence).PackagePath);}
 [Theory][InlineData(StandardStatus.Success,EvidenceCompleteness.Complete)][InlineData(StandardStatus.PartialSuccess,EvidenceCompleteness.Partial)][InlineData(StandardStatus.Empty,EvidenceCompleteness.Missing)][InlineData(StandardStatus.Unavailable,EvidenceCompleteness.Unavailable)]public void CompletenessPreservesSourceOutcome(StandardStatus status,EvidenceCompleteness expected){var e=new EvidenceCompletenessEvaluator();var source=new TypedSourceEvidenceMapper().Map(Result(EngineeringSource.Teamcenter,status));Assert.Equal(expected,Assert.Single(e.Evaluate([source])).Completeness);}
 [Fact]public void FindingsExposeAwaitingContextWithoutInventingEvidence(){var source=new TypedSourceEvidenceMapper().Map(Result(EngineeringSource.Configit,StandardStatus.AwaitingContext));var identity=new UnifiedIdentityEvaluator().Evaluate([Candidate(EngineeringSource.Configit,"c:1","P1","Product")],[]);var finding=Assert.Single(new EngineeringFindingEvaluator().Evaluate(identity,[source],[]),x=>x.Code=="source-awaiting-context");Assert.Empty(finding.Evidence);}
 [Fact]public void AssemblerIgnoresResultForUnselectedCandidate(){var selected=Candidate(EngineeringSource.Sap,"sap:selected","001","Pump");var stale=Result(EngineeringSource.Sap,StandardStatus.Success,candidate:Candidate(EngineeringSource.Sap,"sap:stale","002","Other"));var a=Assembler().Assemble(new("1.0","discovery-1",[selected],[stale],[]));Assert.Empty(a.Sources);Assert.Equal(StandardStatus.Empty,a.Status);}
 [Fact]public void AssemblerProducesPartialSuccessForMixedResults(){var tc=Candidate(EngineeringSource.Teamcenter,"tc:1","001","Pump");var sap=Candidate(EngineeringSource.Sap,"sap:1","001","Pump");var a=Assembler().Assemble(new("1.0","d",[tc,sap],[Result(EngineeringSource.Teamcenter,StandardStatus.Success,candidate:tc),Result(EngineeringSource.Sap,StandardStatus.PartialSuccess,candidate:sap)],[]));Assert.Equal(StandardStatus.PartialSuccess,a.Status);Assert.Equal(2,a.Sources.Count);Assert.Contains(a.Findings,x=>x.Code=="source-evidence-partial");}
 [Fact]public void AssemblerIsSourceOrderDeterministic(){var tc=Candidate(EngineeringSource.Teamcenter,"tc:1","001","Pump");var sap=Candidate(EngineeringSource.Sap,"sap:1","001","Pump");var a=Assembler().Assemble(new("1.0","d",[sap,tc],[Result(EngineeringSource.Sap,StandardStatus.Success,candidate:sap),Result(EngineeringSource.Teamcenter,StandardStatus.Success,candidate:tc)],[]));Assert.Equal([EngineeringSource.Teamcenter,EngineeringSource.Sap],a.Sources.Select(x=>x.Source).ToArray());}
 static UnifiedProductIntelligenceAssembler Assembler()=>new(new TypedSourceEvidenceMapper(),new UnifiedIdentityEvaluator(),new EvidenceCompletenessEvaluator(),new EngineeringFindingEvaluator());
 static SourceCandidate Candidate(EngineeringSource s,string cid,string id,string name)=>new(cid,s,id,name,"product",null,null,null,null,MatchCategory.SourceNativeReference,"selected",ConfidenceClass.Unverified,[],new Dictionary<string,string?>(),new(ProvenanceKind.CachedSourceResult,"test",DateTimeOffset.UtcNow),true);
 static StandardExtractionResult Result(EngineeringSource s,StandardStatus status,IReadOnlyDictionary<string,object?>? evidence=null,SourceCandidate? candidate=null){var now=DateTimeOffset.UtcNow;candidate??=Candidate(s,$"{s}:1","001","Pump");var availability=status==StandardStatus.Success?ProvenanceKind.LiveSource:ProvenanceKind.Unavailable;return new("1.0","r","c",$"exec-{s}",s,status,new(status,candidate,candidate.NativeId,[],[]),new(s,SourceReadiness.Ready,[],true,true,true,true,false,false,false,false,false,true,true,true,[],[]),status is StandardStatus.Success or StandardStatus.PartialSuccess?new BomRoot{SourceItemId=candidate.NativeId,BomRootNode=new BomNode{ItemId=candidate.NativeId}}:null,[],evidence??new Dictionary<string,object?>(),[],[],new($"exec-{s}",s,EngineeringStage.Extraction,status==StandardStatus.Success?JobState.Success:JobState.Failed,100,"complete",now),[],new(availability,"test",now),[],now,now,0);}
}



