namespace Orchestration.API.Engineering.Contracts;
public sealed record DefaultDecision(string Field,string? RequestedValue,string? EffectiveValue,bool Defaulted,string DefaultSource,string DefaultReason);
public sealed record ConfigitConfigurationContext(string? PackagePath=null,string? PackageVersion=null,string? ConfigurationDate=null,IReadOnlyDictionary<string,string>? ProvidedVariables=null,string? NodeContext=null);
public sealed record FederatedSourceContext(EngineeringSource Source,OrganizationContext? OrganizationContext=null,ConfigitConfigurationContext? ConfigurationContext=null);
public sealed record FederatedEngineeringExtractionRequest(string SchemaVersion,string ParentDiscoveryJobId,string? RequestId=null,string? CorrelationId=null,TimeoutPolicy? TimeoutPolicy=null,IReadOnlyList<string>? RequestedEvidence=null,IReadOnlyList<FederatedSourceContext>? SourceContexts=null);
public enum FederatedExtractionJobState { Accepted,Extracting,AwaitingContext,Empty,Unavailable,Failed,CancellationRequested,Cancelled,TimedOut,Success,PartialSuccess }
public sealed record FederatedExtractionAccepted(string SchemaVersion,string ParentExtractionJobId,FederatedExtractionJobState State,DateTimeOffset AcceptedAt);
public sealed record FederatedExtractionChildSnapshot(string SourceExecutionId,EngineeringSource Source,string CandidateId,int Attempt,StandardStatus Status,int ProgressPercent,DateTimeOffset CreatedAt,DateTimeOffset? CompletedAt,bool Active,bool Retryable,StandardExtractionResult? Result);
public sealed record FederatedEngineeringExtractionResult(string SchemaVersion,string ParentExtractionJobId,string ParentDiscoveryJobId,StandardStatus Status,int ProgressPercent,IReadOnlyList<FederatedExtractionChildSnapshot> Sources,IReadOnlyList<StructuredWarning> Warnings,IReadOnlyList<StructuredError> Errors,DateTimeOffset StartedAt,DateTimeOffset CompletedAt);
public sealed record FederatedExtractionJobSnapshot(string ParentExtractionJobId,string ParentDiscoveryJobId,string RequestId,string CorrelationId,FederatedExtractionJobState State,int ProgressPercent,DateTimeOffset CreatedAt,DateTimeOffset? CompletedAt,DateTimeOffset? CancellationRequestedAt,IReadOnlyList<FederatedExtractionChildSnapshot> Sources,FederatedEngineeringExtractionResult? Result);
