import { describe, expect, it } from "vitest";
import type { EngineeringIntelligenceInvestigationV1 } from "../contracts/intelligence-v1";
import { buildIntelligenceInvestigation } from "../engines/build-intelligence-investigation";

const temporal={assembledAt:"2026-09-02T00:00:00Z",freshness:"unknown" as const};
const provenance={provider:"test",observedAt:"2026-09-02T00:00:00Z",authority:"backend-derived" as const};
const entity=(id:string,kind="part")=>({id,kind,displayName:id,identityQuality:"deterministic-derived" as const,assertion:"fact" as const,properties:{},provenance,temporal});
function input(confidence:string):EngineeringIntelligenceInvestigationV1{return {contractVersion:"1.0",investigationId:"i",subject:{id:"subject",displayName:"Part",candidateIds:[],confidence:"deterministic",reasons:[],provenance,temporal},entities:[entity("part-a"),entity("part-b"),entity("tc","source-representation"),entity("sap","source-representation")],relationships:[{id:"r",kind:"contains",family:"structure",sourceEntityId:"part-b",targetEntityId:"tc",assertion:"fact",evidenceIds:[],properties:{},provenance,temporal}],evidence:[],findings:[],sources:[{entityId:"tc",source:"teamcenter",status:"available",provenance},{entityId:"sap",source:"sap",status:"available",provenance}],identityClusters:[{id:"parts",preferredEntityId:"part-a",entityIds:["part-a","part-b"],confidence,reasons:["same id"],evidenceIds:[]},{id:"representations",preferredEntityId:"subject",entityIds:["subject","tc","sap"],confidence:"verified",reasons:["representations"],evidenceIds:[]}],temporal,summary:{entityCount:4,relationshipCount:1,evidenceCount:0,findingCount:0,availableSourceCount:2,partialSourceCount:0,status:"success"}}}

describe("canonical entity deduplication",()=>{it("merges verified canonical duplicates and redirects relationships",()=>{const graph=buildIntelligenceInvestigation(input("verified"));expect(graph.byId["part-a"]).toBeTruthy();expect(graph.byId["part-b"]).toBeUndefined();expect(graph.relationshipById.r.from).toBe("part-a");expect(graph.metadata?.entityAliases).toEqual({"part-b":"part-a"});expect(graph.byId.tc).toBeTruthy();expect(graph.byId.sap).toBeTruthy();});it("does not merge ambiguous canonical entities",()=>{const graph=buildIntelligenceInvestigation(input("ambiguous"));expect(graph.byId["part-a"]).toBeTruthy();expect(graph.byId["part-b"]).toBeTruthy();expect(graph.metadata?.entityAliases).toEqual({});});});
