using Orchestration.API.Engineering.Contracts;
namespace Orchestration.API.Engineering.Services;
public interface IEngineeringRequestValidator { ValidationOutcome Validate(EngineeringDiscoveryRequest request); ValidationOutcome Validate(EngineeringExtractionRequest request); }
public sealed class EngineeringRequestValidator : IEngineeringRequestValidator {
 const int MinTimeout=1000,MaxTimeout=1800000,MinLimit=1,MaxLimit=50,MaxText=256;
 public ValidationOutcome Validate(EngineeringDiscoveryRequest r){var e=new List<StructuredError>(); Common(r.SchemaVersion,r.RequestId,r.CorrelationId,r.TimeoutPolicy,e); if(r.RequestedSources is null||r.RequestedSources.Count==0)Add(e,"sources-required","At least one source is required."); else if(r.RequestedSources.Distinct().Count()!=r.RequestedSources.Count)Add(e,"duplicate-sources","Requested sources must be unique."); if(r.Query is null)Add(e,"query-required","Query is required."); else {if(AllEmpty(r.Query))Add(e,"query-empty","A product ID, product name, or original input is required."); Length(r.Query.ProductId,"product-id-too-long",e);Length(r.Query.ProductName,"product-name-too-long",e);Length(r.Query.OriginalInput,"query-too-long",e);} if(r.ResultLimitPerSource<MinLimit||r.ResultLimitPerSource>MaxLimit)Add(e,"result-limit-out-of-range",$"Result limit must be between {MinLimit} and {MaxLimit}."); return new(!e.Any(),e);}
 public ValidationOutcome Validate(EngineeringExtractionRequest r){var e=new List<StructuredError>();Common(r.SchemaVersion,r.RequestId,r.CorrelationId,r.TimeoutPolicy,e);if(r.Candidate is null)Add(e,"candidate-required","A selected source candidate is required.");else if(r.Candidate.Source!=r.Source)Add(e,"candidate-source-mismatch","Candidate source does not match request source.");if(r.OrganizationContext?.Additional?.Any(x=>string.IsNullOrWhiteSpace(x.Key))==true)Add(e,"organization-context-invalid","Organization context contains an empty key.");return new(!e.Any(),e);}
 static bool AllEmpty(EngineeringQuery q)=>string.IsNullOrWhiteSpace(q.OriginalInput)&&string.IsNullOrWhiteSpace(q.ProductId)&&string.IsNullOrWhiteSpace(q.ProductName);
 static void Length(string? v,string code,List<StructuredError> e){if(v?.Length>MaxText)Add(e,code,"Query field exceeds the maximum length.");}
 static void Common(string v,string id,string correlation,TimeoutPolicy t,List<StructuredError> e){if(v!=EngineeringContractVersions.V1)Add(e,"schema-version-unsupported","Schema version is unsupported.");if(string.IsNullOrWhiteSpace(id)||id.Length>128)Add(e,"request-id-invalid","Request ID is required and must be at most 128 characters.");if(string.IsNullOrWhiteSpace(correlation)||correlation.Length>128)Add(e,"correlation-id-invalid","Correlation ID is required and must be at most 128 characters.");if(t is null||t.TimeoutMs<MinTimeout||t.TimeoutMs>MaxTimeout)Add(e,"timeout-out-of-range",$"Timeout must be between {MinTimeout} and {MaxTimeout} milliseconds.");}
 static void Add(List<StructuredError> e,string code,string message)=>e.Add(new(code,null,EngineeringStage.Validation,message,message,false,DateTimeOffset.UtcNow));
}
