import type { NodePosition, RelationshipProjection } from "../contracts/projection";
import type { Bounds, LayoutRoute, UniversalLayoutResult } from "./layout-contract";
export type LayoutChangeType="initial"|"expand"|"collapse"|"filter"|"pin"|"unpin"|"resize"|"replace"|"structural";
export type LayoutSession={layoutRevision:number;graphStructuralKey:string;subjectPosition:NodePosition;branchAnchors:Record<string,NodePosition>;branchBounds:Record<string,Bounds>;nodePositions:Record<string,NodePosition>;routes:Record<string,LayoutRoute>;visibleNodeIds:string[];visibleEdgeIds:string[];layoutGeneration:number};
export type StabilityDiagnostics={changeType:LayoutChangeType;changedBranchIds:string[];reusedBranchCount:number;recalculatedBranchCount:number;unchangedNodeMeanMovement:number;unchangedNodeMaximumMovement:number;displacedNeighborCount:number;staleResultsRejected:number;layoutDurationMs:number};
const ids=(p:RelationshipProjection)=>new Set(p.nodes.map(n=>n.id));
export function classifyChange(previous:LayoutSession|undefined,p:RelationshipProjection,pinned:Readonly<Record<string,NodePosition>>,viewportChanged=false):LayoutChangeType{if(!previous)return"initial";if(viewportChanged)return"resize";const before=new Set(previous.visibleNodeIds),after=ids(p);if(after.size>before.size&&[...before].every(x=>after.has(x)))return"expand";if(after.size<before.size&&[...after].every(x=>before.has(x)))return"collapse";if(p.structuralKey!==previous.graphStructuralKey)return"structural";if(Object.keys(pinned).some(id=>previous.nodePositions[id]&&(previous.nodePositions[id].x!==pinned[id].x||previous.nodePositions[id].y!==pinned[id].y)))return"pin";return"filter"}
export function stabilizeLayout(result:UniversalLayoutResult,previous:LayoutSession|undefined,changeType:LayoutChangeType){if(!previous||changeType==="initial"||changeType==="replace"||changeType==="resize")return result;const changed=new Set<string>();for(const b of result.branches){const old=previous.branchBounds[b.id];if(!old||b.nodeIds.some(id=>!previous.nodePositions[id]))changed.add(b.id)}const positions={...result.positions};for(const b of result.branches){if(changed.has(b.id)||!previous.branchBounds[b.id])continue;const old=previous.branchBounds[b.id],dx=old.x-b.bounds.x,dy=old.y-b.bounds.y;for(const id of b.nodeIds)if(positions[id])positions[id]={x:positions[id].x+dx,y:positions[id].y+dy};b.bounds={...old};result.branchBounds[b.id]={...old};for(const route of Object.values(result.routes).filter(r=>b.edgeIds.includes(r.edgeId))){route.start={x:route.start.x+dx,y:route.start.y+dy};route.bends=route.bends.map(p=>({x:p.x+dx,y:p.y+dy}));route.end={x:route.end.x+dx,y:route.end.y+dy}}}return {...result,positions}}
export function createSession(result:UniversalLayoutResult,p:RelationshipProjection,generation:number):LayoutSession{const subject=p.nodes.find(n=>n.level===0)?.id??p.nodes[0]?.id;return{layoutRevision:result.revision,graphStructuralKey:p.structuralKey,subjectPosition:subject?result.positions[subject]??{x:0,y:0}:{x:0,y:0},branchAnchors:Object.fromEntries(result.branches.map(b=>[b.id,result.positions[b.rootId]??{x:b.bounds.x,y:b.bounds.y}])),branchBounds:result.branchBounds,nodePositions:result.positions,routes:result.routes,visibleNodeIds:p.nodes.map(n=>n.id).sort(),visibleEdgeIds:p.edges.map(e=>e.id).sort(),layoutGeneration:generation}}
export function movementDiagnostics(previous:LayoutSession|undefined,result:UniversalLayoutResult,changeType:LayoutChangeType,elapsed:number):StabilityDiagnostics{if(!previous)return{changeType,changedBranchIds:result.branches.map(b=>b.id),reusedBranchCount:0,recalculatedBranchCount:result.branches.length,unchangedNodeMeanMovement:0,unchangedNodeMaximumMovement:0,displacedNeighborCount:0,staleResultsRejected:0,layoutDurationMs:elapsed};const moves=Object.entries(result.positions).filter(([id])=>previous.nodePositions[id]).map(([id,p])=>Math.hypot(p.x-previous.nodePositions[id].x,p.y-previous.nodePositions[id].y));const changed=result.branches.filter(b=>!previous.branchBounds[b.id]||b.nodeIds.some(id=>!previous.nodePositions[id])).map(b=>b.id);return{changeType,changedBranchIds:changed,reusedBranchCount:result.branches.length-changed.length,recalculatedBranchCount:changed.length,unchangedNodeMeanMovement:moves.length?moves.reduce((a,b)=>a+b,0)/moves.length:0,unchangedNodeMaximumMovement:moves.length?Math.max(...moves):0,displacedNeighborCount:moves.filter(v=>v>1).length,staleResultsRejected:0,layoutDurationMs:elapsed}}
