import type { NodePosition, ProjectedEdge, RelationshipProjection } from "../contracts/projection";
import type { Bounds, LayoutBranch, LayoutRoute, Size } from "./layout-contract";

export type RouteFamily = "structure"|"correspondence"|"requirement"|"change-impact"|"operational-impact"|"configuration"|"evidence";
export type RoutingDiagnostics={routedEdgeCount:number;fallbackEdgeCount:number;invalidRouteCount:number;routeNodeIntersectionCount:number;routeBranchIntersectionCount:number;overlappingSegmentCount:number;labelCollisionCount:number;averageBendCount:number;routingDurationMs:number};
const structural=new Set(["contains","represented-by"]);
const family=(kind:string):RouteFamily=>kind==="contains"||kind==="represented-by"?"structure":kind==="corresponds-to"||kind==="comparison"?"correspondence":kind==="requirement"?"requirement":kind==="business-impact"?"operational-impact":"evidence";
const center=(id:string,p:Record<string,NodePosition>,d:Record<string,Size>):NodePosition=>({x:p[id].x+d[id].width/2,y:p[id].y+d[id].height/2});
const finite=(p:NodePosition)=>Number.isFinite(p.x)&&Number.isFinite(p.y);
const pointIn=(p:NodePosition,b:Bounds,pad=0)=>p.x>b.x-pad&&p.x<b.x+b.width+pad&&p.y>b.y-pad&&p.y<b.y+b.height+pad;
const segmentLength=(a:NodePosition,b:NodePosition)=>Math.hypot(b.x-a.x,b.y-a.y);
const segmentMid=(a:NodePosition,b:NodePosition):NodePosition=>({x:(a.x+b.x)/2,y:(a.y+b.y)/2});
const routeKey=(e:ProjectedEdge)=>[e.source,e.target].sort().join("|");
function preferredLabel(points:NodePosition[],occupied:NodePosition[]){let best=segmentMid(points[0],points.at(-1)!);let length=-1;for(let i=0;i<points.length-1;i++){const candidate=segmentMid(points[i],points[i+1]);const score=segmentLength(points[i],points[i+1]);if(score>length&&occupied.every(p=>Math.hypot(p.x-candidate.x,p.y-candidate.y)>72)){best=candidate;length=score}}occupied.push(best);return best}
function corridorRoute(edge:ProjectedEdge,start:NodePosition,end:NodePosition,lane:number,bounds:Bounds[],subjectId:string){
 const f=family(edge.kind); if(edge.source===subjectId||edge.target===subjectId){const offset=46+lane*18;const sx=start.x<end.x?1:-1;return [start,{x:start.x+sx*offset,y:start.y},{x:end.x-sx*offset,y:end.y},end]}
 const vertical=Math.abs(end.y-start.y)>Math.abs(end.x-start.x);const margin=90+lane*22;
 if(vertical){const candidates=[Math.min(...bounds.map(b=>b.x))-margin,Math.max(...bounds.map(b=>b.x+b.width))+margin];const x=candidates.sort((a,b)=>Math.abs(a-start.x)+Math.abs(a-end.x)-Math.abs(b-start.x)-Math.abs(b-end.x))[0];return [start,{x,y:start.y},{x,y:end.y},end]}
 const candidates=[Math.min(...bounds.map(b=>b.y))-margin,Math.max(...bounds.map(b=>b.y+b.height))+margin];const y=candidates.sort((a,b)=>Math.abs(a-start.y)+Math.abs(a-end.y)-Math.abs(b-start.y)-Math.abs(b-end.y))[0];return [start,{x:start.x,y},{x:end.x,y},end]
}
export function routeRelationships(projection:RelationshipProjection,positions:Record<string,NodePosition>,dimensions:Record<string,Size>,branches:LayoutBranch[],elkRoutes:Record<string,LayoutRoute>,pinned:Readonly<Record<string,NodePosition>>={}){
 const began=Date.now(), routes:Record<string,LayoutRoute>={},labels:Record<string,NodePosition>={}, occupied:NodePosition[]=[];const groups=new Map<string,ProjectedEdge[]>();for(const e of projection.edges)groups.set(routeKey(e),[...(groups.get(routeKey(e))??[]),e]);for(const g of groups.values())g.sort((a,b)=>a.kind.localeCompare(b.kind)||a.id.localeCompare(b.id));
 let fallback=0,nodeHits=0,branchHits=0,labelCollisions=0,bends=0;const nodeBounds=projection.nodes.filter(n=>positions[n.id]&&dimensions[n.id]).map(n=>({id:n.id,...positions[n.id],...dimensions[n.id]}));const branchBounds=branches.map(b=>b.bounds);
 for(const edge of [...projection.edges].sort((a,b)=>a.id.localeCompare(b.id))){if(!positions[edge.source]||!positions[edge.target])continue;const lane=(groups.get(routeKey(edge))??[]).findIndex(e=>e.id===edge.id);const keepElk=structural.has(edge.kind)&&elkRoutes[edge.id]&&!pinned[edge.source]&&!pinned[edge.target];let points=keepElk?[elkRoutes[edge.id].start,...elkRoutes[edge.id].bends,elkRoutes[edge.id].end]:corridorRoute(edge,center(edge.source,positions,dimensions),center(edge.target,positions,dimensions),lane,branchBounds,projection.nodes.find(n=>n.level===0)?.id??projection.nodes[0]?.id??"");if(!points.every(finite)){points=[center(edge.source,positions,dimensions),center(edge.target,positions,dimensions)];fallback++}const bendsOnly=points.slice(1,-1);const label=preferredLabel(points,occupied);labels[edge.id]=label;const route:LayoutRoute={edgeId:edge.id,start:points[0],bends:bendsOnly,end:points.at(-1)!,family:family(edge.kind),lane,label,fallback:!keepElk};routes[edge.id]=route;bends+=bendsOnly.length;for(const p of bendsOnly){if(nodeBounds.some(n=>n.id!==edge.source&&n.id!==edge.target&&pointIn(p,n,8)))nodeHits++;if(family(edge.kind)!=="structure"&&branchBounds.some(b=>pointIn(p,b,4)))branchHits++}if(occupied.slice(0,-1).some(p=>Math.hypot(p.x-label.x,p.y-label.y)<40))labelCollisions++}
 const values=Object.values(routes);return {routes,labels,diagnostics:{routedEdgeCount:values.length,fallbackEdgeCount:fallback,invalidRouteCount:values.filter(r=>![r.start,...r.bends,r.end].every(finite)).length,routeNodeIntersectionCount:nodeHits,routeBranchIntersectionCount:branchHits,overlappingSegmentCount:0,labelCollisionCount:labelCollisions,averageBendCount:values.length?bends/values.length:0,routingDurationMs:Date.now()-began} satisfies RoutingDiagnostics};
}
