export type Domain="Teamcenter"|"Windchill"|"SAP"|"Configit"|"Requirement"|"Change"|"Document"|"Supplier"|"Excel";
export type EClass="authoritative"|"deterministic"|"verified"|"heuristic"|"unresolved";
export type ENode={id:string;label:string;data:{domain:Domain;kind:string;evidence:EClass;cluster:string;importance:number;nativeId:string}};
export type EEdge={id:string;source:string;target:string;label:string;data:{family:string;evidence:EClass;aggregated?:number}};
const domains:Domain[]=["Teamcenter","Windchill","SAP","Configit","Requirement","Change","Document","Supplier","Excel"];
const kinds:Record<Domain,string[]>= {Teamcenter:["Product","Assembly","Part","Occurrence","Item Revision"],Windchill:["Part Version","Change Context"],SAP:["Material","Stock","Movement","FI Document"],Configit:["Model","Rule","Option"],Requirement:["Requirement"],Change:["Change Notice"],Document:["Drawing","Specification"],Supplier:["Supplier Evidence"],Excel:["Provenance Row"]};
function base(){const nodes:ENode[]=[
{id:"product",label:"Screwjack_002403",data:{domain:"Teamcenter",kind:"Product",evidence:"authoritative",cluster:"Product structure",importance:10,nativeId:"002403"}},
{id:"body",label:"Body_002409",data:{domain:"Teamcenter",kind:"Assembly",evidence:"authoritative",cluster:"Product structure",importance:8,nativeId:"002409"}},
{id:"occ",label:"Spindle occurrence",data:{domain:"Teamcenter",kind:"Occurrence",evidence:"authoritative",cluster:"Product structure",importance:7,nativeId:"OCC-17"}},
{id:"spindle",label:"Screw Spindle_002410",data:{domain:"Teamcenter",kind:"Part",evidence:"authoritative",cluster:"Product structure",importance:10,nativeId:"002410"}},
{id:"wc",label:"Windchill 002410 B.1",data:{domain:"Windchill",kind:"Part Version",evidence:"deterministic",cluster:"Windchill records",importance:8,nativeId:"OR:wt.part.WTPart:2410"}},
{id:"req",label:"R-42 Load capacity",data:{domain:"Requirement",kind:"Requirement",evidence:"verified",cluster:"Requirements",importance:9,nativeId:"R-42"}},
{id:"change",label:"CN-8 Spindle update",data:{domain:"Change",kind:"Change Notice",evidence:"verified",cluster:"Change impact",importance:7,nativeId:"CN-8"}},
{id:"doc",label:"Drawing D-410",data:{domain:"Document",kind:"Drawing",evidence:"authoritative",cluster:"Documents",importance:6,nativeId:"D-410"}},
{id:"mat",label:"SAP Material 002410",data:{domain:"SAP",kind:"Material",evidence:"deterministic",cluster:"SAP operations",importance:10,nativeId:"002410"}},
{id:"stock",label:"Plant 1000 · 84 units",data:{domain:"SAP",kind:"Stock",evidence:"authoritative",cluster:"SAP operations",importance:5,nativeId:"MARD-1000"}},
{id:"move",label:"Material Doc 490001",data:{domain:"SAP",kind:"Movement",evidence:"authoritative",cluster:"SAP operations",importance:8,nativeId:"490001"}},
{id:"fi",label:"FI Document 510001",data:{domain:"SAP",kind:"FI Document",evidence:"authoritative",cluster:"SAP finance",importance:8,nativeId:"510001"}},
{id:"cfg",label:"BODY configuration rule",data:{domain:"Configit",kind:"Rule",evidence:"authoritative",cluster:"Configuration",importance:6,nativeId:"RULE-BODY"}},
{id:"excel",label:"Excel BOM row 17",data:{domain:"Excel",kind:"Provenance Row",evidence:"heuristic",cluster:"Provenance",importance:3,nativeId:"ROW-17"}},
{id:"supplier",label:"Supplier reference missing",data:{domain:"Supplier",kind:"Supplier Evidence",evidence:"unresolved",cluster:"Supplier evidence",importance:3,nativeId:"SUP-?"}}
];const edges:EEdge[]=[
{id:"e1",source:"product",target:"body",label:"contains",data:{family:"structural",evidence:"authoritative"}},{id:"e2",source:"body",target:"occ",label:"contains occurrence",data:{family:"occurrence",evidence:"authoritative"}},{id:"e3",source:"occ",target:"spindle",label:"occurrence of",data:{family:"occurrence",evidence:"authoritative"}},{id:"e4",source:"spindle",target:"wc",label:"deterministic match",data:{family:"cross-source",evidence:"deterministic"}},{id:"e5",source:"req",target:"spindle",label:"satisfied by",data:{family:"requirement",evidence:"verified"}},{id:"e6",source:"wc",target:"change",label:"affected by",data:{family:"change",evidence:"verified"}},{id:"e7",source:"wc",target:"doc",label:"documented by",data:{family:"document",evidence:"authoritative"}},{id:"e8",source:"spindle",target:"mat",label:"represented in",data:{family:"cross-source",evidence:"deterministic"}},{id:"e9",source:"mat",target:"stock",label:"has stock",data:{family:"sap",evidence:"authoritative"}},{id:"e10",source:"mat",target:"move",label:"has movement",data:{family:"sap",evidence:"authoritative"}},{id:"e11",source:"move",target:"fi",label:"posted through",data:{family:"financial",evidence:"authoritative"}},{id:"e12",source:"product",target:"cfg",label:"configured by",data:{family:"configuration",evidence:"authoritative"}},{id:"e13",source:"body",target:"excel",label:"heuristic match",data:{family:"heuristic",evidence:"heuristic"}},{id:"e14",source:"body",target:"supplier",label:"unresolved reference",data:{family:"unresolved",evidence:"unresolved"}}];return{nodes,edges}}
function rand(i:number){return((i*9301+49297)%233280)/233280}
export function makeDataset(count:number){const started=performance.now();const b=base();const nodes=[...b.nodes],edges=[...b.edges];for(let i=nodes.length;i<count;i++){const domain=domains[i%domains.length],kind=kinds[domain][i%kinds[domain].length],id=`sim-${i}`,parent=i<50?nodes[Math.max(0,Math.floor(rand(i)*nodes.length))].id:`sim-${Math.max(15,Math.floor(rand(i)*i))}`;nodes.push({id,label:`${domain} ${kind} ${String(i).padStart(5,"0")}`,data:{domain,kind,evidence:i%31===0?"unresolved":i%17===0?"heuristic":i%11===0?"deterministic":"authoritative",cluster:domain==="SAP"?`SAP ${i%6}`:domain,importance:1+(i%10),nativeId:`${domain.slice(0,3).toUpperCase()}-${i}`}});edges.push({id:`sim-edge-${i}`,source:parent,target:id,label:domain==="SAP"?"operational evidence":"related evidence",data:{family:domain.toLowerCase(),evidence:i%31===0?"unresolved":i%17===0?"heuristic":"authoritative"}});if(i%7===0)edges.push({id:`cross-${i}`,source:id,target:nodes[Math.floor(rand(i+7)*nodes.length)].id,label:"cross-source link",data:{family:"cross-source",evidence:"deterministic"}})}return{nodes,edges,duration:performance.now()-started}}
export const colors:Record<Domain,string>={Teamcenter:"#06b6d4",Windchill:"#8b5cf6",SAP:"#22c55e",Configit:"#ec4899",Requirement:"#a855f7",Change:"#f97316",Document:"#eab308",Supplier:"#14b8a6",Excel:"#94a3b8"};
export const pathIds=new Set(["req","spindle","mat","move","fi"]);
