"use client";
import { AnimatePresence, motion } from "motion/react";
import { IconAlertTriangle, IconCheck, IconRefresh, IconX } from "@tabler/icons-react";
import type { EnterpriseSource, ItemSearchCandidate, ResolvedItemContext, SourceSearchResult } from "@/types/item-explorer";
import type { LatticeInspectorTarget } from "@/types/lattice";
import { latticeSourceMeta } from "@/lib/lattice/source-meta";

type Props = { target: LatticeInspectorTarget; results: SourceSearchResult[]; selections: ResolvedItemContext; centerLabel: string; onClose: () => void; onSelect: (candidate: ItemSearchCandidate) => void; onClear: (source: EnterpriseSource) => void; onRetry: (source: EnterpriseSource) => void; onItemIdMode: () => void };
export function LatticeInspector({ target, results, selections, centerLabel, onClose, onSelect, onClear, onRetry, onItemIdMode }: Props) {
  const result = target?.kind === "source" ? results.find((item) => item.source === target.source) : undefined;
  return <AnimatePresence>{target ? <motion.aside initial={{ opacity:0,x:28 }} animate={{ opacity:1,x:0 }} exit={{ opacity:0,x:24 }} className="absolute bottom-4 right-4 top-4 z-40 flex w-[min(390px,calc(100%-32px))] flex-col overflow-hidden rounded-2xl border border-slate-700 bg-[#07101f]/96 shadow-2xl backdrop-blur-xl">
    <header className="flex items-start justify-between border-b border-slate-800 p-4"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-cyan-300">{target.kind === "item" ? "Enterprise item context" : latticeSourceMeta[target.source].domain}</p><h2 className="mt-1 text-lg font-semibold">{target.kind === "item" ? centerLabel : latticeSourceMeta[target.source].label}</h2></div><button onClick={onClose} aria-label="Close inspector" className="flex h-9 w-9 items-center justify-center rounded-lg border border-slate-700 text-slate-400 hover:text-white"><IconX className="h-4 w-4"/></button></header>
    {target.kind === "item" ? <ItemContext selections={selections}/> : <SourceContext result={result} selection={selections[target.source]} onSelect={onSelect} onClear={() => onClear(target.source)} onRetry={() => onRetry(target.source)} onItemIdMode={onItemIdMode}/>} 
  </motion.aside> : null}</AnimatePresence>;
}
function ItemContext({ selections }: { selections: ResolvedItemContext }) {
  const entries = Object.values(selections).filter(Boolean);
  return <div className="min-h-0 flex-1 overflow-y-auto p-4"><p className="text-sm leading-6 text-slate-400">Resolved records form the current investigation context. Source values remain independent and traceable.</p><div className="mt-5 space-y-3">{entries.length ? entries.map((entry) => <div key={entry!.source} className="rounded-xl border border-slate-800 bg-slate-900/60 p-3"><div className="flex items-center justify-between"><b className="text-sm">{latticeSourceMeta[entry!.source].label}</b><IconCheck className="h-4 w-4 text-emerald-400"/></div><p className="mt-2 text-sm font-semibold">{entry!.candidate.name}</p><p className="mt-1 font-mono text-xs text-slate-500">{entry!.candidate.nativeId}</p></div>) : <Empty message="Select a candidate from a source node to establish the item context."/>}</div></div>;
}
function SourceContext({ result, selection, onSelect, onClear, onRetry, onItemIdMode }: { result?: SourceSearchResult; selection?: ResolvedItemContext[EnterpriseSource]; onSelect: (candidate: ItemSearchCandidate) => void; onClear: () => void; onRetry: () => void; onItemIdMode: () => void }) {
  if (!result || result.status === "idle") return <Empty message="Run a search from the center of the arena."/>;
  if (result.status === "searching") return <div className="p-4"><div className="h-1.5 overflow-hidden rounded-full bg-slate-800"><div className="h-full w-1/3 animate-pulse rounded-full bg-cyan-500"/></div><p className="mt-4 text-sm text-slate-400">Searching the connected source...</p></div>;
  if (result.status === "failed" || result.status === "timed-out") return <Outcome title={result.status === "timed-out" ? "Search timed out" : "Source unavailable"} message={result.error || "The source did not return a usable response."} action={<button onClick={onRetry} className="action"><IconRefresh className="h-4 w-4"/>Retry</button>}/>;
  if (result.status === "unsupported") return <Outcome title="Name search unavailable" message={result.capabilityNote || "Use a source-native identifier for this application."} action={<button onClick={onItemIdMode} className="action">Search by Item ID</button>}/>;
  if (result.status === "empty") return <Outcome title="No matching record" message="The source returned no candidates for this query." action={<button onClick={onItemIdMode} className="action">Search by Item ID</button>}/>;
  return <div className="min-h-0 flex-1 overflow-y-auto p-3"><div className="mb-3 flex items-center justify-between px-1"><p className="text-xs text-slate-500">{result.candidates.length} candidate{result.candidates.length === 1 ? "" : "s"}</p>{selection ? <button onClick={onClear} className="text-xs font-semibold text-cyan-300">Replace selection</button> : null}</div><div className="space-y-2">{result.candidates.map((candidate) => { const selected = selection?.candidate.candidateId === candidate.candidateId; return <button key={candidate.candidateId} onClick={() => onSelect(candidate)} className={`w-full rounded-xl border p-3 text-left transition ${selected ? "border-cyan-400 bg-cyan-500/10" : "border-slate-800 bg-slate-900/55 hover:border-slate-600"}`}><div className="flex items-start gap-3"><span className={`mt-1 flex h-5 w-5 shrink-0 items-center justify-center rounded-full border ${selected ? "border-cyan-400 bg-cyan-500" : "border-slate-600"}`}>{selected ? <IconCheck className="h-3 w-3"/> : null}</span><span className="min-w-0"><b className="block text-sm">{candidate.name}</b><span className="mt-1 block font-mono text-xs text-slate-500">{candidate.nativeId}</span>{candidate.description ? <span className="mt-2 line-clamp-2 block text-xs leading-5 text-slate-400">{candidate.description}</span> : null}<span className="mt-2 block text-xs font-semibold text-cyan-300">{candidate.matchReasons[0]}</span></span></div></button>; })}</div></div>;
}
function Empty({ message }: { message: string }) { return <div className="flex flex-1 items-center justify-center p-7 text-center"><div><span className="mx-auto flex h-11 w-11 items-center justify-center rounded-xl bg-slate-900 text-slate-500"><IconAlertTriangle className="h-5 w-5"/></span><p className="mt-4 text-sm leading-6 text-slate-400">{message}</p></div></div>; }
function Outcome({ title, message, action }: { title: string; message: string; action: React.ReactNode }) { return <div className="p-5"><IconAlertTriangle className="h-5 w-5 text-amber-400"/><h3 className="mt-4 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{message}</p><div className="mt-4">{action}</div><style>{`.action{display:inline-flex;height:2.5rem;align-items:center;gap:.5rem;border-radius:.6rem;background:#0891b2;padding:0 .9rem;font-size:.75rem;font-weight:700;color:white}`}</style></div>; }
